import { useState, useEffect } from 'react';
import { Icon } from './Icons.jsx';
import { getAuthHeaders } from '../utils/authHeaders.js';
import DiagramSVG from './DiagramSVG.jsx';
import { generateSlug, getProblemBySlug } from '../data/problems.js';
import { getLeetCodeUrl } from '../data/leetcodeUrls.js';
import problemsFull from '../data/problems-full.json';
import { codingCategories, codingCategoryMap, codingTopics } from '../data/topics/codingTopics.js';
import { systemDesignCategories, systemDesignCategoryMap, systemDesignTopics } from '../data/topics/systemDesignTopics.js';
import { systemDesignProblemCategories, systemDesignProblemCategoryMap, systemDesigns, lldProblemCategories, lldProblemCategoryMap } from '../data/topics/systemDesignProblems.js';
import { lldProblems } from '../data/topics/lldProblems.js';
import { concurrencyTopics } from '../data/topics/concurrencyTopics.js';
import { behavioralCategories, topicCategoryMap, behavioralTopics } from '../data/topics/behavioralTopics.js';
import { companyPrep } from '../data/topics/companyPrep.js';

// Unified card styling - clean, minimal design with larger fonts
import CloudArchitectureDiagram from './docs/CloudArchitectureDiagram.jsx';
import FormattedContent from './docs/FormattedContent.jsx';
import TopicDetail from './docs/TopicDetail.jsx';
const CARD_STYLES = {
  // Standard card with subtle border
  card: {
    background: '#111318',
    border: '1px solid #e2e8f0',
    borderRadius: '16px',
  },
  // Card header - uses Ascend emerald accent
  header: {
    background: 'rgba(16, 185, 129, 0.05)',
    borderBottom: '1px solid rgba(16, 185, 129, 0.15)',
    padding: '18px 24px',
  },
  // Card body
  body: {
    padding: '24px',
  },
  // Code block
  code: {
    background: '#0d1117',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
  },
};

// Font size scale - increased for better readability
const FONT_SIZES = {
  xs: '14px',
  sm: '16px',
  base: '18px',
  lg: '20px',
  xl: '24px',
  '2xl': '28px',
  '3xl': '32px',
};

// Ascend brand colors - emerald green
const ASCEND_COLORS = {
  primary: '#10b981',
  primaryHover: '#059669',
  primaryLight: 'rgba(16, 185, 129, 0.15)',
  primaryBorder: 'rgba(16, 185, 129, 0.25)',
  gradient: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
};

// Get API URL based on environment (Electron vs Web)
const getApiUrl = () => {
  if (window.electronAPI?.isElectron) {
    return 'http://127.0.0.1:3001';
  }
  return import.meta.env.VITE_API_URL || 'https://capra-backend.up.railway.app';
};

/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */

/**
 * Documentation Page with Sidebar Navigation and Topic Details
 * Original educational content for interview preparation
 */
export default function DocsPage({ onBack }) {
  const isElectron = window.electronAPI?.isElectron || false;
  // Initialize state from URL params for persistence on refresh
  const getInitialState = () => {
    const params = new URLSearchParams(window.location.search);
    const rawPage = params.get('page') || 'coding';
    // Support 'dsa' as alias for 'coding'
    const page = rawPage === 'dsa' ? 'coding' : rawPage;
    return {
      page,
      topic: params.get('topic') || null,
    };
  };

  const initialState = getInitialState();
  const [activePage, setActivePageState] = useState(initialState.page);
  const [searchQuery, setSearchQuery] = useState('');
  const [sortOrder, setSortOrder] = useState('a-z');
  const [selectedTopic, setSelectedTopicState] = useState(initialState.topic);

  // Sync URL with state via useEffect (avoids stale closure issues)
  useEffect(() => {
    const params = new URLSearchParams();
    if (activePage && activePage !== 'coding') params.set('page', activePage);
    if (selectedTopic) params.set('topic', selectedTopic);
    const queryString = params.toString();
    const newURL = queryString ? `/prepare?${queryString}` : '/prepare';
    window.history.replaceState({}, '', newURL);
  }, [activePage, selectedTopic]);

  // Wrapped setters
  const setActivePage = (page) => {
    setActivePageState(page);
    setSelectedTopicState(null);
  };

  const setSelectedTopic = (topic) => {
    setSelectedTopicState(topic);
    if (topic) {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  // Diagram generation state
  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [diagramData, setDiagramData] = useState(null);
  const [diagramError, setDiagramError] = useState(null);
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  const [diagramCloudProvider, setDiagramCloudProvider] = useState('aws');
  const [diagramCache, setDiagramCache] = useState({}); // Cache diagrams by topic+level+provider

  // Theory questions expanded state
  const [expandedTheoryQuestions, setExpandedTheoryQuestions] = useState({});

  // ── Interactive features (AlgoMaster-inspired) ──
  const [completedTopics, setCompletedTopics] = useState(() => {
    try { return JSON.parse(localStorage.getItem('ascend_completed_topics') || '{}'); } catch { return {}; }
  });
  const [starredTopics, setStarredTopics] = useState(() => {
    try { return JSON.parse(localStorage.getItem('ascend_starred_topics') || '{}'); } catch { return {}; }
  });
  const [showAskAI, setShowAskAI] = useState(false);
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiAnswer, setAiAnswer] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [showRoadmap, setShowRoadmap] = useState(false);

  const toggleComplete = (topicId) => {
    setCompletedTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      localStorage.setItem('ascend_completed_topics', JSON.stringify(next));
      return next;
    });
  };

  const toggleStar = (topicId) => {
    setStarredTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      localStorage.setItem('ascend_starred_topics', JSON.stringify(next));
      return next;
    });
  };

  const handleAskAI = async () => {
    if (!aiQuestion.trim()) return;
    setAiLoading(true);
    setAiAnswer('');
    try {
      const res = await fetch(`${API_URL}/api/solve/followup`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({
          question: aiQuestion,
          context: topicDetails ? `Topic: ${topicDetails.title}. ${topicDetails.description || ''} ${topicDetails.introduction || ''}` : '',
          problem: '',
          code: '',
        }),
      });
      const data = await res.json();
      setAiAnswer(data.answer || data.result || 'No answer available.');
    } catch (err) {
      setAiAnswer('Failed to get AI response. Please try again.');
    } finally {
      setAiLoading(false);
    }
  };

  // Calculate progress
  const getProgress = () => {
    const topics = activePage === 'coding' ? codingTopics :
      activePage === 'system-design' ? [...systemDesignTopics, ...systemDesigns, ...lldProblems, ...concurrencyTopics] :
      [...behavioralTopics, ...companyPrep];
    const total = topics.length;
    const completed = topics.filter(t => completedTopics[t.id]).length;
    return { total, completed, percent: total > 0 ? Math.round((completed / total) * 100) : 0 };
  };

  // Reset diagram when topic changes
  useEffect(() => {
    setDiagramData(null);
    setDiagramError(null);
    // Check cache for existing diagram
    const cacheKey = `${selectedTopic}-${diagramDetailLevel}-${diagramCloudProvider}`;
    if (selectedTopic && diagramCache[cacheKey]) {
      setDiagramData(diagramCache[cacheKey]);
    }
  }, [selectedTopic]);

  // Generate architecture diagram
  const handleGenerateDiagram = async (topicTitle, detailLevel = 'overview', provider = diagramCloudProvider) => {
    if (!topicTitle) return;

    // Check cache first
    const cacheKey = `${selectedTopic}-${detailLevel}-${provider}`;
    if (diagramCache[cacheKey]) {
      setDiagramData(diagramCache[cacheKey]);
      setDiagramDetailLevel(detailLevel);
      setDiagramCloudProvider(provider);
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramDetailLevel(detailLevel);
    setDiagramCloudProvider(provider);

    try {
      const API_URL = getApiUrl();
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question: `Design ${topicTitle}`,
          cloudProvider: provider,
          difficulty: 'medium',
          category: 'System Design',
          format: 'png',
          detailLevel: detailLevel
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch {
          // Response wasn't JSON
        }
        throw new Error(errorMessage);
      }

      const data = await response.json();
      if (data.success && data.image_url) {
        // Construct full URL
        const fullImageUrl = data.image_url.startsWith('http')
          ? data.image_url
          : `${API_URL}${data.image_url}`;

        const result = { ...data, imageUrl: fullImageUrl };
        setDiagramData(result);
        // Cache the result
        setDiagramCache(prev => ({ ...prev, [cacheKey]: result }));
      } else {
        throw new Error(data.error || 'Diagram generation failed');
      }
    } catch (err) {
      console.error('Diagram generation error:', err);
      setDiagramError(err.message);
    } finally {
      setGeneratingDiagram(false);
    }
  };

  // Sidebar navigation items
  const navItems = [
    { id: 'coding', label: 'Data Structures & Algorithms', icon: 'code' },
    { id: 'system-design', label: 'System Design', icon: 'systemDesign' },
    { id: 'behavioral', label: 'Behavioral', icon: 'users' },
  ];

  // Coding topic categories
  // Filter and sort topics based on active page
  const getFilteredTopics = () => {
    let topics = [];
    if (activePage === 'coding') topics = codingTopics;
    else if (activePage === 'system-design') topics = systemDesignTopics;
    else if (activePage === 'behavioral') topics = behavioralTopics;
    else return [];

    return topics
      .filter(topic => topic.title.toLowerCase().includes(searchQuery.toLowerCase()))
      .sort((a, b) => {
        if (sortOrder === 'a-z') return a.title.localeCompare(b.title);
        if (sortOrder === 'z-a') return b.title.localeCompare(a.title);
        if (sortOrder === 'most') return b.questions - a.questions;
        if (sortOrder === 'least') return a.questions - b.questions;
        return 0;
      });
  };

  const filteredTopics = getFilteredTopics();

  // Get page title and color
  const getPageConfig = () => {
    switch (activePage) {
      case 'coding': return { title: 'Data Structures & Algorithms', color: '#10b981' };
      case 'system-design': return { title: 'System Design', color: '#3b82f6' };
      case 'behavioral': return { title: 'Behavioral Interviews', color: '#a855f7' };
      default: return { title: 'Documentation', color: '#10b981' };
    }
  };

  const pageConfig = getPageConfig();

  // Find selected topic details
  const getSelectedTopicDetails = () => {
    if (!selectedTopic) return null;
    if (activePage === 'coding') return codingTopics.find(t => t.id === selectedTopic);
    if (activePage === 'system-design') {
      return systemDesignTopics.find(t => t.id === selectedTopic) ||
             systemDesigns.find(t => t.id === selectedTopic) ||
             lldProblems.find(t => t.id === selectedTopic) ||
             concurrencyTopics.find(t => t.id === selectedTopic);
    }
    if (activePage === 'behavioral') {
      return behavioralTopics.find(t => t.id === selectedTopic) ||
             companyPrep.find(t => t.id === selectedTopic);
    }
    return null;
  };

  const topicDetails = getSelectedTopicDetails();

  // Render topic detail view

  // Generate table of contents for topic detail view
  const getTableOfContents = () => {
    if (!topicDetails) return [];
    const toc = [];

    if (activePage === 'coding') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.whenToUse) toc.push({ id: 'when-to-use', label: 'When to Use' });
      if (topicDetails.approach) toc.push({ id: 'approach', label: 'Approach' });
      if (topicDetails.codeExamples) toc.push({ id: 'code-examples', label: 'Code Examples' });
      if (topicDetails.commonProblems) toc.push({ id: 'practice', label: 'Practice Problems' });
      if (topicDetails.tips) toc.push({ id: 'tips', label: 'Interview Tips' });
    } else if (activePage === 'system-design') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.requirements) toc.push({ id: 'requirements', label: 'Requirements' });
      if (topicDetails.keyQuestions) toc.push({ id: 'key-questions', label: 'Key Questions' });
      if (topicDetails.estimation) toc.push({ id: 'estimation', label: 'Estimation' });
      if (topicDetails.apiDesign) toc.push({ id: 'api-design', label: 'API Design' });
      if (topicDetails.dataModel) toc.push({ id: 'data-model', label: 'Data Model' });
      if (topicDetails.basicImplementation) toc.push({ id: 'architecture', label: 'Architecture' });
    } else if (activePage === 'behavioral') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.keyQuestions) toc.push({ id: 'key-questions', label: 'Key Questions' });
      if (topicDetails.starExample) toc.push({ id: 'star-example', label: 'STAR Example' });
      if (topicDetails.sampleQuestions) toc.push({ id: 'sample-questions', label: 'Sample Questions' });
      if (topicDetails.tips) toc.push({ id: 'tips', label: 'Tips' });
    }
    return toc;
  };

  const tableOfContents = getTableOfContents();

  return (
    <div className="min-h-screen" style={{ background: '#ffffff', fontFamily: "'Source Sans 3', sans-serif", color: '#1a1a1a' }}>
      {/* Electron drag region */}
      {isElectron && (
        <div
          className="fixed top-0 left-0 right-0 h-8 z-50"
          style={{ WebkitAppRegion: 'drag' }}
        />
      )}

      {/* Background grid pattern */}
      <div
        className="fixed inset-0 pointer-events-none opacity-30"
        style={{
          backgroundImage: `
            linear-gradient(rgba(79, 79, 79, 0.08) 1px, transparent 1px),
            linear-gradient(90deg, rgba(79, 79, 79, 0.08) 1px, transparent 1px)
          `,
          backgroundSize: '60px 60px'
        }}
      />

      <div className="relative flex">
        {/* Left Sidebar - Navigation */}
        <div className="w-72 flex-shrink-0 h-screen sticky top-0 flex flex-col" style={{ background: '#f8fafc', borderRight: '1px solid #e2e8f0' }}>
          {/* Logo */}
          <div className="p-6">
            <a href="/prepare" className="flex items-center gap-3 group">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center transition-transform group-hover:scale-105" style={{ background: 'linear-gradient(135deg, #10b981, #059669)' }}>
                <Icon name="ascend" size={22} className="text-white" />
              </div>
              <div>
                <span className="text-sm font-bold text-gray-900">Ascend</span>
                <span className="block text-sm text-gray-700">Job Interview Preparation</span>
              </div>
            </a>
          </div>

          {/* Category Navigation */}
          <nav className="flex-1 px-4 py-2 overflow-y-auto">
            <div className="text-sm font-semibold text-gray-500 uppercase tracking-wider px-3 mb-3">Learning Tracks</div>
            {navItems.map((item) => {
              const isActive = activePage === item.id;
              const accentColor = item.id === 'coding' ? '#10b981' : item.id === 'system-design' ? '#3b82f6' : '#a855f7';
              return (
                <button
                  key={item.id}
                  onClick={() => { setActivePage(item.id); }}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm transition-all mb-1 ${
                    isActive ? 'text-gray-900 font-semibold' : 'text-gray-700 hover:text-gray-900 hover:bg-gray-50'
                  }`}
                  style={isActive ? {
                    background: `${accentColor}08`,
                    border: `1px solid ${accentColor}25`
                  } : {}}
                >
                  <div
                    className="w-7 h-7 rounded-lg flex items-center justify-center transition-transform"
                    style={{ background: isActive ? `${accentColor}20` : 'rgba(255,255,255,0.05)' }}
                  >
                    <Icon name={item.icon} size={16} style={{ color: isActive ? accentColor : '#9ca3af' }} />
                  </div>
                  <div className="flex-1 text-left">
                    <span className="font-medium block">{item.label}</span>
                    <span className="text-sm text-gray-700">
                      {item.id === 'coding' ? `${codingTopics.length} topics` :
                       item.id === 'system-design' ? `${systemDesignTopics.length + systemDesigns.length + lldProblems.length + concurrencyTopics.length} topics` :
                       `${behavioralTopics.length} topics`}
                    </span>
                  </div>
                  {isActive && <div className="w-1.5 h-1.5 rounded-full" style={{ background: accentColor }} />}
                </button>
              );
            })}

            {/* Practice Links */}
            <div className="text-sm font-semibold text-gray-500 uppercase tracking-wider px-3 mt-8 mb-3">Practice Links</div>
            {[
              { href: '/app/coding', label: 'Coding', icon: 'code', color: '#10b981' },
              { href: '/app/design', label: 'Design', icon: 'systemDesign', color: '#3b82f6' },
              { href: '/app/prep', label: 'Interview Prep', icon: 'briefcase', color: '#a855f7' },
            ].map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="flex items-center gap-3 px-4 py-2.5 rounded-xl text-sm transition-all hover:bg-gray-50 mb-1"
                style={{ color: link.color }}
              >
                <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${link.color}15` }}>
                  <Icon name={link.icon} size={16} />
                </div>
                <span className="font-medium">{link.label}</span>
              </a>
            ))}
          </nav>

          {/* Pro Badge */}
          <div className="p-4 m-4 rounded-xl" style={{ background: '#f5f3ff', border: '1px solid #ddd6fe' }}>
            <div className="flex items-center gap-2 mb-2">
              <Icon name="crown" size={16} className="text-emerald-600" />
              <span className="text-sm font-semibold text-gray-900">Ascend Pro</span>
            </div>
            <p className="text-sm text-gray-400 mb-3">Get AI-powered practice with real-time feedback</p>
            <a href="/app/coding" className="block text-center py-2 rounded-lg text-sm font-medium text-white transition-all hover:opacity-90" style={{ background: 'linear-gradient(135deg, #10b981, #059669)' }}>
              Try Free
            </a>
          </div>
        </div>

        {/* Main Content Area + Right Sidebar */}
        <div className="flex-1 min-h-screen flex">
          {/* Center Content */}
          <div className="flex-1 min-w-0 mx-auto" style={{ maxWidth: '100%', padding: '0 40px' }}>
            {/* Top Bar */}
            <div className="sticky top-0 z-20 px-4 py-4 flex items-center justify-between" style={{ background: 'rgba(255,255,255,0.95)', backdropFilter: 'blur(12px)', borderBottom: '1px solid #e2e8f0' }}>
              {/* Breadcrumb */}
              <div className="flex items-center gap-2 text-sm">
                {isElectron && onBack && (
                  <button
                    onClick={onBack}
                    className="flex items-center gap-1 text-gray-700 hover:text-gray-900 transition-colors mr-2"
                  >
                    <Icon name="arrowLeft" size={16} />
                    <span>Back</span>
                  </button>
                )}
                <button onClick={() => setSelectedTopic(null)} className="text-gray-700 hover:text-gray-900 transition-colors cursor-pointer">Learn</button>
                <Icon name="chevronRight" size={14} className="text-gray-600" />
                {selectedTopic && topicDetails ? (
                  <>
                    <button onClick={() => setSelectedTopic(null)} className="text-gray-700 hover:text-gray-900 transition-colors cursor-pointer">{pageConfig.title}</button>
                    <Icon name="chevronRight" size={14} className="text-gray-600" />
                    <span className="text-gray-900">{topicDetails.title}</span>
                  </>
                ) : (
                  <span className="text-gray-900">{pageConfig.title}</span>
                )}
              </div>
              {!selectedTopic && (
                <div className="flex items-center gap-3">
                  <a
                    href="/app"
                    className="px-4 py-2 rounded-lg text-sm font-medium transition-all hover:opacity-90"
                    style={{ background: 'linear-gradient(135deg, #10b981, #059669)', color: '#fff' }}
                  >
                    Start Practice
                  </a>
                </div>
              )}
            </div>

            {/* Content */}
            <div className="px-4 py-4">
              {/* Show topic detail or list */}
              {selectedTopic ? <TopicDetail activePage={activePage} selectedTopic={selectedTopic} topicDetails={topicDetails} pageConfig={pageConfig} completedTopics={completedTopics} starredTopics={starredTopics} toggleComplete={toggleComplete} toggleStar={toggleStar} showAskAI={showAskAI} setShowAskAI={setShowAskAI} aiQuestion={aiQuestion} setAiQuestion={setAiQuestion} aiAnswer={aiAnswer} aiLoading={aiLoading} handleAskAI={handleAskAI} showRoadmap={showRoadmap} setShowRoadmap={setShowRoadmap} expandedTheoryQuestions={expandedTheoryQuestions} setExpandedTheoryQuestions={setExpandedTheoryQuestions} setSelectedTopic={setSelectedTopic} generatingDiagram={generatingDiagram} diagramData={diagramData} diagramError={diagramError} diagramDetailLevel={diagramDetailLevel} setDiagramDetailLevel={setDiagramDetailLevel} diagramCloudProvider={diagramCloudProvider} setDiagramCloudProvider={setDiagramCloudProvider} generateDiagram={handleGenerateDiagram} codingTopics={codingTopics} systemDesignTopics={systemDesignTopics} systemDesigns={systemDesigns} behavioralTopics={behavioralTopics} filteredTopics={filteredTopics} /> : (
                <>
                  {/* Page Hero */}
                  <div className="mb-4">
                    <div
                      className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full text-sm font-medium mb-4"
                      style={{ background: `${pageConfig.color}15`, color: pageConfig.color }}
                    >
                      <Icon name={activePage === 'coding' ? 'code' : activePage === 'system-design' ? 'systemDesign' : 'users'} size={12} />
                      {activePage === 'coding' ? 'Algorithms' : activePage === 'system-design' ? 'Architecture' : 'Soft Skills'}
                    </div>
                    <h1 className="text-[20px] font-bold text-gray-900 mb-2">{pageConfig.title}</h1>
                    <p className="text-[14px] text-gray-700 max-w-2xl">
                      {activePage === 'coding' && 'Master the fundamental data structures and algorithms needed to ace technical interviews at top tech companies.'}
                      {activePage === 'system-design' && 'Learn to design scalable, reliable systems that can handle millions of users. Essential for senior engineering roles.'}
                      {activePage === 'behavioral' && 'Prepare compelling stories and answers for behavioral interviews using proven frameworks like STAR.'}
                    </p>
                  </div>

                  {/* Search and Filters */}
                  <div className="flex items-center gap-3 mb-3 p-3 rounded-xl" style={{ background: '#f9fafb', border: '1px solid #e2e8f0' }}>
                    <div className="relative flex-1 max-w-md">
                      <Icon name="search" size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-gray-500" />
                      <input
                        type="text"
                        placeholder="Search topics..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-11 pr-4 py-3 rounded-xl text-sm text-gray-900 placeholder-gray-400 focus:outline-none focus:ring-2 transition-all"
                        style={{ background: '#ffffff', border: '1px solid #d1d5db', '--tw-ring-color': pageConfig.color }}
                      />
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-sm text-gray-700">Sort:</span>
                      <select
                        value={sortOrder}
                        onChange={(e) => setSortOrder(e.target.value)}
                        className="px-3 py-2 rounded-lg text-sm text-gray-700 focus:outline-none cursor-pointer transition-all hover:bg-gray-100"
                        style={{ background: '#ffffff', border: '1px solid #d1d5db' }}
                      >
                        <option value="a-z">A - Z</option>
                        <option value="z-a">Z - A</option>
                        <option value="most">Most Questions</option>
                        <option value="least">Least Questions</option>
                      </select>
                    </div>
                    <div className="text-sm text-gray-700">
                      {filteredTopics.length} {filteredTopics.length === 1 ? 'topic' : 'topics'}
                    </div>
                  </div>

              {/* DSA Content */}
              {activePage === 'coding' && (
                <>
                  {/* Topic Cards - Grouped by Category */}
                  <div className="space-y-3 mb-4">
                    {codingCategories.map((category) => {
                      const categoryTopics = filteredTopics.filter(t => codingCategoryMap[t.id] === category.id);
                      if (categoryTopics.length === 0) return null;
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          {/* Category Header */}
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900">{category.name}</h3>
                              <span className="text-sm text-gray-700">{categoryTopics.length} topics</span>
                            </div>
                          </div>
                          {/* Topics in Category */}
                          <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                            {categoryTopics.map((topic) => (
                              <div
                                key={topic.id}
                                onClick={() => setSelectedTopic(topic.id)}
                                className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group"
                              >
                                <div className="flex items-center gap-3">
                                  <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}15` }}>
                                    {completedTopics[topic.id] ? <Icon name="check" size={12} className="text-emerald-600" /> : <Icon name={topic.icon} size={12} style={{ color: topic.color }} />}
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-sm font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400' : 'text-gray-900'}`}>{topic.title}</span>
                                    {starredTopics[topic.id] && <Icon name="star5" size={10} className="text-yellow-500" />}
                                    <span className="text-gray-600 text-sm ml-2 hidden md:inline">{topic.description}</span>
                                  </div>
                                </div>
                                <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                                  {topic.commonProblems?.length || topic.keyQuestions?.length || 0}Q
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Quick Reference - Enhanced */}
                  <div className="mb-4">
                    <div className="flex items-center gap-3 mb-6">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-emerald-50">
                        <Icon name="book" size={16} className="text-emerald-600" />
                      </div>
                      <h2 className="text-[16px] font-bold text-gray-900">Quick Reference</h2>
                    </div>
                    <div className="grid md:grid-cols-2 gap-3">
                      {/* Time Complexity Card */}
                      <div className="rounded-xl overflow-hidden" style={CARD_STYLES.card}>
                        <div className="px-4 py-3 border-b border-emerald-500/20" style={{ background: 'rgba(16,185,129,0.05)' }}>
                          <h3 className="text-sm text-gray-900 font-semibold flex items-center gap-2">
                            <Icon name="clock" size={16} className="text-emerald-600" />
                            Time Complexity Cheat Sheet
                          </h3>
                        </div>
                        <div className="p-4">
                          <table className="w-full text-sm">
                            <tbody>
                              {[
                                { complexity: 'O(1)', desc: 'Constant', rating: 'Best', color: '#10b981' },
                                { complexity: 'O(log n)', desc: 'Logarithmic', rating: 'Great', color: '#10b981' },
                                { complexity: 'O(n)', desc: 'Linear', rating: 'Good', color: '#eab308' },
                                { complexity: 'O(n log n)', desc: 'Linearithmic', rating: 'Fair', color: '#eab308' },
                                { complexity: 'O(n²)', desc: 'Quadratic', rating: 'Slow', color: '#f97316' },
                                { complexity: 'O(2ⁿ)', desc: 'Exponential', rating: 'Avoid', color: '#ef4444' },
                              ].map((item, i) => (
                                <tr key={i} className="border-b border-gray-200 last:border-0">
                                  <td className="py-2 font-mono text-sm text-emerald-600">{item.complexity}</td>
                                  <td className="py-2 text-gray-600">{item.desc}</td>
                                  <td className="py-2 text-right">
                                    <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${item.color}20`, color: item.color }}>
                                      {item.rating}
                                    </span>
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      {/* Data Structure Selection Card */}
                      <div className="rounded-xl overflow-hidden" style={CARD_STYLES.card}>
                        <div className="px-4 py-3 border-b border-emerald-500/20" style={{ background: 'rgba(16,185,129,0.05)' }}>
                          <h3 className="text-sm text-gray-900 font-semibold flex items-center gap-2">
                            <Icon name="database" size={16} className="text-emerald-600" />
                            When to Use What
                          </h3>
                        </div>
                        <div className="p-4">
                          <table className="w-full text-sm">
                            <tbody>
                              {[
                                { need: 'Fast lookup', solution: 'Hash Map', icon: 'hash' },
                                { need: 'Sorted data', solution: 'BST / TreeMap', icon: 'tree' },
                                { need: 'FIFO operations', solution: 'Queue', icon: 'list' },
                                { need: 'LIFO operations', solution: 'Stack', icon: 'layers' },
                                { need: 'Priority access', solution: 'Heap', icon: 'triangle' },
                                { need: 'Prefix matching', solution: 'Trie', icon: 'search' },
                              ].map((item, i) => (
                                <tr key={i} className="border-b border-gray-200 last:border-0">
                                  <td className="py-2 text-gray-600">{item.need}</td>
                                  <td className="py-2 text-right">
                                    <span className="px-2 py-0.5 rounded text-sm font-medium bg-emerald-50 text-emerald-600">
                                      {item.solution}
                                    </span>
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </>
              )}

              {/* System Design Content */}
              {activePage === 'system-design' && (
                <>
                  {/* Core Concepts Section - Grouped by Category */}
                  <div className="space-y-3 mb-4">
                    {systemDesignCategories.map((category) => {
                      const categoryTopics = filteredTopics.filter(t => systemDesignCategoryMap[t.id] === category.id);
                      if (categoryTopics.length === 0) return null;
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          {/* Category Header */}
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900">{category.name}</h3>
                              <span className="text-sm text-gray-700">{categoryTopics.length} topics</span>
                            </div>
                          </div>
                          {/* Topics in Category */}
                          <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                            {categoryTopics.map((topic) => (
                              <div
                                key={topic.id}
                                onClick={() => setSelectedTopic(topic.id)}
                                className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group"
                              >
                                <div className="flex items-center gap-3">
                                  <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}15` }}>
                                    {completedTopics[topic.id] ? <Icon name="check" size={12} className="text-emerald-600" /> : <Icon name={topic.icon} size={12} style={{ color: topic.color }} />}
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-sm font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400' : 'text-gray-900'}`}>{topic.title}</span>
                                    {starredTopics[topic.id] && <Icon name="star5" size={10} className="text-yellow-500" />}
                                    <span className="text-gray-600 text-sm ml-2 hidden md:inline">{topic.description}</span>
                                  </div>
                                </div>
                                <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                                  {topic.keyQuestions?.length || topic.questions || 0}Q
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* System Design Problems Section - Grouped by Category */}
                  <div className="space-y-3 mb-4">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-purple-50">
                        <Icon name="systemDesign" size={16} className="text-emerald-600" />
                      </div>
                      <div>
                        <h2 className="text-sm font-bold text-gray-900">Common System Designs</h2>
                        <p className="text-sm text-gray-700">Real-world systems frequently asked in interviews</p>
                      </div>
                    </div>
                    {systemDesignProblemCategories.map((category) => {
                      const categoryDesigns = systemDesigns.filter(d => systemDesignProblemCategoryMap[d.id] === category.id);
                      if (categoryDesigns.length === 0) return null;
                      const difficultyColors = {
                        'Easy': { bg: 'rgba(16,185,129,0.15)', text: '#10b981' },
                        'Medium': { bg: 'rgba(234,179,8,0.15)', text: '#eab308' },
                        'Hard': { bg: 'rgba(239,68,68,0.15)', text: '#ef4444' }
                      };
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          {/* Category Header */}
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900">{category.name}</h3>
                              <span className="text-sm text-gray-700">{categoryDesigns.length} systems</span>
                            </div>
                          </div>
                          {/* Designs in Category */}
                          <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                            {categoryDesigns.map((design) => {
                              const diffColor = difficultyColors[design.difficulty] || difficultyColors['Medium'];
                              const designProblem = `Design ${design.title}. ${design.description || design.subtitle || ''}`;
                              return (
                                <div
                                  key={design.id}
                                  className="px-5 py-4 flex items-center justify-between hover:bg-gray-50 transition-colors group"
                                >
                                  <div
                                    onClick={() => setSelectedTopic(design.id)}
                                    className="flex items-center gap-4 flex-1 cursor-pointer"
                                  >
                                    <div className="w-10 h-10 rounded-lg flex items-center justify-center flex-shrink-0" style={{ background: `${design.color}15` }}>
                                      <Icon name={design.icon} size={20} style={{ color: design.color }} />
                                    </div>
                                    <div>
                                      <span className="text-gray-900 text-base font-semibold group-hover:text-emerald-600 transition-colors">{design.title}</span>
                                      {design.isNew && <span className="px-1.5 py-0.5 rounded text-xs font-bold bg-violet-500/20 text-violet-400 border border-violet-500/30 ml-2">NEW</span>}
                                      <span className="text-gray-500 text-lg ml-3 hidden md:inline">{design.subtitle}</span>
                                    </div>
                                  </div>
                                  <div className="flex items-center gap-3">
                                    <span className="px-3 py-1 rounded-lg text-lg font-medium" style={{ background: diffColor.bg, color: diffColor.text }}>
                                      {design.difficulty}
                                    </span>
                                    <a
                                      href={`/app?problem=${encodeURIComponent(designProblem)}&mode=system-design&autosolve=true`}
                                      className="px-4 py-2 rounded-lg text-lg font-medium bg-emerald-500/15 text-emerald-600 hover:bg-emerald-500/25 transition-colors flex items-center gap-2"
                                      onClick={(e) => e.stopPropagation()}
                                    >
                                      <Icon name="zap" size={16} />
                                      Design
                                    </a>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Low-Level Design Problems Section */}
                  <div className="space-y-3 mb-4">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-teal-500/10">
                        <Icon name="code" size={16} className="text-teal-400" />
                      </div>
                      <div>
                        <h2 className="text-sm font-bold text-gray-900">Low-Level Design (LLD)</h2>
                        <p className="text-sm text-gray-700">Object-oriented design problems with class diagrams and implementations</p>
                      </div>
                    </div>
                    {lldProblemCategories.map((category) => {
                      const categoryProblems = lldProblems.filter(p => lldProblemCategoryMap[p.id] === category.id);
                      if (categoryProblems.length === 0) return null;
                      const difficultyColors = {
                        'Easy': { bg: 'rgba(16,185,129,0.15)', text: '#10b981' },
                        'Medium': { bg: 'rgba(234,179,8,0.15)', text: '#eab308' },
                        'Hard': { bg: 'rgba(239,68,68,0.15)', text: '#ef4444' }
                      };
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900">{category.name}</h3>
                              <span className="text-sm text-gray-700">{categoryProblems.length} problems</span>
                            </div>
                          </div>
                          <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                            {categoryProblems.map((problem) => {
                              const diffColor = difficultyColors[problem.difficulty] || difficultyColors['Medium'];
                              return (
                                <div
                                  key={problem.id}
                                  onClick={() => setSelectedTopic(problem.id)}
                                  className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group"
                                >
                                  <div className="flex items-center gap-3">
                                    <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: `${problem.color}15` }}>
                                      <Icon name={problem.icon} size={12} style={{ color: problem.color }} />
                                    </div>
                                    <div>
                                      <span className="text-gray-900 text-sm font-medium group-hover:text-emerald-600 transition-colors">{problem.title}</span>
                                      {problem.isNew && <span className="px-1 py-0.5 rounded text-xs font-bold bg-violet-500/20 text-violet-400 border border-violet-500/30 ml-1">NEW</span>}
                                      <span className="text-gray-600 text-sm ml-2 hidden md:inline">{problem.subtitle}</span>
                                    </div>
                                  </div>
                                  <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: diffColor.bg, color: diffColor.text }}>
                                    {problem.difficulty}
                                  </span>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Concurrency Section */}
                  <div className="space-y-3 mb-4">
                    <div className="flex items-center gap-3">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-orange-500/10">
                        <Icon name="cpu" size={16} className="text-orange-400" />
                      </div>
                      <div>
                        <h2 className="text-sm font-bold text-gray-900">Concurrency & Multithreading</h2>
                        <p className="text-sm text-gray-700">Thread-safe programming, synchronization, and classic problems</p>
                      </div>
                    </div>
                    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                      <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                        {concurrencyTopics.map((topic) => (
                          <div
                            key={topic.id}
                            onClick={() => setSelectedTopic(topic.id)}
                            className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group"
                          >
                            <div className="flex items-center gap-3">
                              <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: `${topic.color}15` }}>
                                <Icon name={topic.icon} size={12} style={{ color: topic.color }} />
                              </div>
                              <div>
                                <span className="text-gray-900 text-sm font-medium group-hover:text-emerald-600 transition-colors">{topic.title}</span>
                                <span className="text-gray-600 text-sm ml-2 hidden md:inline">{topic.description}</span>
                              </div>
                            </div>
                            <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                              {topic.concepts?.length || topic.primitives?.length || topic.problems?.length || 0} items
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Interview Framework - Compact */}
                  <div className="rounded-xl overflow-hidden" style={{ background: 'linear-gradient(135deg, rgba(59, 130, 246, 0.08), rgba(59, 130, 246, 0.02))', border: '1px solid rgba(59, 130, 246, 0.2)' }}>
                    <div className="px-4 py-3 border-b border-blue-500/20 flex items-center gap-3" style={{ background: 'rgba(59,130,246,0.05)' }}>
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-emerald-500/15">
                        <Icon name="target" size={14} className="text-emerald-600" />
                      </div>
                      <div>
                        <h3 className="text-sm font-bold text-gray-900">Interview Framework</h3>
                        <p className="text-gray-500 text-sm">45-minute breakdown</p>
                      </div>
                    </div>
                    <div className="p-3">
                      <div className="grid grid-cols-4 gap-2">
                        {[
                          { time: '5m', step: 'Requirements', desc: 'Functional & non-functional', icon: 'list', color: '#10b981' },
                          { time: '5m', step: 'Estimations', desc: 'QPS, storage, bandwidth', icon: 'calculator', color: '#eab308' },
                          { time: '20m', step: 'High-Level', desc: 'Components, data flow', icon: 'systemDesign', color: '#3b82f6' },
                          { time: '15m', step: 'Deep Dive', desc: 'Schema, scaling', icon: 'database', color: '#a855f7' },
                        ].map((phase, i) => (
                          <div key={i} className="rounded-lg p-3" style={{ background: '#f5f5f5' }}>
                            <div className="flex items-center gap-2 mb-2">
                              <div className="w-6 h-6 rounded flex items-center justify-center" style={{ background: `${phase.color}20` }}>
                                <Icon name={phase.icon} size={12} style={{ color: phase.color }} />
                              </div>
                              <span className="px-1.5 py-0.5 rounded text-sm font-bold" style={{ background: phase.color, color: '#0a0a0f' }}>
                                {phase.time}
                              </span>
                            </div>
                            <div className="text-gray-900 font-semibold text-sm mb-1">{phase.step}</div>
                            <div className="text-gray-500 text-sm">{phase.desc}</div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </>
              )}

              {/* Behavioral Content */}
              {activePage === 'behavioral' && (
                <>
                  {/* STAR Method - Enhanced */}
                  <div className="rounded-lg overflow-hidden mb-4" style={{ background: 'linear-gradient(135deg, rgba(168, 85, 247, 0.1), rgba(168, 85, 247, 0.02))', border: '1px solid rgba(168, 85, 247, 0.2)' }}>
                    <div className="px-6 py-4 border-b border-purple-500/20" style={{ background: 'rgba(168,85,247,0.05)' }}>
                      <h3 className="text-sm font-bold text-gray-900 flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl flex items-center justify-center bg-emerald-500/15">
                          <Icon name="star" size={20} className="text-emerald-600" />
                        </div>
                        The STAR Method
                      </h3>
                      <p className="text-gray-400 text-sm mt-1 ml-13">The proven framework for behavioral interview answers</p>
                    </div>
                    <div className="p-6">
                      <div className="grid md:grid-cols-4 gap-4">
                        {[
                          { letter: 'S', title: 'Situation', desc: 'Set the scene and give context for your story', color: '#ef4444', tip: 'Be specific about when and where' },
                          { letter: 'T', title: 'Task', desc: 'Describe your responsibility or challenge', color: '#f59e0b', tip: 'Focus on YOUR role' },
                          { letter: 'A', title: 'Action', desc: 'Explain the specific steps you took', color: '#22c55e', tip: 'Use "I" not "we"' },
                          { letter: 'R', title: 'Result', desc: 'Share the outcomes and what you learned', color: '#3b82f6', tip: 'Quantify when possible' },
                        ].map((step, i) => (
                          <div key={i} className="relative rounded-xl p-5" style={{ background: '#f5f5f5' }}>
                            <div
                              className="w-14 h-14 rounded-xl flex items-center justify-center mb-4 text-sm font-bold transition-transform hover:scale-110"
                              style={{ background: `${step.color}20`, color: step.color }}
                            >
                              {step.letter}
                            </div>
                            <div className="text-gray-900 font-semibold text-base mb-2">{step.title}</div>
                            <div className="text-gray-400 text-sm mb-3">{step.desc}</div>
                            <div className="flex items-center gap-2 text-sm" style={{ color: step.color }}>
                              <Icon name="lightbulb" size={12} />
                              <span>{step.tip}</span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Question Categories Section - Grouped by Category */}
                  <div className="space-y-3 mb-4">
                    {behavioralCategories.map((category) => {
                      const categoryTopics = filteredTopics.filter(t => topicCategoryMap[t.id] === category.id);
                      if (categoryTopics.length === 0) return null;
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          {/* Category Header */}
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900">{category.name}</h3>
                              <span className="text-sm text-gray-700">{categoryTopics.length} topics</span>
                            </div>
                          </div>
                          {/* Topics in Category */}
                          <div className="divide-y" style={{ borderColor: '#f0f0f0' }}>
                            {categoryTopics.map((topic) => (
                              <div
                                key={topic.id}
                                onClick={() => setSelectedTopic(topic.id)}
                                className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group"
                              >
                                <div className="flex items-center gap-3">
                                  <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}15` }}>
                                    {completedTopics[topic.id] ? <Icon name="check" size={12} className="text-emerald-600" /> : <Icon name={topic.icon} size={12} style={{ color: topic.color }} />}
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-sm font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400' : 'text-gray-900'}`}>{topic.title}</span>
                                    {starredTopics[topic.id] && <Icon name="star5" size={10} className="text-yellow-500" />}
                                    <span className="text-gray-600 text-sm ml-2 hidden md:inline">{topic.description}</span>
                                  </div>
                                </div>
                                <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                                  {topic.keyQuestions?.length || topic.sampleQuestions?.length || 0}Q
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Company-Specific Section */}
                  <div className="mb-6">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-amber-500/10">
                        <Icon name="briefcase" size={16} className="text-amber-400" />
                      </div>
                      <div>
                        <h2 className="text-sm font-bold text-gray-900">Company-Specific Prep</h2>
                        <p className="text-sm text-gray-700">Tailored guidance for top tech companies</p>
                      </div>
                    </div>
                    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                      <table className="w-full">
                        <thead>
                          <tr style={{ background: '#f8fafc' }}>
                            <th className="text-left text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3">Company</th>
                            <th className="text-left text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3 hidden md:table-cell">Focus Areas</th>
                            <th className="text-right text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3 w-24">Topics</th>
                          </tr>
                        </thead>
                        <tbody>
                          {companyPrep.map((company) => (
                            <tr
                              key={company.id}
                              onClick={() => setSelectedTopic(company.id)}
                              className="group cursor-pointer transition-all hover:bg-gray-50"
                              style={{ borderTop: '1px solid rgba(255,255,255,0.05)' }}
                            >
                              <td className="px-4 py-3">
                                <div className="flex items-center gap-3">
                                  <div
                                    className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                                    style={{ background: `${company.color}15` }}
                                  >
                                    <Icon name={company.icon} size={16} style={{ color: company.color }} />
                                  </div>
                                  <span className="text-gray-900 font-medium group-hover:text-emerald-600 transition-colors">{company.title}</span>
                                </div>
                              </td>
                              <td className="px-4 py-3 hidden md:table-cell">
                                <span className="text-gray-400 text-sm">{company.subtitle}</span>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <span className="px-2 py-1 rounded text-sm font-medium" style={{ background: `${company.color}15`, color: company.color }}>
                                  {company.keyQuestions?.length || 0}
                                </span>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </>
              )}
            </>
          )}
        </div>
          </div>

          {/* Right Sidebar - Table of Contents (only shown on topic detail) */}
          {selectedTopic && topicDetails && tableOfContents.length > 0 && (
            <div className="w-64 flex-shrink-0 hidden xl:block">
              <div className="sticky top-24 p-6">
                <div className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">On this page</div>
                <nav className="space-y-1">
                  {tableOfContents.map((item) => (
                    <a
                      key={item.id}
                      href={`#${item.id}`}
                      className="block px-3 py-2 text-sm text-gray-700 hover:text-gray-900 hover:bg-gray-50 rounded-lg transition-colors"
                    >
                      {item.label}
                    </a>
                  ))}
                </nav>

                {/* Quick Actions */}
                <div className="mt-8 pt-6 border-t border-white/10">
                  <div className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">Quick Actions</div>
                  <div className="space-y-2">
                    <a
                      href="/app"
                      className="flex items-center gap-2 px-3 py-2 text-sm text-emerald-600 hover:bg-emerald-400/10 rounded-lg transition-colors"
                    >
                      <Icon name="play" size={14} />
                      <span>Practice Now</span>
                    </a>
                    <button
                      onClick={() => setSelectedTopic(null)}
                      className="flex items-center gap-2 px-3 py-2 text-sm text-gray-400 hover:bg-gray-50 rounded-lg transition-colors w-full text-left"
                    >
                      <Icon name="list" size={14} />
                      <span>All Topics</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* ── Right Sidebar — Progress & TOC (visible when topic selected) ── */}
        {selectedTopic && topicDetails && (
          <div className="w-64 flex-shrink-0 h-screen sticky top-0 hidden xl:flex flex-col py-6 px-4 overflow-y-auto" style={{ borderLeft: '1px solid #e2e8f0', background: '#f8fafc' }}>
            {/* Progress Ring */}
            <div className="text-center mb-6">
              <div className="relative w-20 h-20 mx-auto mb-3">
                <svg className="w-20 h-20 -rotate-90" viewBox="0 0 80 80">
                  <circle cx="40" cy="40" r="35" fill="none" stroke="rgba(255,255,255,0.06)" strokeWidth="6" />
                  <circle cx="40" cy="40" r="35" fill="none" stroke="#10b981" strokeWidth="6" strokeLinecap="round"
                    strokeDasharray={`${2 * Math.PI * 35}`}
                    strokeDashoffset={`${2 * Math.PI * 35 * (1 - getProgress().percent / 100)}`}
                    style={{ transition: 'stroke-dashoffset 0.5s ease' }}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="text-sm font-bold text-gray-900">{getProgress().percent}%</span>
                </div>
              </div>
              <div className="text-sm text-gray-600">{getProgress().completed}/{getProgress().total} topics</div>
              <div className="text-xs text-gray-600 mt-1">{pageConfig.title}</div>
            </div>

            {/* Quick Actions */}
            <div className="space-y-1.5 mb-6">
              <button
                onClick={() => toggleComplete(selectedTopic)}
                className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium transition-all ${completedTopics[selectedTopic] ? 'bg-emerald-500/15 text-emerald-600' : 'text-gray-700 hover:text-gray-900 hover:bg-gray-50'}`}
              >
                <Icon name={completedTopics[selectedTopic] ? 'checkCircle' : 'check'} size={14} />
                {completedTopics[selectedTopic] ? 'Completed' : 'Mark Complete'}
              </button>
              <button
                onClick={() => toggleStar(selectedTopic)}
                className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium transition-all ${starredTopics[selectedTopic] ? 'text-yellow-500 bg-yellow-400/10' : 'text-gray-700 hover:text-gray-900 hover:bg-gray-50'}`}
              >
                <Icon name={starredTopics[selectedTopic] ? 'star5' : 'star'} size={14} />
                {starredTopics[selectedTopic] ? 'Starred' : 'Add to Favorites'}
              </button>
              <button
                onClick={() => setShowAskAI(!showAskAI)}
                className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium text-gray-400 hover:text-purple-400 hover:bg-purple-400/10 transition-all"
              >
                <Icon name="sparkles" size={14} />
                Ask AI
              </button>
            </div>

            {/* Table of Contents */}
            {tableOfContents.length > 0 && (
              <div>
                <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">On This Page</div>
                <div className="space-y-0.5">
                  {tableOfContents.map((item, i) => (
                    <a
                      key={i}
                      href={`#${item.id}`}
                      className="block px-3 py-1.5 rounded text-xs text-gray-700 hover:text-gray-900 hover:bg-gray-50 transition-all truncate"
                    >
                      {item.label}
                    </a>
                  ))}
                </div>
              </div>
            )}

            {/* Starred Topics */}
            {Object.keys(starredTopics).filter(k => starredTopics[k]).length > 0 && (
              <div className="mt-6 pt-6" style={{ borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                <div className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-3">Favorites</div>
                <div className="space-y-1">
                  {Object.keys(starredTopics).filter(k => starredTopics[k]).map((topicId) => {
                    const t = [...codingTopics, ...systemDesignTopics, ...systemDesigns, ...behavioralTopics].find(x => x.id === topicId);
                    if (!t) return null;
                    return (
                      <button
                        key={topicId}
                        onClick={() => setSelectedTopic(topicId)}
                        className="w-full flex items-center gap-2 px-3 py-1.5 rounded text-xs text-left text-gray-700 hover:text-gray-900 hover:bg-gray-50 transition-all"
                      >
                        <Icon name="star5" size={10} className="text-yellow-500 flex-shrink-0" />
                        <span className="truncate">{t.title}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <style>{`
        .animate-fade-in {
          animation: fadeIn 0.3s ease-out;
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .line-clamp-2 {
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }
        .formatted-content pre {
          font-family: "SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, "Courier New", monospace !important;
          white-space: pre !important;
          tab-size: 4 !important;
          -moz-tab-size: 4 !important;
          line-height: 1.4 !important;
          letter-spacing: 0 !important;
        }
        /* Smooth scrolling for anchor links */
        html {
          scroll-behavior: smooth;
        }
        /* Custom scrollbar */
        ::-webkit-scrollbar {
          width: 8px;
          height: 8px;
        }
        ::-webkit-scrollbar-track {
          background: rgba(255,255,255,0.02);
        }
        ::-webkit-scrollbar-thumb {
          background: rgba(255,255,255,0.1);
          border-radius: 4px;
        }
        ::-webkit-scrollbar-thumb:hover {
          background: rgba(255,255,255,0.2);
        }
        /* Card hover effects */
        .group:hover .hover-glow {
          opacity: 1;
        }
      `}</style>
    </div>
  );
}
