import { useState, useEffect } from 'react';
import { useIsMobile } from '../hooks/useIsMobile';
import { Icon } from './Icons.jsx';
import { getAuthHeaders } from '../utils/authHeaders.js';
import DiagramSVG from './DiagramSVG.jsx';
import { generateSlug, getProblemBySlug } from '../data/problems.js';
import { getLeetCodeUrl } from '../data/leetcodeUrls.js';
import problemsFull from '../data/problems-full.json';
import { codingCategories, codingCategoryMap, codingTopics } from '../data/topics/codingTopics.js';
import { systemDesignCategories, systemDesignCategoryMap, systemDesignTopics } from '../data/topics/systemDesignTopics.js';
import { systemDesignProblemCategories, systemDesignProblemCategoryMap, systemDesigns, lldProblemCategories, lldProblemCategoryMap } from '../data/topics/systemDesignProblems.js';
import { lldProblems } from '../data/topics/lldProblems.js';
import { concurrencyTopics } from '../data/topics/concurrencyTopics.js';
import { behavioralCategories, topicCategoryMap, behavioralTopics } from '../data/topics/behavioralTopics.js';
import { companyPrep } from '../data/topics/companyPrep.js';

// Unified card styling - clean, minimal design with larger fonts
import CloudArchitectureDiagram from './docs/CloudArchitectureDiagram.jsx';
import FormattedContent from './docs/FormattedContent.jsx';
import TopicDetail from './docs/TopicDetail.jsx';
const CARD_STYLES = {
  // Standard card with subtle border
  card: {
    background: '#ffffff',
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
  },
  // Card header - uses Ascend emerald accent
  header: {
    background: '#f0fdf4',
    borderBottom: '1px solid #d1fae5',
    padding: '8px 12px',
  },
  // Card body
  body: {
    padding: '24px',
  },
  // Code block
  code: {
    background: '#0d1117',
    border: '1px solid #e2e8f0',
    borderRadius: '10px',
  },
};

// Font size scale - increased for better readability
const FONT_SIZES = {
  xs: '14px',
  sm: '16px',
  base: '18px',
  lg: '20px',
  xl: '24px',
  '2xl': '28px',
  '3xl': '32px',
};

// Ascend brand colors - emerald green
const ASCEND_COLORS = {
  primary: '#10b981',
  primaryHover: '#059669',
  primaryLight: 'rgba(16, 185, 129, 0.15)',
  primaryBorder: 'rgba(16, 185, 129, 0.25)',
  gradient: '#10b981',
};

// Get API URL based on environment (Electron vs Web)
const getApiUrl = () => {
  if (window.electronAPI?.isElectron) {
    return 'http://127.0.0.1:3001';
  }
  return import.meta.env.VITE_API_URL || '';
};

/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */

/**
 * Documentation Page with Sidebar Navigation and Topic Details
 * Original educational content for interview preparation
 */
export default function DocsPage({ onBack }) {
  const { isMobile } = useIsMobile();
  const [docsSidebarOpen, setDocsSidebarOpen] = useState(false);
  const isElectron = window.electronAPI?.isElectron || false;
  // Initialize state from URL params for persistence on refresh
  const getInitialState = () => {
    const params = new URLSearchParams(window.location.search);
    // Support both query param (?page=...) and path segment (/prepare/system-design)
    const pathSegment = window.location.pathname.replace('/prepare', '').replace(/^\//, '');
    const rawPage = params.get('page') || (pathSegment || 'coding');
    // Support 'dsa' as alias for 'coding'
    const page = rawPage === 'dsa' ? 'coding' : rawPage === 'low-level-design' ? 'low-level' : rawPage;
    return {
      page,
      topic: params.get('topic') || null,
    };
  };

  const initialState = getInitialState();
  const [activePage, setActivePageState] = useState(initialState.page);
  const [searchQuery, setSearchQuery] = useState('');
  const [sortOrder, setSortOrder] = useState('a-z');
  const [selectedTopic, setSelectedTopicState] = useState(initialState.topic);

  // Sync URL with state via useEffect (avoids stale closure issues)
  useEffect(() => {
    const params = new URLSearchParams();
    if (activePage && activePage !== 'coding') params.set('page', activePage);
    if (selectedTopic) params.set('topic', selectedTopic);
    const queryString = params.toString();
    const newURL = queryString ? `/prepare?${queryString}` : '/prepare';
    window.history.replaceState({}, '', newURL);
  }, [activePage, selectedTopic]);

  // Wrapped setters
  const setActivePage = (page) => {
    setActivePageState(page);
    setSelectedTopicState(null);
  };

  const setSelectedTopic = (topic) => {
    setSelectedTopicState(topic);
    if (topic) {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  // Diagram generation state
  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [diagramData, setDiagramData] = useState(null);
  const [diagramError, setDiagramError] = useState(null);
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  const [diagramCloudProvider, setDiagramCloudProvider] = useState('aws');
  const [diagramCache, setDiagramCache] = useState({}); // Cache diagrams by topic+level+provider

  // Theory questions expanded state
  const [expandedTheoryQuestions, setExpandedTheoryQuestions] = useState({});

  // ── Interactive features (AlgoMaster-inspired) ──
  const [completedTopics, setCompletedTopics] = useState(() => {
    try { return JSON.parse(localStorage.getItem('ascend_completed_topics') || '{}'); } catch { return {}; }
  });
  const [starredTopics, setStarredTopics] = useState(() => {
    try { return JSON.parse(localStorage.getItem('ascend_starred_topics') || '{}'); } catch { return {}; }
  });
  const [showAskAI, setShowAskAI] = useState(false);
  const [aiQuestion, setAiQuestion] = useState('');
  const [aiAnswer, setAiAnswer] = useState('');
  const [aiLoading, setAiLoading] = useState(false);
  const [showRoadmap, setShowRoadmap] = useState(false);

  const toggleComplete = (topicId) => {
    setCompletedTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      localStorage.setItem('ascend_completed_topics', JSON.stringify(next));
      return next;
    });
  };

  const toggleStar = (topicId) => {
    setStarredTopics(prev => {
      const next = { ...prev, [topicId]: !prev[topicId] };
      localStorage.setItem('ascend_starred_topics', JSON.stringify(next));
      return next;
    });
  };

  const handleAskAI = async () => {
    if (!aiQuestion.trim()) return;
    setAiLoading(true);
    setAiAnswer('');
    try {
      const res = await fetch(`${API_URL}/api/solve/followup`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', ...getAuthHeaders() },
        body: JSON.stringify({
          question: aiQuestion,
          context: topicDetails ? `Topic: ${topicDetails.title}. ${topicDetails.description || ''} ${topicDetails.introduction || ''}` : '',
          problem: '',
          code: '',
        }),
      });
      const data = await res.json();
      setAiAnswer(data.answer || data.result || 'No answer available.');
    } catch (err) {
      setAiAnswer('Failed to get AI response. Please try again.');
    } finally {
      setAiLoading(false);
    }
  };

  // Calculate progress
  const getProgress = () => {
    const topics = activePage === 'coding' ? codingTopics :
      activePage === 'system-design' ? [...systemDesignTopics, ...systemDesigns, ...lldProblems, ...concurrencyTopics] :
      [...behavioralTopics, ...companyPrep];
    const total = topics.length;
    const completed = topics.filter(t => completedTopics[t.id]).length;
    return { total, completed, percent: total > 0 ? Math.round((completed / total) * 100) : 0 };
  };

  // Reset diagram when topic changes
  useEffect(() => {
    setDiagramData(null);
    setDiagramError(null);
    // Check cache for existing diagram
    const cacheKey = `${selectedTopic}-${diagramDetailLevel}-${diagramCloudProvider}`;
    if (selectedTopic && diagramCache[cacheKey]) {
      setDiagramData(diagramCache[cacheKey]);
    }
  }, [selectedTopic]);

  // Generate architecture diagram
  const handleGenerateDiagram = async (topicTitle, detailLevel = 'overview', provider = diagramCloudProvider) => {
    if (!topicTitle) return;

    // Check cache first
    const cacheKey = `${selectedTopic}-${detailLevel}-${provider}`;
    if (diagramCache[cacheKey]) {
      setDiagramData(diagramCache[cacheKey]);
      setDiagramDetailLevel(detailLevel);
      setDiagramCloudProvider(provider);
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramDetailLevel(detailLevel);
    setDiagramCloudProvider(provider);

    try {
      const API_URL = getApiUrl();
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question: `Design ${topicTitle}`,
          cloudProvider: provider,
          difficulty: 'medium',
          category: 'System Design',
          format: 'png',
          detailLevel: detailLevel
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch {
          // Response wasn't JSON
        }
        throw new Error(errorMessage);
      }

      const data = await response.json();
      if (data.success && data.image_url) {
        // Construct full URL
        const fullImageUrl = data.image_url.startsWith('http')
          ? data.image_url
          : `${API_URL}${data.image_url}`;

        const result = { ...data, imageUrl: fullImageUrl };
        setDiagramData(result);
        // Cache the result
        setDiagramCache(prev => ({ ...prev, [cacheKey]: result }));
      } else {
        throw new Error(data.error || 'Diagram generation failed');
      }
    } catch (err) {
      console.error('Diagram generation error:', err);
      setDiagramError(err.message);
    } finally {
      setGeneratingDiagram(false);
    }
  };

  // Sidebar navigation items
  const navItems = [
    { id: 'coding', label: 'Data Structures & Algorithms', icon: 'code' },
    { id: 'system-design', label: 'System Design', icon: 'systemDesign' },
    { id: 'behavioral', label: 'Behavioral', icon: 'users' },
  ];

  // Coding topic categories
  // Filter and sort topics based on active page
  const getFilteredTopics = () => {
    let topics = [];
    if (activePage === 'coding') topics = codingTopics;
    else if (activePage === 'system-design') topics = systemDesignTopics;
    else if (activePage === 'behavioral') topics = behavioralTopics;
    else return [];

    return topics
      .filter(topic => topic.title.toLowerCase().includes(searchQuery.toLowerCase()))
      .sort((a, b) => {
        if (sortOrder === 'a-z') return a.title.localeCompare(b.title);
        if (sortOrder === 'z-a') return b.title.localeCompare(a.title);
        if (sortOrder === 'most') return b.questions - a.questions;
        if (sortOrder === 'least') return a.questions - b.questions;
        return 0;
      });
  };

  const filteredTopics = getFilteredTopics();

  // Get page title and color
  const getPageConfig = () => {
    switch (activePage) {
      case 'coding': return { title: 'Data Structures & Algorithms', color: '#10b981' };
      case 'system-design': return { title: 'System Design', color: '#3b82f6' };
      case 'behavioral': return { title: 'Behavioral Interviews', color: '#a855f7' };
      default: return { title: 'Documentation', color: '#10b981' };
    }
  };

  const pageConfig = getPageConfig();

  // Find selected topic details
  const getSelectedTopicDetails = () => {
    if (!selectedTopic) return null;
    if (activePage === 'coding') return codingTopics.find(t => t.id === selectedTopic);
    if (activePage === 'system-design') {
      return systemDesignTopics.find(t => t.id === selectedTopic) ||
             systemDesigns.find(t => t.id === selectedTopic) ||
             lldProblems.find(t => t.id === selectedTopic) ||
             concurrencyTopics.find(t => t.id === selectedTopic);
    }
    if (activePage === 'behavioral') {
      return behavioralTopics.find(t => t.id === selectedTopic) ||
             companyPrep.find(t => t.id === selectedTopic);
    }
    return null;
  };

  const topicDetails = getSelectedTopicDetails();

  // Render topic detail view

  // Generate table of contents for topic detail view
  const getTableOfContents = () => {
    if (!topicDetails) return [];
    const toc = [];

    if (activePage === 'coding') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.whenToUse) toc.push({ id: 'when-to-use', label: 'When to Use' });
      if (topicDetails.approach) toc.push({ id: 'approach', label: 'Approach' });
      if (topicDetails.codeExamples) toc.push({ id: 'code-examples', label: 'Code Examples' });
      if (topicDetails.commonProblems) toc.push({ id: 'practice', label: 'Practice Problems' });
      if (topicDetails.tips) toc.push({ id: 'tips', label: 'Interview Tips' });
    } else if (activePage === 'system-design') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.requirements) toc.push({ id: 'requirements', label: 'Requirements' });
      if (topicDetails.keyQuestions) toc.push({ id: 'key-questions', label: 'Key Questions' });
      if (topicDetails.estimation) toc.push({ id: 'estimation', label: 'Estimation' });
      if (topicDetails.apiDesign) toc.push({ id: 'api-design', label: 'API Design' });
      if (topicDetails.dataModel) toc.push({ id: 'data-model', label: 'Data Model' });
      if (topicDetails.basicImplementation) toc.push({ id: 'architecture', label: 'Architecture' });
    } else if (activePage === 'behavioral') {
      if (topicDetails.introduction) toc.push({ id: 'overview', label: 'Overview' });
      if (topicDetails.keyQuestions) toc.push({ id: 'key-questions', label: 'Key Questions' });
      if (topicDetails.starExample) toc.push({ id: 'star-example', label: 'STAR Example' });
      if (topicDetails.sampleQuestions) toc.push({ id: 'sample-questions', label: 'Sample Questions' });
      if (topicDetails.tips) toc.push({ id: 'tips', label: 'Tips' });
    }
    return toc;
  };

  const tableOfContents = getTableOfContents();

  return (
    <div className="min-h-screen landing-root bg-white text-gray-900">
      {/* Electron drag region */}
      {isElectron && (
        <div
          className="fixed top-0 left-0 right-0 h-8 z-50"
          style={{ WebkitAppRegion: 'drag' }}
        />
      )}

      {/* Subtle dot pattern background */}
      <div
        className="fixed inset-0 pointer-events-none opacity-20"
        style={{
          backgroundImage: 'radial-gradient(circle, #d1d5db 0.5px, transparent 0.5px)',
          backgroundSize: '24px 24px'
        }}
      />

      <div className="relative flex">
        {/* Mobile sidebar overlay */}
        {isMobile && docsSidebarOpen && (
          <div className="fixed inset-0 z-40 bg-black/50" onClick={() => setDocsSidebarOpen(false)} />
        )}

        {/* Left Sidebar - Navigation */}
        <div className={`${isMobile ? 'fixed inset-y-0 left-0 z-50 w-72 max-w-[80vw] transition-transform duration-300' : 'w-72 flex-shrink-0 h-screen sticky top-0'} flex flex-col bg-white border-r border-gray-100 ${isMobile && !docsSidebarOpen ? '-translate-x-full' : 'translate-x-0'}`}>
          {/* Logo */}
          <div className="p-6">
            <a href="/" className="flex items-center gap-3 group">
              <div className="w-8 h-8 bg-emerald-500 flex items-center justify-center transition-transform group-hover:scale-105">
                <Icon name="ascend" size={16} className="text-white" />
              </div>
              <div>
                <span className="landing-display font-bold text-lg tracking-tight text-gray-900">Ascend</span>
                <span className="block text-[10px] landing-mono uppercase tracking-[0.2em] text-emerald-600 -mt-0.5">Interview AI</span>
              </div>
            </a>
          </div>

          {/* Category Navigation */}
          <nav className="flex-1 px-4 py-2 overflow-y-auto">
            <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase px-3 mb-3">Learning Tracks</div>
            {navItems.map((item) => {
              const isActive = activePage === item.id;
              return (
                <button
                  key={item.id}
                  onClick={() => { setActivePage(item.id); if (isMobile) setDocsSidebarOpen(false); }}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-sm transition-all mb-1 landing-body ${
                    isActive ? 'text-emerald-700 font-semibold bg-emerald-50' : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50 font-medium'
                  }`}
                >
                  <Icon name={item.icon} size={18} className={isActive ? 'text-emerald-500' : 'text-gray-400'} />
                  <div className="flex-1 text-left">
                    <span className="block">{item.label}</span>
                    <span className="text-xs text-gray-400 landing-mono">
                      {item.id === 'coding' ? `${codingTopics.length} topics` :
                       item.id === 'system-design' ? `${systemDesignTopics.length + systemDesigns.length + lldProblems.length + concurrencyTopics.length} topics` :
                       `${behavioralTopics.length} topics`}
                    </span>
                  </div>
                  {isActive && <div className="w-1.5 h-1.5 rounded-full bg-emerald-500" />}
                </button>
              );
            })}

            {/* Practice Links */}
            <div className="mx-5 h-px bg-gradient-to-r from-transparent via-emerald-200 to-transparent mt-6 mb-4" />
            <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase px-3 mb-3">Practice</div>
            {[
              { href: '/app/coding', label: 'Coding', icon: 'code', color: '#10b981' },
              { href: '/app/design', label: 'Design', icon: 'systemDesign', color: '#3b82f6' },
              { href: '/app/prep', label: 'Interview Prep', icon: 'briefcase', color: '#a855f7' },
            ].map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="flex items-center gap-3 px-4 py-2.5 rounded-lg text-sm transition-all hover:bg-gray-50 mb-0.5 landing-body font-medium"
                style={{ color: link.color }}
              >
                <Icon name={link.icon} size={16} />
                <span>{link.label}</span>
              </a>
            ))}
          </nav>

          {/* Pro Badge */}
          <div className="mx-4 mb-4">
            <div className="h-px bg-gradient-to-r from-transparent via-emerald-200 to-transparent mb-4" />
            <div className="p-4 rounded-lg border border-emerald-200 bg-emerald-50/50">
              <div className="flex items-center gap-2 mb-2">
                <Icon name="crown" size={14} className="text-emerald-600" />
                <span className="text-sm font-semibold text-gray-900 landing-display">Ascend Pro</span>
              </div>
              <p className="text-xs text-gray-500 mb-3 landing-body">AI-powered practice with real-time feedback</p>
              <a href="/app/coding" className="block text-center py-2 bg-emerald-500 text-white font-semibold text-sm rounded hover:bg-emerald-600 transition-colors landing-body">
                Try Free
              </a>
            </div>
          </div>
        </div>

        {/* Main Content Area + Right Sidebar */}
        <div className="flex-1 min-h-screen flex">
          {/* Center Content */}
          <div className={`flex-1 min-w-0 mx-auto max-w-full ${isMobile ? 'px-3' : 'px-10'}`}>
            {/* Top Bar */}
            <div className="sticky top-0 z-20 px-3 sm:px-4 py-3 sm:py-4 flex items-center justify-between gap-2 safe-top bg-white/90 backdrop-blur-md border-b border-gray-100">
              {/* Mobile hamburger */}
              {isMobile && (
                <button
                  onClick={() => setDocsSidebarOpen(true)}
                  className="flex-shrink-0 w-9 h-9 rounded-lg flex items-center justify-center text-gray-600 hover:bg-gray-100 transition-colors"
                  aria-label="Open navigation"
                >
                  <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M4 6h16M4 12h16M4 18h16" /></svg>
                </button>
              )}
              {/* Breadcrumb */}
              <div className="flex items-center gap-2 text-sm min-w-0 flex-1">
                {isElectron && onBack && (
                  <button
                    onClick={onBack}
                    className="flex items-center gap-1 text-gray-400 hover:text-gray-900 transition-colors mr-2 landing-body"
                  >
                    <Icon name="arrowLeft" size={16} />
                    <span>Back</span>
                  </button>
                )}
                <button onClick={() => setSelectedTopic(null)} className="text-gray-400 hover:text-gray-900 transition-colors cursor-pointer landing-body font-medium">Learn</button>
                <Icon name="chevronRight" size={14} className="text-gray-300" />
                {selectedTopic && topicDetails ? (
                  <>
                    <button onClick={() => setSelectedTopic(null)} className="text-gray-400 hover:text-gray-900 transition-colors cursor-pointer landing-body font-medium">{pageConfig.title}</button>
                    <Icon name="chevronRight" size={14} className="text-gray-300" />
                    <span className="text-gray-900 landing-body font-semibold">{topicDetails.title}</span>
                  </>
                ) : (
                  <span className="text-gray-900 landing-body font-semibold">{pageConfig.title}</span>
                )}
              </div>
              {!selectedTopic && (
                <div className="flex items-center gap-3">
                  <a
                    href="/app"
                    className="px-5 py-2 bg-emerald-500 text-white font-semibold text-sm rounded hover:bg-emerald-600 transition-colors landing-body"
                  >
                    Start Practice
                  </a>
                </div>
              )}
            </div>

            {/* Content */}
            <div className="px-4 py-4">
              {/* Show topic detail or list */}
              {selectedTopic ? <TopicDetail activePage={activePage} selectedTopic={selectedTopic} topicDetails={topicDetails} pageConfig={pageConfig} completedTopics={completedTopics} starredTopics={starredTopics} toggleComplete={toggleComplete} toggleStar={toggleStar} showAskAI={showAskAI} setShowAskAI={setShowAskAI} aiQuestion={aiQuestion} setAiQuestion={setAiQuestion} aiAnswer={aiAnswer} aiLoading={aiLoading} handleAskAI={handleAskAI} showRoadmap={showRoadmap} setShowRoadmap={setShowRoadmap} expandedTheoryQuestions={expandedTheoryQuestions} setExpandedTheoryQuestions={setExpandedTheoryQuestions} setSelectedTopic={setSelectedTopic} generatingDiagram={generatingDiagram} diagramData={diagramData} diagramError={diagramError} diagramDetailLevel={diagramDetailLevel} setDiagramDetailLevel={setDiagramDetailLevel} diagramCloudProvider={diagramCloudProvider} setDiagramCloudProvider={setDiagramCloudProvider} generateDiagram={handleGenerateDiagram} codingTopics={codingTopics} systemDesignTopics={systemDesignTopics} systemDesigns={systemDesigns} behavioralTopics={behavioralTopics} filteredTopics={filteredTopics} /> : (
                <>
                  {/* Page Hero */}
                  <div className="mb-6">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 border border-emerald-200 bg-emerald-50 rounded-full mb-4">
                      <span className="w-2 h-2 bg-emerald-500 rounded-full animate-pulse" />
                      <span className="text-xs landing-mono text-emerald-700 tracking-wide">
                        {activePage === 'coding' ? 'Algorithms' : activePage === 'system-design' ? 'Architecture' : 'Soft Skills'}
                      </span>
                    </div>
                    <h1 className="landing-display font-extrabold text-2xl md:text-3xl tracking-tight text-gray-900 mb-2">
                      {activePage === 'coding' && <>Data Structures &{' '}<span className="bg-gradient-to-r from-emerald-600 to-cyan-600 bg-clip-text text-transparent">Algorithms</span></>}
                      {activePage === 'system-design' && <>Design Systems That{' '}<span className="bg-gradient-to-r from-emerald-600 to-cyan-600 bg-clip-text text-transparent">Scale</span></>}
                      {activePage === 'behavioral' && <>Tell Your{' '}<span className="bg-gradient-to-r from-emerald-600 to-cyan-600 bg-clip-text text-transparent">Best Story</span></>}
                    </h1>
                    <p className="text-sm text-gray-500 max-w-2xl leading-relaxed landing-body">
                      {activePage === 'coding' && 'Master the fundamental data structures and algorithms needed to ace technical interviews at top tech companies.'}
                      {activePage === 'system-design' && 'Master distributed systems, scalability patterns, and architecture trade-offs. From fundamentals to real-world designs at top companies.'}
                      {activePage === 'behavioral' && 'Prepare compelling stories and answers for behavioral interviews using proven frameworks like STAR.'}
                    </p>
                  </div>
                  {/* Gradient Divider */}
                  <div className="h-px bg-gradient-to-r from-transparent via-emerald-300 to-transparent mb-6" />

                  {/* Search and Filters */}
                  <div className="flex flex-col sm:flex-row sm:items-center gap-3 mb-4">
                    <div className="relative flex-1 sm:max-w-md">
                      <Icon name="search" size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
                      <input
                        type="text"
                        placeholder="Search topics..."
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        className="w-full pl-9 pr-4 py-2 rounded-lg text-sm text-gray-900 placeholder-gray-400 border border-gray-200 bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-300 transition-all landing-body"
                      />
                    </div>
                    <div className="flex items-center gap-3">
                      <select
                        value={sortOrder}
                        onChange={(e) => setSortOrder(e.target.value)}
                        className="px-4 py-2 rounded-lg text-sm text-gray-500 border border-gray-200 bg-white focus:outline-none focus:ring-2 focus:ring-emerald-500/20 focus:border-emerald-300 cursor-pointer landing-body"
                      >
                        <option value="a-z">A - Z</option>
                        <option value="z-a">Z - A</option>
                        <option value="most">Most Questions</option>
                        <option value="least">Least Questions</option>
                      </select>
                      <span className="text-xs text-gray-400 landing-mono">
                        {filteredTopics.length} {filteredTopics.length === 1 ? 'topic' : 'topics'}
                      </span>
                    </div>
                  </div>

              {/* DSA Content */}
              {activePage === 'coding' && (
                <>
                  {/* All topics in a flat 2-column grid */}
                  <div className="rounded-xl overflow-hidden mb-4" style={{ border: '1px solid #e2e8f0' }}>
                    <div className="grid grid-cols-1 md:grid-cols-2">
                    {filteredTopics.map((topic, idx) => {
                      const catId = codingCategoryMap[topic.id];
                      const category = codingCategories.find(c => c.id === catId);
                      const isFirstInCategory = idx === 0 || codingCategoryMap[filteredTopics[idx-1]?.id] !== catId;
                      return (
                        <div key={topic.id}>
                          {isFirstInCategory && category && (
                            <div className="col-span-full px-3 py-1.5 flex items-center gap-2 text-xs font-bold text-gray-500 uppercase tracking-wider" style={{ background: '#f8fafc', borderTop: idx > 0 ? '1px solid #e2e8f0' : 'none', borderBottom: '1px solid #f0f0f0' }}>
                              <Icon name={category.icon} size={12} style={{ color: category.color }} />
                              {category.name} · {filteredTopics.filter(t => codingCategoryMap[t.id] === catId).length}
                            </div>
                          )}
                          <div
                            onClick={() => setSelectedTopic(topic.id)}
                            className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group border-b border-r border-gray-100"
                          >
                            <div className="flex items-center gap-2">
                              <div className="w-5 h-5 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}15` }}>
                                {completedTopics[topic.id] ? <Icon name="check" size={10} className="text-emerald-600" /> : <Icon name={topic.icon} size={10} style={{ color: topic.color }} />}
                              </div>
                              <span className={`text-sm font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400' : 'text-gray-900'}`}>{topic.title}</span>
                            </div>
                            <span className="px-1.5 py-0.5 rounded text-xs font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                              {topic.commonProblems?.length || topic.keyQuestions?.length || 0}Q
                            </span>
                          </div>
                        </div>
                      );
                    })}
                    </div>
                  </div>

                  {/* Quick Reference - Enhanced */}
                  <div className="mb-4">
                    <div className="flex items-center gap-3 mb-6">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-emerald-50">
                        <Icon name="book" size={16} className="text-emerald-600" />
                      </div>
                      <h2 className="text-sm font-bold text-gray-900">Quick Reference</h2>
                    </div>
                    <div className="grid md:grid-cols-2 gap-3">
                      {/* Time Complexity Card */}
                      <div className="rounded-xl overflow-hidden" style={CARD_STYLES.card}>
                        <div className="px-4 py-3 border-b border-emerald-200" style={{ background: '#f0fdf4' }}>
                          <h3 className="text-sm text-gray-900 font-semibold flex items-center gap-2">
                            <Icon name="clock" size={16} className="text-emerald-600" />
                            Time Complexity Cheat Sheet
                          </h3>
                        </div>
                        <div className="p-4">
                          <table className="w-full text-sm">
                            <tbody>
                              {[
                                { complexity: 'O(1)', desc: 'Constant', rating: 'Best', color: '#10b981' },
                                { complexity: 'O(log n)', desc: 'Logarithmic', rating: 'Great', color: '#10b981' },
                                { complexity: 'O(n)', desc: 'Linear', rating: 'Good', color: '#eab308' },
                                { complexity: 'O(n log n)', desc: 'Linearithmic', rating: 'Fair', color: '#eab308' },
                                { complexity: 'O(n²)', desc: 'Quadratic', rating: 'Slow', color: '#f97316' },
                                { complexity: 'O(2ⁿ)', desc: 'Exponential', rating: 'Avoid', color: '#ef4444' },
                              ].map((item, i) => (
                                <tr key={i} className="border-b border-gray-100 last:border-0">
                                  <td className="py-2 font-mono text-sm text-emerald-700">{item.complexity}</td>
                                  <td className="py-2 text-gray-900">{item.desc}</td>
                                  <td className="py-2 text-right">
                                    <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${item.color}20`, color: item.color }}>
                                      {item.rating}
                                    </span>
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                      {/* Data Structure Selection Card */}
                      <div className="rounded-xl overflow-hidden" style={CARD_STYLES.card}>
                        <div className="px-4 py-3 border-b border-emerald-200" style={{ background: '#f0fdf4' }}>
                          <h3 className="text-sm text-gray-900 font-semibold flex items-center gap-2">
                            <Icon name="database" size={16} className="text-emerald-600" />
                            When to Use What
                          </h3>
                        </div>
                        <div className="p-4">
                          <table className="w-full text-sm">
                            <tbody>
                              {[
                                { need: 'Fast lookup', solution: 'Hash Map', icon: 'hash' },
                                { need: 'Sorted data', solution: 'BST / TreeMap', icon: 'tree' },
                                { need: 'FIFO operations', solution: 'Queue', icon: 'list' },
                                { need: 'LIFO operations', solution: 'Stack', icon: 'layers' },
                                { need: 'Priority access', solution: 'Heap', icon: 'triangle' },
                                { need: 'Prefix matching', solution: 'Trie', icon: 'search' },
                              ].map((item, i) => (
                                <tr key={i} className="border-b border-gray-100 last:border-0">
                                  <td className="py-2 text-gray-600">{item.need}</td>
                                  <td className="py-2 text-right">
                                    <span className="px-2 py-0.5 rounded text-sm font-medium bg-emerald-50 text-emerald-600">
                                      {item.solution}
                                    </span>
                                  </td>
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    </div>
                  </div>
                </>
              )}

              {/* System Design Content */}
              {activePage === 'system-design' && (
                <>
                  {/* Core Concepts Section - Grouped by Category */}
                  <div className="mb-6">
                    <div className="mb-4">
                      <span className="landing-mono text-xs text-emerald-600 tracking-widest uppercase">Foundations</span>
                      <h2 className="landing-display font-bold text-xl mt-1 tracking-tight text-gray-900">Core Concepts</h2>
                    </div>
                    <div className="space-y-3">
                    {systemDesignCategories.map((category) => {
                      const categoryTopics = filteredTopics.filter(t => systemDesignCategoryMap[t.id] === category.id);
                      if (categoryTopics.length === 0) return null;
                      return (
                        <div key={category.id} className="rounded-lg overflow-hidden border border-gray-200">
                          {/* Category Header */}
                          <div className="px-4 py-2.5 flex items-center gap-2.5 bg-gray-50/80 border-b border-gray-100">
                            <div className="w-7 h-7 rounded flex items-center justify-center" style={{ background: `${category.color}12` }}>
                              <Icon name={category.icon} size={14} style={{ color: category.color }} />
                            </div>
                            <h3 className="text-sm font-semibold text-gray-900 landing-display">{category.name}</h3>
                            <span className="text-[10px] landing-mono text-gray-400">{categoryTopics.length} topics</span>
                          </div>
                          {/* Topics in Category */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 bg-white">
                            {categoryTopics.map((topic) => (
                              <div
                                key={topic.id}
                                onClick={() => setSelectedTopic(topic.id)}
                                className="px-4 py-2.5 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-all group border-b border-r border-gray-100"
                              >
                                <div className="flex items-center gap-2.5">
                                  <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}12` }}>
                                    {completedTopics[topic.id] ? <Icon name="check" size={11} className="text-emerald-600" /> : <Icon name={topic.icon} size={11} style={{ color: topic.color }} />}
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-sm landing-body font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400 line-through' : 'text-gray-900'}`}>{topic.title}</span>
                                    {starredTopics[topic.id] && <Icon name="star5" size={10} className="text-yellow-500" />}
                                  </div>
                                </div>
                                <div className="flex items-center gap-2">
                                  <span className="text-[10px] landing-mono px-1.5 py-0.5 rounded border border-gray-200 text-gray-400">
                                    {topic.keyQuestions?.length || topic.questions || 0}Q
                                  </span>
                                  <Icon name="chevronRight" size={12} className="text-gray-300 group-hover:text-emerald-500 group-hover:translate-x-0.5 transition-all" />
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>
                      );
                    })}
                    </div>
                  </div>

                  {/* Gradient Divider */}
                  <div className="h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent mb-6" />

                  {/* System Design Problems Section - Grouped by Category */}
                  <div className="mb-6">
                    <div className="mb-4">
                      <span className="landing-mono text-xs text-emerald-600 tracking-widest uppercase">Real-World</span>
                      <h2 className="landing-display font-bold text-xl mt-1 tracking-tight text-gray-900">Common System Designs</h2>
                    </div>
                    <div className="space-y-3">
                    {systemDesignProblemCategories.map((category) => {
                      const categoryDesigns = systemDesigns.filter(d => systemDesignProblemCategoryMap[d.id] === category.id);
                      if (categoryDesigns.length === 0) return null;
                      const difficultyStyles = {
                        'Easy': 'bg-emerald-50 text-emerald-700 border-emerald-200',
                        'Medium': 'bg-amber-50 text-amber-700 border-amber-200',
                        'Hard': 'bg-red-50 text-red-700 border-red-200',
                      };
                      return (
                        <div key={category.id} className="rounded-lg overflow-hidden border border-gray-200">
                          {/* Category Header */}
                          <div className="px-4 py-2.5 flex items-center gap-2.5 bg-gray-50/80 border-b border-gray-100">
                            <div className="w-7 h-7 rounded flex items-center justify-center" style={{ background: `${category.color}12` }}>
                              <Icon name={category.icon} size={14} style={{ color: category.color }} />
                            </div>
                            <h3 className="text-sm font-semibold text-gray-900 landing-display">{category.name}</h3>
                            <span className="text-[10px] landing-mono text-gray-400">{categoryDesigns.length} systems</span>
                          </div>
                          {/* Designs in Category */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 bg-white">
                            {categoryDesigns.map((design) => {
                              const diffStyle = difficultyStyles[design.difficulty] || difficultyStyles['Medium'];
                              const designProblem = `Design ${design.title}. ${design.description || design.subtitle || ''}`;
                              return (
                                <div
                                  key={design.id}
                                  className="px-4 py-2.5 flex items-center justify-between hover:bg-gray-50 transition-all group border-b border-r border-gray-100"
                                >
                                  <div
                                    onClick={() => setSelectedTopic(design.id)}
                                    className="flex items-center gap-2.5 flex-1 cursor-pointer"
                                  >
                                    <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: `${design.color}12` }}>
                                      <Icon name={design.icon} size={11} style={{ color: design.color }} />
                                    </div>
                                    <div>
                                      <span className="text-sm landing-body font-medium text-gray-900 group-hover:text-emerald-600 transition-colors">{design.title}</span>
                                      {design.isNew && <span className="text-[10px] landing-mono px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 ml-2 font-bold">NEW</span>}
                                      <span className="text-gray-400 text-xs ml-2 hidden md:inline landing-body">{design.subtitle}</span>
                                    </div>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-[10px] landing-mono px-1.5 py-0.5 rounded border font-medium ${diffStyle}`}>
                                      {design.difficulty}
                                    </span>
                                    <a
                                      href={`/app?problem=${encodeURIComponent(designProblem)}&mode=system-design&autosolve=true`}
                                      className="px-3 py-1.5 rounded text-xs font-semibold bg-emerald-500 text-white hover:bg-emerald-600 transition-colors flex items-center gap-1.5 landing-body"
                                      onClick={(e) => e.stopPropagation()}
                                    >
                                      <Icon name="zap" size={12} />
                                      Design
                                    </a>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                    </div>
                  </div>

                  {/* Gradient Divider */}
                  <div className="h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent mb-6" />

                  {/* Low-Level Design Problems Section */}
                  <div className="mb-6">
                    <div className="mb-4">
                      <span className="landing-mono text-xs text-emerald-600 tracking-widest uppercase">Object-Oriented</span>
                      <h2 className="landing-display font-bold text-xl mt-1 tracking-tight text-gray-900">Low-Level Design</h2>
                      <p className="text-sm text-gray-500 landing-body mt-1">Class diagrams, design patterns, and OOP implementations</p>
                    </div>
                    <div className="space-y-3">
                    {lldProblemCategories.map((category) => {
                      const categoryProblems = lldProblems.filter(p => lldProblemCategoryMap[p.id] === category.id);
                      if (categoryProblems.length === 0) return null;
                      // diffStyle is computed inline per-problem below
                      return (
                        <div key={category.id} className="rounded-lg overflow-hidden border border-gray-200">
                          <div className="px-4 py-2.5 flex items-center gap-2.5 bg-gray-50/80 border-b border-gray-100">
                            <div className="w-7 h-7 rounded flex items-center justify-center" style={{ background: `${category.color}12` }}>
                              <Icon name={category.icon} size={14} style={{ color: category.color }} />
                            </div>
                            <h3 className="text-sm font-semibold text-gray-900 landing-display">{category.name}</h3>
                            <span className="text-[10px] landing-mono text-gray-400">{categoryProblems.length} problems</span>
                          </div>
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 bg-white">
                            {categoryProblems.map((problem) => {
                              const diffStyle = { Easy: 'bg-emerald-50 text-emerald-700 border-emerald-200', Medium: 'bg-amber-50 text-amber-700 border-amber-200', Hard: 'bg-red-50 text-red-700 border-red-200' }[problem.difficulty] || 'bg-amber-50 text-amber-700 border-amber-200';
                              return (
                                <div
                                  key={problem.id}
                                  onClick={() => setSelectedTopic(problem.id)}
                                  className="px-4 py-2.5 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-all group border-b border-r border-gray-100"
                                >
                                  <div className="flex items-center gap-2.5">
                                    <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: `${problem.color}12` }}>
                                      <Icon name={problem.icon} size={11} style={{ color: problem.color }} />
                                    </div>
                                    <div>
                                      <span className="text-gray-900 text-sm landing-body font-medium group-hover:text-emerald-600 transition-colors">{problem.title}</span>
                                      {problem.isNew && <span className="text-[10px] landing-mono px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 border border-emerald-200 ml-2 font-bold">NEW</span>}
                                      <span className="text-gray-400 text-xs ml-2 hidden md:inline landing-body">{problem.subtitle}</span>
                                    </div>
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-[10px] landing-mono px-1.5 py-0.5 rounded border font-medium ${diffStyle}`}>
                                      {problem.difficulty}
                                    </span>
                                    <Icon name="chevronRight" size={12} className="text-gray-300 group-hover:text-emerald-500 group-hover:translate-x-0.5 transition-all" />
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                    </div>
                  </div>

                  {/* Gradient Divider */}
                  <div className="h-px bg-gradient-to-r from-transparent via-gray-200 to-transparent mb-6" />

                  {/* Concurrency Section */}
                  <div className="mb-6">
                    <div className="mb-4">
                      <span className="landing-mono text-xs text-emerald-600 tracking-widest uppercase">Advanced</span>
                      <h2 className="landing-display font-bold text-xl mt-1 tracking-tight text-gray-900">Concurrency & Multithreading</h2>
                      <p className="text-sm text-gray-500 landing-body mt-1">Thread-safe programming, synchronization, and classic problems</p>
                    </div>
                    <div className="rounded-lg overflow-hidden border border-gray-200">
                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 bg-white">
                        {concurrencyTopics.map((topic) => (
                          <div
                            key={topic.id}
                            onClick={() => setSelectedTopic(topic.id)}
                            className="px-4 py-2.5 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-all group border-b border-r border-gray-100"
                          >
                            <div className="flex items-center gap-2.5">
                              <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: `${topic.color}12` }}>
                                <Icon name={topic.icon} size={11} style={{ color: topic.color }} />
                              </div>
                              <span className="text-gray-900 text-sm landing-body font-medium group-hover:text-emerald-600 transition-colors">{topic.title}</span>
                            </div>
                            <div className="flex items-center gap-2">
                              <span className="text-[10px] landing-mono px-1.5 py-0.5 rounded border border-gray-200 text-gray-400">
                                {topic.concepts?.length || topic.primitives?.length || topic.problems?.length || 0} items
                              </span>
                              <Icon name="chevronRight" size={12} className="text-gray-300 group-hover:text-emerald-500 group-hover:translate-x-0.5 transition-all" />
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Gradient Divider */}
                  <div className="h-px bg-gradient-to-r from-transparent via-emerald-300 to-transparent mb-6" />

                  {/* Interview Framework */}
                  <div className="rounded-lg border border-emerald-200 bg-gradient-to-br from-emerald-50/80 to-cyan-50/40 p-5">
                    <div className="mb-4">
                      <span className="landing-mono text-xs text-emerald-600 tracking-widest uppercase">Framework</span>
                      <h3 className="landing-display font-bold text-lg mt-1 tracking-tight text-gray-900 flex items-center gap-2">
                        System Design Interview
                        <span className="text-gray-400 font-normal text-sm landing-body">(45 min)</span>
                      </h3>
                    </div>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-2.5">
                      {[
                        { time: '5 min', step: 'Requirements', desc: 'Functional & non-functional requirements', num: '01', accent: 'emerald' },
                        { time: '5 min', step: 'Estimations', desc: 'QPS, storage, bandwidth calculations', num: '02', accent: 'cyan' },
                        { time: '20 min', step: 'High-Level', desc: 'Components, data flow, API design', num: '03', accent: 'emerald' },
                        { time: '15 min', step: 'Deep Dive', desc: 'Database schema, scaling, trade-offs', num: '04', accent: 'cyan' },
                      ].map((phase, i) => (
                        <div key={i} className="group p-3 rounded-lg border border-white/60 bg-white/70 hover:bg-white hover:shadow-sm transition-all">
                          <span className={`landing-mono text-2xl font-black text-${phase.accent}-200 group-hover:text-${phase.accent}-300 transition-colors`}>
                            {phase.num}
                          </span>
                          <div className="landing-mono text-[10px] text-emerald-600 font-semibold mt-1.5 mb-1">{phase.time}</div>
                          <div className="text-gray-900 font-semibold text-sm landing-display mb-0.5">{phase.step}</div>
                          <div className="text-gray-500 text-xs leading-relaxed landing-body">{phase.desc}</div>
                        </div>
                      ))}
                    </div>
                  </div>
                </>
              )}

              {/* Behavioral Content */}
              {activePage === 'behavioral' && (
                <>
                  {/* STAR Method - Compact */}
                  <div className="rounded-lg overflow-hidden mb-3" style={{ background: '#fff', border: '1px solid #e2e8f0' }}>
                    <div className="px-3 py-2 border-b border-gray-200 flex items-center gap-2" style={{ background: '#f8fafc' }}>
                      <Icon name="star" size={14} className="text-emerald-700" />
                      <h3 className="text-sm font-bold text-gray-900">The STAR Method</h3>
                      <span className="text-xs text-gray-500">— Framework for behavioral answers</span>
                    </div>
                    <div className="grid grid-cols-2 md:grid-cols-4 gap-2 p-2">
                      {[
                        { letter: 'S', title: 'Situation', desc: 'Set the scene. Be specific about when and where.', color: '#3b82f6', bg: '#eff6ff' },
                        { letter: 'T', title: 'Task', desc: 'Describe your responsibility. Focus on YOUR role.', color: '#f59e0b', bg: '#fffbeb' },
                        { letter: 'A', title: 'Action', desc: 'Explain specific steps you took. Use "I" not "we".', color: '#10b981', bg: '#ecfdf5' },
                        { letter: 'R', title: 'Result', desc: 'Share outcomes. Quantify when possible.', color: '#ef4444', bg: '#fef2f2' },
                      ].map((step, i) => (
                        <div key={i} className="flex items-start gap-2 p-2 rounded" style={{ background: step.bg, borderLeft: `3px solid ${step.color}` }}>
                          <span className="w-6 h-6 rounded flex items-center justify-center text-xs font-extrabold text-white flex-shrink-0" style={{ background: step.color }}>{step.letter}</span>
                          <div>
                            <div className="text-sm font-extrabold" style={{ color: step.color }}>{step.title}</div>
                            <div className="text-xs text-gray-700">{step.desc}</div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Question Categories Section - Grouped by Category */}
                  <div className="space-y-3 mb-4">
                    {behavioralCategories.map((category) => {
                      const categoryTopics = filteredTopics.filter(t => topicCategoryMap[t.id] === category.id);
                      if (categoryTopics.length === 0) return null;
                      return (
                        <div key={category.id} className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                          {/* Category Header */}
                          <div className="px-3 py-2 flex items-center gap-2" style={{ background: `linear-gradient(135deg, ${category.color}15, ${category.color}05)` }}>
                            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: `${category.color}20` }}>
                              <Icon name={category.icon} size={16} style={{ color: category.color }} />
                            </div>
                            <div>
                              <h3 className="text-sm font-bold text-gray-900 inline">{category.name}</h3>
                              <span className="text-xs text-gray-500 ml-2">{categoryTopics.length} topics</span>
                            </div>
                          </div>
                          {/* Topics in Category */}
                          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3" style={{ borderTop: '1px solid #f0f0f0' }}>
                            {categoryTopics.map((topic) => (
                              <div
                                key={topic.id}
                                onClick={() => setSelectedTopic(topic.id)}
                                className="px-3 py-2 flex items-center justify-between cursor-pointer hover:bg-gray-50 transition-colors group border-b border-r border-gray-100"
                              >
                                <div className="flex items-center gap-3">
                                  <div className="w-6 h-6 rounded flex items-center justify-center flex-shrink-0" style={{ background: completedTopics[topic.id] ? '#d1fae5' : `${topic.color}15` }}>
                                    {completedTopics[topic.id] ? <Icon name="check" size={12} className="text-emerald-600" /> : <Icon name={topic.icon} size={12} style={{ color: topic.color }} />}
                                  </div>
                                  <div className="flex items-center gap-2">
                                    <span className={`text-sm font-medium group-hover:text-emerald-600 transition-colors ${completedTopics[topic.id] ? 'text-gray-400' : 'text-gray-900'}`}>{topic.title}</span>
                                    {starredTopics[topic.id] && <Icon name="star5" size={10} className="text-yellow-500" />}
                                    
                                  </div>
                                </div>
                                <span className="px-2 py-0.5 rounded text-sm font-medium" style={{ background: `${topic.color}15`, color: topic.color }}>
                                  {topic.keyQuestions?.length || topic.sampleQuestions?.length || 0}Q
                                </span>
                              </div>
                            ))}
                          </div>
                        </div>
                      );
                    })}
                  </div>

                  {/* Company-Specific Section */}
                  <div className="mb-6">
                    <div className="flex items-center gap-3 mb-4">
                      <div className="w-7 h-7 rounded-lg flex items-center justify-center bg-amber-500/10">
                        <Icon name="briefcase" size={16} className="text-amber-400" />
                      </div>
                      <div>
                        <h2 className="text-sm font-bold text-gray-900">Company-Specific Prep</h2>
                        <p className="text-sm text-gray-700">Tailored guidance for top tech companies</p>
                      </div>
                    </div>
                    <div className="rounded-xl overflow-hidden" style={{ border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                      <table className="w-full">
                        <thead>
                          <tr style={{ background: '#f8fafc' }}>
                            <th className="text-left text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3">Company</th>
                            <th className="text-left text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3 hidden md:table-cell">Focus Areas</th>
                            <th className="text-right text-sm font-semibold text-gray-500 uppercase tracking-wider px-4 py-3 w-24">Topics</th>
                          </tr>
                        </thead>
                        <tbody>
                          {companyPrep.map((company) => (
                            <tr
                              key={company.id}
                              onClick={() => setSelectedTopic(company.id)}
                              className="group cursor-pointer transition-all hover:bg-gray-50"
                              className="border-t border-gray-100"
                            >
                              <td className="px-4 py-3">
                                <div className="flex items-center gap-3">
                                  <div
                                    className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                                    style={{ background: `${company.color}15` }}
                                  >
                                    <Icon name={company.icon} size={16} style={{ color: company.color }} />
                                  </div>
                                  <span className="text-gray-900 font-medium group-hover:text-emerald-600 transition-colors">{company.title}</span>
                                </div>
                              </td>
                              <td className="px-4 py-3 hidden md:table-cell">
                                <span className="text-gray-400 text-sm">{company.subtitle}</span>
                              </td>
                              <td className="px-4 py-3 text-right">
                                <span className="px-2 py-1 rounded text-sm font-medium" style={{ background: `${company.color}15`, color: company.color }}>
                                  {company.keyQuestions?.length || 0}
                                </span>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </>
              )}
            </>
          )}
        </div>
          </div>

          {/* Right Sidebar - Table of Contents (only shown on topic detail) */}
          {selectedTopic && topicDetails && tableOfContents.length > 0 && (
            <div className="w-64 flex-shrink-0 hidden xl:block">
              <div className="sticky top-24 p-6">
                <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase mb-4">On this page</div>
                <nav className="space-y-1">
                  {tableOfContents.map((item) => (
                    <a
                      key={item.id}
                      href={`#${item.id}`}
                      className="block px-3 py-2 text-sm text-gray-500 hover:text-gray-900 hover:bg-gray-50 rounded-lg transition-colors landing-body"
                    >
                      {item.label}
                    </a>
                  ))}
                </nav>

                {/* Quick Actions */}
                <div className="mt-8 pt-6 border-t border-gray-100">
                  <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase mb-4">Quick Actions</div>
                  <div className="space-y-2">
                    <a
                      href="/app"
                      className="flex items-center gap-2 px-3 py-2 text-sm text-emerald-600 hover:bg-emerald-50 rounded-lg transition-colors landing-body font-medium"
                    >
                      <Icon name="play" size={14} />
                      <span>Practice Now</span>
                    </a>
                    <button
                      onClick={() => setSelectedTopic(null)}
                      className="flex items-center gap-2 px-3 py-2 text-sm text-gray-500 hover:bg-gray-50 rounded-lg transition-colors w-full text-left landing-body"
                    >
                      <Icon name="list" size={14} />
                      <span>All Topics</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* ── Right Sidebar — Progress & TOC (visible when topic selected) ── */}
        {selectedTopic && topicDetails && (
          <div className="w-64 flex-shrink-0 h-screen sticky top-0 hidden xl:flex flex-col py-6 px-4 overflow-y-auto bg-white border-l border-gray-100">
            {/* Progress Ring */}
            <div className="text-center mb-6">
              <div className="relative w-20 h-20 mx-auto mb-3">
                <svg className="w-20 h-20 -rotate-90" viewBox="0 0 80 80">
                  <circle cx="40" cy="40" r="35" fill="none" stroke="#f1f5f9" strokeWidth="6" />
                  <circle cx="40" cy="40" r="35" fill="none" stroke="#10b981" strokeWidth="6" strokeLinecap="round"
                    strokeDasharray={`${2 * Math.PI * 35}`}
                    strokeDashoffset={`${2 * Math.PI * 35 * (1 - getProgress().percent / 100)}`}
                    style={{ transition: 'stroke-dashoffset 0.5s ease' }}
                  />
                </svg>
                <div className="absolute inset-0 flex items-center justify-center">
                  <span className="text-sm font-bold text-gray-900">{getProgress().percent}%</span>
                </div>
              </div>
              <div className="text-sm text-gray-500 landing-body">{getProgress().completed}/{getProgress().total} topics</div>
              <div className="text-xs text-gray-400 landing-mono mt-1">{pageConfig.title}</div>
            </div>

            {/* Quick Actions */}
            <div className="space-y-1.5 mb-6">
              <button
                onClick={() => toggleComplete(selectedTopic)}
                className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium transition-all landing-body ${completedTopics[selectedTopic] ? 'bg-emerald-50 text-emerald-600' : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'}`}
              >
                <Icon name={completedTopics[selectedTopic] ? 'checkCircle' : 'check'} size={14} />
                {completedTopics[selectedTopic] ? 'Completed' : 'Mark Complete'}
              </button>
              <button
                onClick={() => toggleStar(selectedTopic)}
                className={`w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium transition-all landing-body ${starredTopics[selectedTopic] ? 'text-yellow-500 bg-amber-50' : 'text-gray-500 hover:text-gray-900 hover:bg-gray-50'}`}
              >
                <Icon name={starredTopics[selectedTopic] ? 'star5' : 'star'} size={14} />
                {starredTopics[selectedTopic] ? 'Starred' : 'Add to Favorites'}
              </button>
              <button
                onClick={() => setShowAskAI(!showAskAI)}
                className="w-full flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-medium text-gray-500 hover:text-emerald-600 hover:bg-emerald-50 transition-all landing-body"
              >
                <Icon name="sparkles" size={14} />
                Ask AI
              </button>
            </div>

            {/* Table of Contents */}
            {tableOfContents.length > 0 && (
              <div>
                <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase mb-3">On This Page</div>
                <div className="space-y-0.5">
                  {tableOfContents.map((item, i) => (
                    <a
                      key={i}
                      href={`#${item.id}`}
                      className="block px-3 py-1.5 rounded text-xs text-gray-500 hover:text-gray-900 hover:bg-gray-50 transition-all truncate landing-body"
                    >
                      {item.label}
                    </a>
                  ))}
                </div>
              </div>
            )}

            {/* Starred Topics */}
            {Object.keys(starredTopics).filter(k => starredTopics[k]).length > 0 && (
              <div className="mt-6 pt-6 border-t border-gray-100">
                <div className="landing-mono text-[10px] text-emerald-600 tracking-widest uppercase mb-3">Favorites</div>
                <div className="space-y-1">
                  {Object.keys(starredTopics).filter(k => starredTopics[k]).map((topicId) => {
                    const t = [...codingTopics, ...systemDesignTopics, ...systemDesigns, ...behavioralTopics].find(x => x.id === topicId);
                    if (!t) return null;
                    return (
                      <button
                        key={topicId}
                        onClick={() => setSelectedTopic(topicId)}
                        className="w-full flex items-center gap-2 px-3 py-1.5 rounded text-xs text-left text-gray-500 hover:text-gray-900 hover:bg-gray-50 transition-all landing-body"
                      >
                        <Icon name="star5" size={10} className="text-yellow-500 flex-shrink-0" />
                        <span className="truncate">{t.title}</span>
                      </button>
                    );
                  })}
                </div>
              </div>
            )}
          </div>
        )}
      </div>

      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Work+Sans:wght@300;400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=IBM+Plex+Mono:wght@300;400;500;600&display=swap');

        .landing-root {
          -webkit-font-smoothing: antialiased;
          -moz-osx-font-smoothing: grayscale;
          font-family: 'Work Sans', 'Plus Jakarta Sans', system-ui, sans-serif;
        }

        .landing-display {
          font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
        }

        .landing-body {
          font-family: 'Work Sans', 'Plus Jakarta Sans', system-ui, sans-serif;
        }

        .landing-mono {
          font-family: 'IBM Plex Mono', monospace;
        }

        .animate-fade-in {
          animation: fadeIn 0.3s ease-out;
        }
        @keyframes fadeIn {
          from { opacity: 0; transform: translateY(10px); }
          to { opacity: 1; transform: translateY(0); }
        }
        .line-clamp-2 {
          display: -webkit-box;
          -webkit-line-clamp: 2;
          -webkit-box-orient: vertical;
          overflow: hidden;
        }
        .formatted-content pre {
          font-family: "SF Mono", Monaco, "Cascadia Code", "Roboto Mono", Consolas, "Courier New", monospace !important;
          white-space: pre !important;
          tab-size: 4 !important;
          -moz-tab-size: 4 !important;
          line-height: 1.4 !important;
          letter-spacing: 0 !important;
        }
        html { scroll-behavior: smooth; }
        /* Custom scrollbar */
        ::-webkit-scrollbar { width: 6px; height: 6px; }
        ::-webkit-scrollbar-track { background: transparent; }
        ::-webkit-scrollbar-thumb { background: #e2e8f0; border-radius: 3px; }
        ::-webkit-scrollbar-thumb:hover { background: #cbd5e1; }
        .group:hover .hover-glow { opacity: 1; }
      `}</style>
    </div>
  );
}
