import { useEffect, useState } from 'react';
import { getApiUrl } from '../hooks/useElectron';
import useElectron from '../hooks/useElectron';
import { getAuthHeaders } from '../utils/authHeaders.js';

const API_URL = getApiUrl();

/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */
function CloudArchitectureDiagram({
  imageUrl,
  expanded = false,
  loading = false,
  error = null,
  cloudProvider = 'auto'
}) {
  const [imageError, setImageError] = useState(false);

  useEffect(() => {
    if (imageUrl) {
      setImageError(false);
    }
  }, [imageUrl]);

  if (loading) {
    return (
      <div className={`p-3 rounded bg-gray-50 border border-gray-200 text-center ${expanded ? 'min-h-[400px]' : ''}`}>
        <div className="flex flex-col items-center justify-center gap-2">
          <svg className="w-5 h-5 animate-spin text-brand-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <div>
            <p className="text-xs text-gray-900 font-medium">Generating diagram...</p>
            <p className="text-xs text-gray-500">{cloudProvider.toUpperCase()}</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-2 rounded bg-error-500/10 border border-error-500/30">
        <p className="text-xs text-error-400">{error}</p>
      </div>
    );
  }

  if (!imageUrl || imageError) {
    return (
      <div className="text-center py-4 text-gray-500">
        <svg className="w-8 h-8 mx-auto mb-2 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
        </svg>
        <p className="text-xs">Click Generate for cloud architecture</p>
        <p className="text-xs text-gray-400">AWS/GCP/Azure icons</p>
        {imageError && <p className="text-xs text-error-400 mt-0.5">Image failed to load</p>}
      </div>
    );
  }

  return (
    <div className={`rounded overflow-hidden border border-gray-200 bg-gray-50 flex justify-center ${expanded ? 'p-4' : 'p-4'}`}>
      <img
        src={imageUrl}
        alt="Cloud Architecture Diagram"
        className={`h-auto object-contain ${expanded ? 'max-h-[80vh] max-w-full' : 'max-w-full'}`}
        onError={(e) => {
          console.error('[CloudDiagram] Image load error:', imageUrl, e);
          setImageError(true);
        }}
        onLoad={() => console.log('[CloudDiagram] Image loaded successfully:', imageUrl)}
      />
    </div>
  );
}

// Modal component for full-screen diagram view
function DiagramModal({ isOpen, onClose, title, children }) {
  // Handle ESC key to close modal
  useEffect(() => {
    if (!isOpen) return;

    const handleKeyDown = (e) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        e.stopPropagation();
        onClose();
      }
    };

    document.addEventListener('keydown', handleKeyDown, true);
    return () => document.removeEventListener('keydown', handleKeyDown, true);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="relative bg-white rounded-2xl shadow-2xl w-[95vw] h-[90vh] flex flex-col border border-gray-200"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-gray-200 bg-gray-50">
          <h3 className="text-sm font-semibold text-gray-800 uppercase tracking-wide">
            {title}
          </h3>
          <button
            onClick={onClose}
            className="p-2 rounded-lg bg-gray-100 hover:bg-gray-200 transition-colors"
            title="Close (ESC)"
          >
            <svg className="w-5 h-5 text-gray-900 hover:text-gray-900" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        {/* Content */}
        <div className="flex-1 overflow-auto p-4 flex items-center justify-center bg-white">
          {children}
        </div>
      </div>
    </div>
  );
}

// Collapsible section component
function CollapsibleSection({ title, icon, color, children, defaultOpen = true, badge }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg bg-white border border-gray-200 overflow-hidden">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-3 py-2 flex items-center justify-between hover:bg-gray-200/30 transition-colors"
      >
        <span className="text-xs font-semibold uppercase tracking-wide flex items-center gap-2 text-gray-600">
          {title}
          {badge && <span className="px-1.5 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-xs font-medium">{badge}</span>}
        </span>
        <svg
          className={`w-3.5 h-3.5 text-gray-500 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && <div className="px-3 pb-3 pt-1">{children}</div>}
    </div>
  );
}

/**
 * ASCII Architecture Diagram Component - Left-to-Right Flow
 */
function ASCIIDiagram({ systemDesign, detailed = false }) {
  if (!systemDesign?.included) return null;

  const str = (val) => {
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && val !== null) {
      return val.step || val.description || val.name || val.tech || JSON.stringify(val);
    }
    return String(val || '');
  };

  const techStack = (systemDesign.techJustifications?.map(t => str(t.tech || t)) || []).filter(Boolean);
  const components = (systemDesign.architecture?.components || []).map(str).filter(Boolean);

  const uniqueItems = [...new Set([...components, ...techStack])];

  const categorize = (items) => {
    const tiers = { client: [], edge: [], gateway: [], compute: [], cache: [], database: [], storage: [], queue: [] };
    const patterns = {
      client: /client|browser|mobile|app|user|frontend|web\s?app/i,
      edge: /cdn|cloudfront|cloudflare|edge|akamai/i,
      gateway: /load.?balancer|alb|nlb|elb|api.?gateway|nginx|haproxy|gateway|ingress/i,
      compute: /ec2|ecs|eks|gke|aks|lambda|function|container|server|service|k8s|kubernetes|fargate|worker|encoding|base62/i,
      cache: /redis|cache|memcache|elasticache/i,
      database: /database|db|rds|aurora|dynamo|postgres|mysql|mongo|sql|cockroach/i,
      storage: /s3|storage|gcs|blob|file|bucket|object/i,
      queue: /queue|sqs|sns|kafka|kinesis|pubsub|rabbit|event|stream|message/i
    };
    items.forEach(item => {
      const itemStr = str(item);
      if (!itemStr) return;
      let matched = false;
      for (const [tier, pattern] of Object.entries(patterns)) {
        if (pattern.test(itemStr)) {
          if (!tiers[tier].includes(itemStr)) tiers[tier].push(itemStr);
          matched = true;
          break;
        }
      }
      if (!matched && !tiers.compute.includes(itemStr)) tiers.compute.push(itemStr);
    });
    return tiers;
  };

  const tiers = categorize(uniqueItems);

  // Build LEFT-TO-RIGHT ASCII diagram
  const buildASCII = () => {
    const lines = [];
    const boxW = 18; // Wider boxes

    const makeBox = (label, w = boxW) => {
      const t = label.substring(0, w - 2);
      const pad = Math.floor((w - 2 - t.length) / 2);
      return [
        '┌' + '─'.repeat(w - 2) + '┐',
        '│' + ' '.repeat(pad) + t + ' '.repeat(w - 2 - pad - t.length) + '│',
        '└' + '─'.repeat(w - 2) + '┘'
      ];
    };

    const arrow = ' ════► ';

    // Build component boxes
    const boxes = [];

    // Client
    boxes.push({ label: '👤 Client', tier: 'client' });

    // Edge/CDN
    if (tiers.edge.length > 0) boxes.push({ label: tiers.edge[0].substring(0, 14), tier: 'edge' });

    // Gateway/LB
    if (tiers.gateway.length > 0) boxes.push({ label: tiers.gateway[0].substring(0, 14), tier: 'gateway' });

    // Compute services
    tiers.compute.slice(0, detailed ? 2 : 1).forEach(c => {
      boxes.push({ label: c.substring(0, 14), tier: 'compute' });
    });

    // Cache
    if (tiers.cache.length > 0) boxes.push({ label: '🔴 ' + tiers.cache[0].substring(0, 11), tier: 'cache' });

    // Database
    if (tiers.database.length > 0) boxes.push({ label: '💾 ' + tiers.database[0].substring(0, 11), tier: 'database' });

    // Build the horizontal flow
    if (boxes.length === 0) {
      return '  No architecture components found';
    }

    // Create 3 rows for boxes (top, middle, bottom)
    let row1 = '', row2 = '', row3 = '';

    boxes.forEach((box, i) => {
      const b = makeBox(box.label);
      const isLast = i === boxes.length - 1;

      row1 += b[0] + (isLast ? '' : '       ');
      row2 += b[1] + (isLast ? '' : arrow);
      row3 += b[2] + (isLast ? '' : '       ');
    });

    lines.push('');
    lines.push('  ' + row1);
    lines.push('  ' + row2);
    lines.push('  ' + row3);

    // Add storage/queue below if detailed
    if (detailed && (tiers.storage.length > 0 || tiers.queue.length > 0)) {
      lines.push('');
      let extras = [];
      if (tiers.storage.length > 0) extras.push('📦 Storage: ' + tiers.storage[0].substring(0, 20));
      if (tiers.queue.length > 0) extras.push('⚡ Queue: ' + tiers.queue[0].substring(0, 20));
      lines.push('  ' + extras.join('    '));
    }

    // Tech stack footer
    lines.push('');
    lines.push('  Tech: ' + techStack.slice(0, 10).join(' • '));
    lines.push('');

    return lines.join('\n');
  };

  const asciiDiagram = buildASCII();

  return (
    <div className="font-mono text-sm leading-relaxed bg-gray-100 text-brand-400 p-4 rounded whitespace-pre border border-gray-200 overflow-x-auto">
      {asciiDiagram}
    </div>
  );
}

export default function SystemDesignPanel({ systemDesign, eraserDiagram, autoGenerateEraser = false, onGenerateEraserDiagram, question, cloudProvider = 'auto', qaHistory = [], onFollowUpQuestion, isProcessingFollowUp = false, diagramOnly = false }) {
  const { isElectron } = useElectron();
  const [generatingEraser, setGeneratingEraser] = useState(false);
  const [diagramModal, setDiagramModal] = useState(false);
  const [proDiagramModal, setProDiagramModal] = useState(false);
  const [imageError, setImageError] = useState(false);

  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [diagramCache, setDiagramCache] = useState({});
  const [diagramError, setDiagramError] = useState(null);
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  const [diagramDirection, setDiagramDirection] = useState('LR');
  const [showASCII, setShowASCII] = useState(true);
  const [diagramScale, setDiagramScale] = useState(1);
  const [diagramTranslate, setDiagramTranslate] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0 });

  const diagramKey = `${diagramDetailLevel}_${diagramDirection}`;
  const diagramData = diagramCache[diagramKey] || null;
  const hasComparison = systemDesign?.comparison || systemDesign?.comparisonDiagram;

  useEffect(() => {
    if (eraserDiagram?.imageUrl) {
      setImageError(false);
    }
  }, [eraserDiagram?.imageUrl]);

  useEffect(() => {
    // Don't auto-generate diagrams for focused questions (SLIs, SLOs, metrics)
    if (systemDesign?.included && question && !diagramCache['overview_LR'] && !generatingDiagram && !diagramError && !systemDesign?.focusedAnswer) {
      const timer = setTimeout(() => {
        handleGenerateDiagram('overview', 'LR');
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [systemDesign?.included, question, systemDesign?.focusedAnswer]);

  const handleGenerateEraser = async () => {
    if (!onGenerateEraserDiagram) return;
    setGeneratingEraser(true);
    try {
      await onGenerateEraserDiagram();
    } finally {
      setGeneratingEraser(false);
    }
  };

  const handleGenerateDiagram = async (detailLevel = 'overview', direction = 'LR') => {
    if (!question) return;

    const cacheKey = `${detailLevel}_${direction}`;
    if (diagramCache[cacheKey]) {
      setDiagramDetailLevel(detailLevel);
      setDiagramDirection(direction);
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramDetailLevel(detailLevel);
    setDiagramDirection(direction);
    setDiagramScale(1);
    setDiagramTranslate({ x: 0, y: 0 });

    try {
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question,
          cloudProvider: cloudProvider || 'auto',
          difficulty: 'medium',
          category: 'System Design',
          format: 'png',
          detailLevel,
          direction,
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch {
          errorMessage = `Server error: ${response.status} ${response.statusText}`;
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();

      if (result.success && result.image_url) {
        setDiagramCache(prev => ({
          ...prev,
          [cacheKey]: {
            imageUrl: `${API_URL}${result.image_url}`,
            cloudProvider: result.cloud_provider,
            pythonCode: result.python_code,
            detailLevel,
            direction,
          }
        }));
      } else {
        throw new Error(result.error || 'Diagram generation failed');
      }
    } catch (error) {
      setDiagramError(error.message);
    } finally {
      setGeneratingDiagram(false);
    }
  };

  if (!systemDesign || !systemDesign.included) {
    return null;
  }

  // Calculate section counts for dynamic layout
  const hasRequirements = systemDesign.requirements && (systemDesign.requirements.functional?.length > 0 || systemDesign.requirements.nonFunctional?.length > 0);
  const hasArchitecture = systemDesign.architecture;
  const hasScalability = systemDesign.scalability?.length > 0;
  const hasTradeoffs = systemDesign.tradeoffs?.length > 0;
  const hasEdgeCases = systemDesign.edgeCases?.length > 0;
  const hasTechJustifications = systemDesign.techJustifications?.length > 0;
  const hasApiDesign = systemDesign.apiDesign?.length > 0;
  const hasDataModel = systemDesign.dataModel?.length > 0;
  const hasDiagram = !!systemDesign.diagram;
  const showProDiagram = autoGenerateEraser || eraserDiagram;

  // Diagram-only mode: render just the cloud architecture diagram with controls
  if (diagramOnly) {
    return (
      <div className="h-full flex flex-col overflow-hidden">
        {/* Diagram Controls */}
        <div className="flex items-center justify-between px-3 py-2 border-b border-gray-200 bg-gray-50 flex-wrap gap-2 flex-shrink-0">
          <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-900">
            Cloud Architecture {diagramData?.cloudProvider && `(${diagramData.cloudProvider.toUpperCase()})`}
          </h4>
          <div className="flex items-center gap-1.5 flex-wrap">
            <div className="flex rounded border border-gray-300 overflow-hidden">
              <button onClick={() => handleGenerateDiagram('overview', diagramDirection)} className={`px-2 py-1 text-[10px] font-semibold transition-colors ${diagramDetailLevel === 'overview' ? 'bg-emerald-500 text-white' : 'bg-white text-gray-500 hover:bg-gray-50'}`}>Overview</button>
              <button onClick={() => handleGenerateDiagram('detailed', diagramDirection)} className={`px-2 py-1 text-[10px] font-semibold transition-colors ${diagramDetailLevel === 'detailed' ? 'bg-emerald-500 text-white' : 'bg-white text-gray-500 hover:bg-gray-50'}`}>Detailed</button>
            </div>
            <div className="flex rounded border border-gray-300 overflow-hidden">
              <button onClick={() => handleGenerateDiagram(diagramDetailLevel, 'LR')} className={`px-2 py-1 text-[10px] font-semibold transition-colors ${diagramDirection === 'LR' ? 'bg-blue-500 text-white' : 'bg-white text-gray-500 hover:bg-gray-50'}`} title="Left to Right">L→R</button>
              <button onClick={() => handleGenerateDiagram(diagramDetailLevel, 'TB')} className={`px-2 py-1 text-[10px] font-semibold transition-colors ${diagramDirection === 'TB' ? 'bg-blue-500 text-white' : 'bg-white text-gray-500 hover:bg-gray-50'}`} title="Top to Bottom">T↓B</button>
            </div>
            {diagramData && (
              <div className="flex items-center gap-1">
                <button onClick={() => setDiagramScale(s => Math.max(0.3, s - 0.15))} className="w-6 h-6 flex items-center justify-center rounded border border-gray-300 bg-white text-gray-600 hover:bg-gray-50 text-xs font-bold">−</button>
                <span className="text-[10px] font-mono text-gray-500 w-8 text-center">{Math.round(diagramScale * 100)}%</span>
                <button onClick={() => setDiagramScale(s => Math.min(4, s + 0.15))} className="w-6 h-6 flex items-center justify-center rounded border border-gray-300 bg-white text-gray-600 hover:bg-gray-50 text-xs font-bold">+</button>
                <button onClick={() => { setDiagramScale(1); setDiagramTranslate({ x: 0, y: 0 }); }} className="px-1.5 py-0.5 rounded border border-gray-300 bg-white text-[10px] text-gray-500 hover:bg-gray-50">Fit</button>
              </div>
            )}
            {diagramData && (
              <button onClick={() => setDiagramModal(true)} className="w-6 h-6 flex items-center justify-center rounded border border-gray-300 bg-white text-gray-600 hover:bg-gray-50" title="Full Screen">
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" /></svg>
              </button>
            )}
          </div>
        </div>
        {/* Diagram with Pan+Zoom */}
        <div
          className="flex-1 min-h-0 overflow-hidden cursor-grab active:cursor-grabbing relative"
          onWheel={(e) => { if (diagramData) { e.preventDefault(); setDiagramScale(s => Math.min(4, Math.max(0.3, s + (e.deltaY > 0 ? -0.1 : 0.1)))); } }}
          onMouseDown={(e) => { if (diagramData) { setIsDragging(true); setDragStart({ x: e.clientX - diagramTranslate.x, y: e.clientY - diagramTranslate.y }); } }}
          onMouseMove={(e) => { if (isDragging) { setDiagramTranslate({ x: e.clientX - dragStart.x, y: e.clientY - dragStart.y }); } }}
          onMouseUp={() => setIsDragging(false)}
          onMouseLeave={() => setIsDragging(false)}
        >
          {diagramData ? (
            <img src={diagramData.imageUrl} alt="Cloud Architecture" className="select-none" draggable={false} style={{ transform: `translate(${diagramTranslate.x}px, ${diagramTranslate.y}px) scale(${diagramScale})`, transformOrigin: '0 0', maxWidth: 'none' }} onError={() => setDiagramError('Image failed to load')} />
          ) : generatingDiagram ? (
            <div className="flex flex-col items-center justify-center h-full text-gray-500">
              <svg className="w-6 h-6 animate-spin text-emerald-500 mb-2" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
              <span className="text-xs">Generating diagram...</span>
            </div>
          ) : diagramError ? (
            <div className="p-3 text-center text-red-500 text-xs">{diagramError}</div>
          ) : (
            <div className="flex flex-col items-center justify-center h-full text-gray-400">
              <svg className="w-8 h-8 mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" /></svg>
              <p className="text-xs">Auto-generating diagram...</p>
            </div>
          )}
        </div>
        <DiagramModal isOpen={diagramModal} onClose={() => setDiagramModal(false)} title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}>
          {diagramData && <div className="max-w-full max-h-full"><img src={diagramData.imageUrl} alt="Cloud Architecture" className="max-w-full max-h-[80vh] object-contain" /></div>}
        </DiagramModal>
      </div>
    );
  }

  return (
    <div className="p-2 rounded-lg animate-fade-in bg-white border border-gray-200 h-full flex flex-col overflow-hidden">
      {/* Compact Header */}
      <div className="flex-shrink-0 mb-2 pb-1.5 flex items-center justify-between border-b border-gray-200">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 rounded-full bg-brand-400" />
          <span className="text-xs font-semibold uppercase tracking-wide text-gray-800">System Design</span>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto overflow-x-hidden min-h-0">
        {/* Focused Answer Mode - For SLI/SLO/concept questions */}
        {systemDesign.focusedAnswer && systemDesign.categories && (
          <div className="space-y-2">
            {/* Overview for focused answer */}
            {systemDesign.overview && (
              <div className="rounded p-2 bg-gray-200/30 border border-gray-200">
                <p className="text-xs text-gray-900 leading-snug">{systemDesign.overview}</p>
              </div>
            )}

            {/* Categories as Compact Tables */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-2">
              {systemDesign.categories.map((category, catIdx) => (
                <div key={catIdx} className="rounded overflow-hidden border border-gray-200">
                  <div className="bg-brand-400/10 px-2 py-1 border-b border-gray-200">
                    <h4 className="text-xs font-semibold text-brand-400">{category.name}</h4>
                  </div>
                  <div className="bg-gray-50 overflow-x-auto">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b border-gray-200">
                          <th className="text-left px-2 py-1 text-gray-600 font-semibold ">Metric</th>
                          <th className="text-left px-2 py-1 text-gray-600 font-semibold ">Target</th>
                          <th className="text-left px-2 py-1 text-gray-600 font-semibold ">Measurement</th>
                          <th className="text-left px-2 py-1 text-gray-600 font-semibold ">Alert</th>
                        </tr>
                      </thead>
                      <tbody>
                        {category.items?.map((item, itemIdx) => (
                          <tr key={itemIdx} className="border-b border-gray-200/30 last:border-b-0">
                            <td className="px-2 py-1 text-gray-800 font-medium">{item.metric || item.name || '-'}</td>
                            <td className="px-2 py-1 text-brand-400 font-mono text-xs">{item.target || item.value || '-'}</td>
                            <td className="px-2 py-1 text-gray-900">{item.measurement || item.description || '-'}</td>
                            <td className="px-2 py-1 text-warning-400 text-xs">{item.alertThreshold || item.alert || '-'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Full System Design Mode - Optimized Grid Layout */}
        {!systemDesign.focusedAnswer && (
          <div className="grid grid-cols-1 sm:grid-cols-12 gap-2 auto-rows-min">

            {/* Row 1: Explanation */}
            {systemDesign.overview && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 text-gray-500">Explanation</h4>
                <p className="text-xs text-gray-900 leading-snug">{systemDesign.overview}</p>
              </div>
            )}
            {hasScalability && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <div className="flex items-start gap-3">
                  <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-500 whitespace-nowrap pt-0.5 flex items-center gap-1">
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                    </svg>
                    Scalability
                  </h4>
                  <div className="flex-1 columns-2 sm:columns-3 gap-x-3 gap-y-0.5">
                    {systemDesign.scalability.map((item, i) => (
                      <div key={i} className="break-inside-avoid mb-0.5">
                        <span className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-brand-400/10 text-brand-400 text-xs rounded border border-brand-400/30" title={item}>
                          <span className="w-1.5 h-1.5 rounded-full bg-brand-400 flex-shrink-0" />
                          {item}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}

            {/* Row 2: Requirements + Tradeoffs + Edge Cases (4 columns) */}
            {(hasRequirements || hasTradeoffs || hasEdgeCases) && (
              <>
                {systemDesign.requirements?.functional?.length > 0 && (
                  <div className="col-span-full sm:col-span-3 rounded p-2 bg-gray-200/30 border border-gray-200">
                    <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 text-gray-500">Functional</h4>
                    <ul className="space-y-0.5">
                      {systemDesign.requirements.functional.map((req, i) => (
                        <li key={i} className="text-xs text-gray-900 flex items-start gap-1.5">
                          <span className="text-brand-400 mt-0.5 flex-shrink-0 text-xs">●</span>
                          {req}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {systemDesign.requirements?.nonFunctional?.length > 0 && (
                  <div className="col-span-full sm:col-span-3 rounded p-2 bg-gray-200/30 border border-gray-200">
                    <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 text-gray-500">Non-Functional</h4>
                    <ul className="space-y-0.5">
                      {systemDesign.requirements.nonFunctional.map((req, i) => (
                        <li key={i} className="text-xs text-gray-900 flex items-start gap-1.5">
                          <span className="text-brand-400 mt-0.5 flex-shrink-0 text-xs">●</span>
                          {req}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {hasTradeoffs && (
                  <div className="col-span-full sm:col-span-3 rounded p-2 bg-warning-500/10 border border-warning-500/30">
                    <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 flex items-center gap-1 text-warning-400">
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                      </svg>
                      Tradeoffs
                    </h4>
                    <ul className="space-y-0.5">
                      {systemDesign.tradeoffs.slice(0, 4).map((tradeoff, i) => (
                        <li key={i} className="text-xs text-warning-200 flex items-start gap-1.5">
                          <span className="text-warning-400 mt-0.5 flex-shrink-0">⚖</span>
                          <span>{typeof tradeoff === 'string' ? tradeoff.replace(/^Tradeoff \d+:\s*/i, '') : tradeoff}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {hasEdgeCases && (
                  <div className="col-span-full sm:col-span-3 rounded p-2 bg-error-500/10 border border-error-500/30">
                    <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 flex items-center gap-1 text-error-400">
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                      </svg>
                      Edge Cases
                    </h4>
                    <ul className="space-y-0.5">
                      {systemDesign.edgeCases.slice(0, 4).map((edge, i) => (
                        <li key={i} className="text-xs text-error-200 flex items-start gap-1.5">
                          <span className="text-error-400 mt-0.5 flex-shrink-0">⚠</span>
                          <span>{typeof edge === 'string' ? edge.replace(/^Edge case \d+:\s*/i, '') : edge}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </>
            )}

            {/* Row 3: Architecture Components */}
            {hasArchitecture && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-1 text-gray-500">Architecture Components</h4>
                <div className="flex flex-wrap gap-1 mb-1.5">
                  {systemDesign.architecture.components?.map((component, i) => (
                    <span key={i} className="px-1.5 py-0.5 bg-gray-200 text-gray-900 text-xs rounded border border-gray-300">
                      {component}
                    </span>
                  ))}
                </div>
                {systemDesign.architecture.description && (
                  <p className="text-xs text-gray-600 leading-snug">{systemDesign.architecture.description}</p>
                )}
              </div>
            )}


            {/* Row 3b: API Design */}
            {hasApiDesign && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-1.5 flex items-center gap-1.5 text-gray-500">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 9l3 3-3 3m5 0h3M5 20h14a2 2 0 002-2V6a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                  API Design
                  <span className="px-1 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-xs">{systemDesign.apiDesign.length}</span>
                </h4>
                <div className="space-y-1.5">
                  {systemDesign.apiDesign.map((api, i) => (
                    <div key={i} className="bg-gray-50 border border-gray-200 rounded p-2">
                      <div className="flex items-center gap-2 mb-1">
                        <span className={`px-1.5 py-0.5 text-xs font-bold rounded ${
                          api.method === 'GET' ? 'bg-blue-100 text-blue-700' :
                          api.method === 'POST' ? 'bg-green-100 text-green-700' :
                          api.method === 'PUT' ? 'bg-yellow-100 text-yellow-700' :
                          api.method === 'DELETE' ? 'bg-red-100 text-red-700' :
                          'bg-gray-200 text-gray-700'
                        }`}>{api.method}</span>
                        <code className="text-xs font-mono text-gray-800">{api.endpoint}</code>
                      </div>
                      <p className="text-xs text-gray-600 leading-snug">{api.description}</p>
                      {(api.request || api.response) && (
                        <div className="grid grid-cols-2 gap-2 mt-1.5">
                          {api.request && (
                            <div>
                              <span className="text-xs font-semibold text-gray-500 uppercase">Request</span>
                              <pre className="text-xs text-gray-700 bg-gray-100 rounded p-1.5 mt-0.5 overflow-x-auto font-mono whitespace-pre-wrap">{typeof api.request === 'string' ? api.request : JSON.stringify(api.request, null, 2)}</pre>
                            </div>
                          )}
                          {api.response && (
                            <div>
                              <span className="text-xs font-semibold text-gray-500 uppercase">Response</span>
                              <pre className="text-xs text-gray-700 bg-gray-100 rounded p-1.5 mt-0.5 overflow-x-auto font-mono whitespace-pre-wrap">{typeof api.response === 'string' ? api.response : JSON.stringify(api.response, null, 2)}</pre>
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Row 3c: Data Model */}
            {hasDataModel && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-1.5 flex items-center gap-1.5 text-gray-500">
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4" />
                  </svg>
                  Data Model
                  <span className="px-1 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-xs">{systemDesign.dataModel.length}</span>
                </h4>
                <div className="grid grid-cols-1 lg:grid-cols-2 gap-1.5">
                  {systemDesign.dataModel.map((model, i) => (
                    <div key={i} className="bg-gray-50 border border-gray-200 rounded overflow-hidden">
                      <div className="bg-gray-100 px-2 py-1 border-b border-gray-200">
                        <span className="text-xs font-bold text-gray-800 font-mono">{model.table}</span>
                      </div>
                      <div className="px-2 py-1">
                        <table className="w-full text-xs">
                          <thead>
                            <tr className="border-b border-gray-200">
                              <th className="text-left py-0.5 text-gray-500 font-semibold">Field</th>
                              <th className="text-left py-0.5 text-gray-500 font-semibold">Type</th>
                              <th className="text-left py-0.5 text-gray-500 font-semibold">Description</th>
                            </tr>
                          </thead>
                          <tbody>
                            {model.fields?.map((field, fi) => (
                              <tr key={fi} className="border-b border-gray-100 last:border-0">
                                <td className="py-0.5 font-mono text-gray-800">{field.name}</td>
                                <td className="py-0.5 text-blue-600 font-mono">{field.type}</td>
                                <td className="py-0.5 text-gray-600">{field.description}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Row 3d: Mermaid Diagram */}
            {hasDiagram && (
              <div className="col-span-full rounded-lg p-3 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 text-gray-500">System Flow Diagram</h4>
                <pre className="text-xs text-gray-800 bg-gray-100 rounded p-3 overflow-x-auto font-mono whitespace-pre leading-relaxed border border-gray-200">{systemDesign.diagram.replace(/\\n/g, '\n')}</pre>
              </div>
            )}

            {/* Row 4: ASCII Diagram - Full Width */}
            <div className="col-span-full rounded-lg p-4 bg-gray-200/30 border border-gray-200">
              <div className="flex items-center justify-between mb-3">
                <h4 className="text-xs font-semibold uppercase tracking-wide text-gray-900">Architecture Flow</h4>
                <button
                  onClick={() => setDiagramDetailLevel(diagramDetailLevel === 'detailed' ? 'overview' : 'detailed')}
                  className={`px-3 py-1.5 text-xs font-medium rounded border transition-all ${
                    diagramDetailLevel === 'detailed' ? 'bg-info-500/10 text-info-400 border-info-500/30' : 'bg-brand-400/10 text-brand-400 border-brand-400/30'
                  }`}
                >
                  {diagramDetailLevel === 'detailed' ? 'Detailed' : 'Overview'}
                </button>
              </div>
              <ASCIIDiagram systemDesign={systemDesign} detailed={diagramDetailLevel === 'detailed'} />
            </div>

            {/* Row 5: Tech Justifications (compact grid) */}
            {hasTechJustifications && (
              <div className="col-span-full rounded p-2 bg-gray-200/30 border border-gray-200">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-1.5 flex items-center gap-1.5 text-gray-500">
                  Technologies
                  <span className="px-1 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-xs">{systemDesign.techJustifications.length}</span>
                </h4>
                <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-1.5">
                  {systemDesign.techJustifications.map((item, i) => (
                    <div key={i} className="bg-gray-50 border border-gray-200 rounded p-1.5 hover:border-brand-400/30 transition-colors">
                      <div className="flex flex-wrap items-center gap-1 mb-1">
                        <span className="px-1 py-0.5 bg-brand-500 text-gray-900 text-xs font-semibold rounded">{item.tech}</span>
                        {item.category && <span className="px-1 py-0.5 bg-gray-200 text-gray-600 text-xs font-medium rounded">{item.category}</span>}
                      </div>
                      <p className="text-xs text-gray-900 leading-snug line-clamp-2">{item.why}</p>
                      {item.alternatives && <p className="text-xs text-brand-400 mt-0.5 truncate"><span className="font-semibold">Alt:</span> {item.alternatives}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Row 6: Comparison (side by side, compact) */}
            {systemDesign.comparison && (
              <div className="col-span-full grid grid-cols-2 gap-2">
                {systemDesign.comparison.approach1 && (
                  <div className="rounded p-2 bg-gray-50 border border-gray-200">
                    <h5 className="text-xs font-bold text-gray-800 mb-1 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-info-400"></span>
                      {systemDesign.comparison.approach1.name || 'Approach 1'}
                    </h5>
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach1.pros?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-xs text-gray-800 flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-xs">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach1.cons?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-xs text-gray-800 flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-xs">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                )}
                {systemDesign.comparison.approach2 && (
                  <div className="rounded p-2 bg-gray-50 border border-gray-200">
                    <h5 className="text-xs font-bold text-gray-800 mb-1 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-accent-purple"></span>
                      {systemDesign.comparison.approach2.name || 'Approach 2'}
                    </h5>
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach2.pros?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-xs text-gray-800 flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-xs">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach2.cons?.length > 0 && (
                        <div>
                          <span className="text-xs font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-xs text-gray-800 flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-xs">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Row 7: Interviewer Q&A Section */}
            {onFollowUpQuestion && (
              <div className="col-span-full rounded p-2 bg-info-400/5 border border-info-400/20">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-5 h-5 rounded flex items-center justify-center bg-info-400/20">
                    <svg className="w-3 h-3 text-info-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                    </svg>
                  </div>
                  <span className="text-xs font-semibold uppercase tracking-wide text-info-400">
                    Interviewer Q&A
                  </span>
                  {qaHistory.length > 0 && (
                    <span className="px-1 py-0.5 bg-info-400/10 text-info-400 border border-info-400/30 rounded text-xs">
                      {qaHistory.length}
                    </span>
                  )}
                </div>

                {/* Q&A History - compact view */}
                {qaHistory.length > 0 ? (
                  <div className="space-y-1.5 max-h-[150px] overflow-y-auto">
                    {[...qaHistory].reverse().map((qa, i) => (
                      <div key={i} className="p-1.5 rounded bg-gray-50 border border-gray-200/30">
                        <div className="flex items-start gap-1.5 mb-1">
                          <span className="w-4 h-4 rounded flex-shrink-0 flex items-center justify-center text-xs font-bold bg-info-900/30 text-info-400">Q</span>
                          <p className="text-xs text-gray-800 font-medium line-clamp-2">{qa.question}</p>
                        </div>
                        <div className="flex items-start gap-1.5">
                          <span className="w-4 h-4 rounded flex-shrink-0 flex items-center justify-center text-xs font-bold bg-brand-900/30 text-brand-400">A</span>
                          {qa.pending ? (
                            <div className="flex items-center gap-1.5">
                              <div className="w-2.5 h-2.5 border-2 rounded-full animate-spin border-brand-400 border-t-transparent" />
                              <p className="text-xs text-gray-500 italic">Generating...</p>
                            </div>
                          ) : (
                            <p className="text-xs text-gray-900 line-clamp-3">{qa.answer}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-xs text-gray-500 text-center py-2">
                    Questions will appear here when auto-listen captures interviewer questions
                  </p>
                )}
              </div>
            )}
          </div>
        )}

        {/* Cloud Architecture Diagram Modal */}
        <DiagramModal
          isOpen={diagramModal}
          onClose={() => setDiagramModal(false)}
          title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}
        >
          {diagramData && (
            <div className="max-w-full max-h-full">
              <CloudArchitectureDiagram
                imageUrl={diagramData.imageUrl}
                expanded={true}
                cloudProvider={diagramData.cloudProvider}
              />
            </div>
          )}
        </DiagramModal>

        {/* Pro Diagram Modal (Eraser.io) */}
        <DiagramModal
          isOpen={proDiagramModal}
          onClose={() => setProDiagramModal(false)}
          title="Pro Diagram"
        >
          {eraserDiagram && (
            <div className="max-w-full max-h-full">
              <img
                src={eraserDiagram.imageUrl}
                alt="Architecture Diagram"
                className="max-w-full max-h-[80vh] object-contain"
              />
              {eraserDiagram.editUrl && (
                <div className="mt-4 text-center">
                  <a
                    href={eraserDiagram.editUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-gray-200 text-gray-800 border border-gray-200 hover:bg-gray-200 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    Edit on Eraser.io
                  </a>
                </div>
              )}
            </div>
          )}
        </DiagramModal>
      </div>
    </div>
  );
}
