import { useEffect, useState } from 'react';
import { getApiUrl } from '../hooks/useElectron';
import useElectron from '../hooks/useElectron';
import { getAuthHeaders } from '../utils/authHeaders.js';

const API_URL = getApiUrl();

/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */
function CloudArchitectureDiagram({
  imageUrl,
  expanded = false,
  loading = false,
  error = null,
  cloudProvider = 'auto'
}) {
  const [imageError, setImageError] = useState(false);

  useEffect(() => {
    if (imageUrl) {
      setImageError(false);
    }
  }, [imageUrl]);

  if (loading) {
    return (
      <div className={`p-3 rounded bg-neutral-800 border border-neutral-700/50 text-center ${expanded ? 'min-h-[400px]' : ''}`}>
        <div className="flex flex-col items-center justify-center gap-2">
          <svg className="w-5 h-5 animate-spin text-brand-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <div>
            <p className="text-[10px] text-neutral-300 font-medium">Generating diagram...</p>
            <p className="text-[9px] text-neutral-500">{cloudProvider.toUpperCase()}</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-2 rounded bg-error-500/10 border border-error-500/30">
        <p className="text-[10px] text-error-400">{error}</p>
      </div>
    );
  }

  if (!imageUrl || imageError) {
    return (
      <div className="text-center py-4 text-neutral-500">
        <svg className="w-8 h-8 mx-auto mb-2 text-neutral-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
        </svg>
        <p className="text-[9px]">Click Generate for cloud architecture</p>
        <p className="text-[8px] text-neutral-600">AWS/GCP/Azure icons</p>
        {imageError && <p className="text-[8px] text-error-400 mt-0.5">Image failed to load</p>}
      </div>
    );
  }

  return (
    <div className={`rounded overflow-hidden border border-neutral-700/50 bg-neutral-800 flex justify-center ${expanded ? 'p-4' : 'p-2'}`}>
      <img
        src={imageUrl}
        alt="Cloud Architecture Diagram"
        className={`h-auto object-contain ${expanded ? 'max-h-[80vh] max-w-full' : 'max-h-[180px] max-w-full'}`}
        onError={(e) => {
          console.error('[CloudDiagram] Image load error:', imageUrl, e);
          setImageError(true);
        }}
        onLoad={() => console.log('[CloudDiagram] Image loaded successfully:', imageUrl)}
      />
    </div>
  );
}

// Modal component for full-screen diagram view
function DiagramModal({ isOpen, onClose, title, children }) {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="relative bg-neutral-850 rounded-2xl shadow-2xl w-[95vw] h-[90vh] flex flex-col border border-neutral-700/50"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-700/50 bg-neutral-800/50">
          <h3 className="text-sm font-semibold text-neutral-200 uppercase tracking-wide">
            {title}
          </h3>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-neutral-700/50 transition-colors"
          >
            <svg className="w-5 h-5 text-neutral-400 hover:text-neutral-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        {/* Content */}
        <div className="flex-1 overflow-auto p-4 flex items-center justify-center bg-neutral-850">
          {children}
        </div>
      </div>
    </div>
  );
}

// Collapsible section component
function CollapsibleSection({ title, icon, color, children, defaultOpen = true, badge }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg bg-neutral-750 border border-neutral-700/50 overflow-hidden">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-3 py-2 flex items-center justify-between hover:bg-neutral-700/30 transition-colors"
      >
        <span className="text-xs font-semibold uppercase tracking-wide flex items-center gap-2 text-neutral-400">
          {title}
          {badge && <span className="px-1.5 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-[9px] font-medium">{badge}</span>}
        </span>
        <svg
          className={`w-3.5 h-3.5 text-neutral-500 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && <div className="px-3 pb-3 pt-1">{children}</div>}
    </div>
  );
}

/**
 * ASCII Architecture Diagram Component
 */
function ASCIIDiagram({ systemDesign, detailed = false }) {
  if (!systemDesign?.included) return null;

  const str = (val) => {
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && val !== null) {
      return val.step || val.description || val.name || val.tech || JSON.stringify(val);
    }
    return String(val || '');
  };

  const techStack = (systemDesign.techJustifications?.map(t => str(t.tech || t)) || []).filter(Boolean);
  const components = (systemDesign.architecture?.components || []).map(str).filter(Boolean);
  const dataFlow = (systemDesign.dataFlow || []).map(str).filter(Boolean);

  const uniqueItems = [...new Set([...components, ...techStack])];

  const categorize = (items) => {
    const tiers = {
      client: [],
      edge: [],
      gateway: [],
      compute: [],
      cache: [],
      database: [],
      storage: [],
      queue: [],
      monitoring: []
    };

    const patterns = {
      client: /client|browser|mobile|app|user|frontend|web\s?app/i,
      edge: /cdn|cloudfront|cloudflare|edge|akamai/i,
      gateway: /load.?balancer|alb|nlb|elb|api.?gateway|nginx|haproxy|gateway|ingress/i,
      compute: /ec2|ecs|eks|gke|aks|lambda|function|container|server|service|k8s|kubernetes|fargate|worker|encoding|base62/i,
      cache: /redis|cache|memcache|elasticache/i,
      database: /database|db|rds|aurora|dynamo|postgres|mysql|mongo|sql|cockroach/i,
      storage: /s3|storage|gcs|blob|file|bucket|object/i,
      queue: /queue|sqs|sns|kafka|kinesis|pubsub|rabbit|event|stream|message/i,
      monitoring: /monitor|cloudwatch|prometheus|grafana|log|trace|alert|metric|datadog/i
    };

    items.forEach(item => {
      const itemStr = str(item);
      if (!itemStr) return;
      let matched = false;
      for (const [tier, pattern] of Object.entries(patterns)) {
        if (pattern.test(itemStr)) {
          if (!tiers[tier].includes(itemStr)) {
            tiers[tier].push(itemStr);
          }
          matched = true;
          break;
        }
      }
      if (!matched && !tiers.compute.includes(itemStr)) {
        tiers.compute.push(itemStr);
      }
    });

    return tiers;
  };

  const tiers = categorize(uniqueItems);

  const makeBox = (text, width = null) => {
    const t = str(text);
    const w = width || t.length + 2;
    const padded = t.substring(0, w - 2).padStart(Math.floor((w - 2 + t.length) / 2)).padEnd(w - 2);
    return {
      top: '┌' + '─'.repeat(Math.max(0, w - 2)) + '┐',
      mid: '│' + padded + '│',
      bot: '└' + '─'.repeat(Math.max(0, w - 2)) + '┘',
      width: w
    };
  };

  const buildASCII = () => {
    const lines = [];
    const title = detailed ? '═══ DETAILED SYSTEM ARCHITECTURE ═══' : '═══ SYSTEM ARCHITECTURE OVERVIEW ═══';
    lines.push('');
    lines.push('  ' + title);
    lines.push('');

    const clientBox = makeBox('👤 Client', 14);
    lines.push('  ' + clientBox.top);
    lines.push('  ' + clientBox.mid);
    lines.push('  ' + clientBox.bot);
    lines.push('       │');
    lines.push('       ▼');

    if (tiers.edge.length > 0) {
      const edgeBox = makeBox(tiers.edge[0], 18);
      lines.push('  ' + edgeBox.top);
      lines.push('  ' + edgeBox.mid);
      lines.push('  ' + edgeBox.bot);
      lines.push('       │');
      lines.push('       ▼');
    }

    if (tiers.gateway.length > 0) {
      const lbBox = makeBox(tiers.gateway[0], 20);
      lines.push('  ' + lbBox.top);
      lines.push('  ' + lbBox.mid);
      lines.push('  ' + lbBox.bot);
      lines.push('       │');
      lines.push('  ┌────┴────┐');
      lines.push('  │         │');
      lines.push('  ▼         ▼');
    } else {
      lines.push('       │');
      lines.push('       ▼');
    }

    const computeItems = tiers.compute.slice(0, detailed ? 3 : 2).map(str);
    if (computeItems.length >= 2) {
      const c0 = computeItems[0];
      const c1 = computeItems[1];
      lines.push('┌' + '─'.repeat(14) + '┐   ┌' + '─'.repeat(14) + '┐');
      lines.push('│' + c0.substring(0, 14).padStart(Math.floor((14 + Math.min(c0.length, 14)) / 2)).padEnd(14) + '│   │' + c1.substring(0, 14).padStart(Math.floor((14 + Math.min(c1.length, 14)) / 2)).padEnd(14) + '│');
      lines.push('└' + '─'.repeat(14) + '┘   └' + '─'.repeat(14) + '┘');
      lines.push('       │              │');
      lines.push('       └──────┬───────┘');
      lines.push('              │');
    } else if (computeItems.length === 1) {
      const svcBox = makeBox(computeItems[0], 20);
      lines.push('  ' + svcBox.top);
      lines.push('  ' + svcBox.mid);
      lines.push('  ' + svcBox.bot);
      lines.push('         │');
    }

    const hasCache = tiers.cache.length > 0;
    const hasDb = tiers.database.length > 0;
    const hasStorage = tiers.storage.length > 0;
    const hasQueue = tiers.queue.length > 0;

    if (hasCache || hasDb || hasStorage) {
      if (hasCache && hasDb) {
        lines.push('    ┌────────┴────────┐');
        lines.push('    │                 │');
        lines.push('    ▼                 ▼');
        const cacheLabel = str(tiers.cache[0]).substring(0, 12);
        const dbLabel = str(tiers.database[0]).substring(0, 14);
        lines.push('┌' + '─'.repeat(14) + '┐   ┌' + '─'.repeat(16) + '┐');
        lines.push('│' + ('🔴 ' + cacheLabel).substring(0, 14).padStart(Math.floor((14 + cacheLabel.length + 3) / 2)).padEnd(14) + '│   │' + ('💾 ' + dbLabel).substring(0, 16).padStart(Math.floor((16 + dbLabel.length + 3) / 2)).padEnd(16) + '│');
        lines.push('└' + '─'.repeat(14) + '┘   └' + '─'.repeat(16) + '┘');
      } else if (hasDb) {
        lines.push('              │');
        lines.push('              ▼');
        const dbBox = makeBox('💾 ' + str(tiers.database[0]), 22);
        lines.push('     ' + dbBox.top);
        lines.push('     ' + dbBox.mid);
        lines.push('     ' + dbBox.bot);
      } else if (hasCache) {
        lines.push('              │');
        lines.push('              ▼');
        const cacheBox = makeBox('🔴 ' + str(tiers.cache[0]), 20);
        lines.push('     ' + cacheBox.top);
        lines.push('     ' + cacheBox.mid);
        lines.push('     ' + cacheBox.bot);
      }
    }

    if (hasStorage && detailed) {
      lines.push('');
      lines.push('         ┌───────────────────┐');
      lines.push('         │ 📦 ' + str(tiers.storage[0]).substring(0, 14).padEnd(14) + '│');
      lines.push('         └───────────────────┘');
    }

    if (hasQueue && detailed) {
      lines.push('');
      lines.push('  ╔══════════════════════════╗');
      lines.push('  ║ ⚡ ASYNC: ' + tiers.queue.map(str).slice(0, 2).join(', ').substring(0, 15).padEnd(15) + '║');
      lines.push('  ╚══════════════════════════╝');
    }

    if (dataFlow.length > 0 && detailed) {
      lines.push('');
      lines.push('  ┄┄┄ DATA FLOW ┄┄┄');
      dataFlow.slice(0, 3).forEach((flow, i) => {
        lines.push('  ' + (i + 1) + '. ' + str(flow).substring(0, 50));
      });
    }

    lines.push('');
    lines.push('  ════════════════════════════════════════');
    lines.push('  TECH: ' + techStack.map(str).slice(0, 6).join(' • ').substring(0, 45));
    lines.push('');

    return lines.join('\n');
  };

  const asciiDiagram = buildASCII();

  return (
    <div className="font-mono text-[10px] leading-tight bg-neutral-900 text-brand-400 p-2 rounded overflow-x-auto whitespace-pre border border-neutral-700/50 max-h-[200px] overflow-y-auto">
      {asciiDiagram}
    </div>
  );
}

export default function SystemDesignPanel({ systemDesign, eraserDiagram, autoGenerateEraser = false, onGenerateEraserDiagram, question, cloudProvider = 'auto', qaHistory = [], onFollowUpQuestion, isProcessingFollowUp = false }) {
  const { isElectron } = useElectron();
  const [generatingEraser, setGeneratingEraser] = useState(false);
  const [diagramModal, setDiagramModal] = useState(false);
  const [proDiagramModal, setProDiagramModal] = useState(false);
  const [imageError, setImageError] = useState(false);

  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [overviewDiagram, setOverviewDiagram] = useState(null);
  const [detailedDiagram, setDetailedDiagram] = useState(null);
  const [diagramError, setDiagramError] = useState(null);
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  const [showASCII, setShowASCII] = useState(true);

  const diagramData = diagramDetailLevel === 'detailed' ? detailedDiagram : overviewDiagram;
  const hasComparison = systemDesign?.comparison || systemDesign?.comparisonDiagram;

  useEffect(() => {
    if (eraserDiagram?.imageUrl) {
      setImageError(false);
    }
  }, [eraserDiagram?.imageUrl]);

  useEffect(() => {
    // Don't auto-generate diagrams for focused questions (SLIs, SLOs, metrics)
    if (systemDesign?.included && question && !overviewDiagram && !generatingDiagram && !diagramError && !systemDesign?.focusedAnswer) {
      const timer = setTimeout(() => {
        handleGenerateDiagram('overview');
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [systemDesign?.included, question, systemDesign?.focusedAnswer]);

  const handleGenerateEraser = async () => {
    if (!onGenerateEraserDiagram) return;
    setGeneratingEraser(true);
    try {
      await onGenerateEraserDiagram();
    } finally {
      setGeneratingEraser(false);
    }
  };

  const handleGenerateDiagram = async (detailLevel = 'overview') => {
    if (!question) return;

    const cachedDiagram = detailLevel === 'detailed' ? detailedDiagram : overviewDiagram;
    if (cachedDiagram) {
      setDiagramDetailLevel(detailLevel);
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramDetailLevel(detailLevel);

    try {
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question,
          cloudProvider: cloudProvider || 'auto',
          difficulty: 'medium',
          category: 'System Design',
          format: 'png',
          detailLevel: detailLevel
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch {
          errorMessage = `Server error: ${response.status} ${response.statusText}`;
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();

      if (result.success && result.image_url) {
        const newDiagramData = {
          imageUrl: `${API_URL}${result.image_url}`,
          cloudProvider: result.cloud_provider,
          pythonCode: result.python_code,
          detailLevel: detailLevel
        };

        if (detailLevel === 'detailed') {
          setDetailedDiagram(newDiagramData);
        } else {
          setOverviewDiagram(newDiagramData);
        }
      } else {
        throw new Error(result.error || 'Diagram generation failed');
      }
    } catch (error) {
      console.error('[Diagram] Generation error:', error);
      setDiagramError(error.message);
    } finally {
      setGeneratingDiagram(false);
    }
  };

  if (!systemDesign || !systemDesign.included) {
    return null;
  }

  // Calculate section counts for dynamic layout
  const hasRequirements = systemDesign.requirements && (systemDesign.requirements.functional?.length > 0 || systemDesign.requirements.nonFunctional?.length > 0);
  const hasArchitecture = systemDesign.architecture;
  const hasScalability = systemDesign.scalability?.length > 0;
  const hasTradeoffs = systemDesign.tradeoffs?.length > 0;
  const hasEdgeCases = systemDesign.edgeCases?.length > 0;
  const hasTechJustifications = systemDesign.techJustifications?.length > 0;
  const showProDiagram = autoGenerateEraser || eraserDiagram;

  return (
    <div className="p-2 rounded-xl animate-fade-in bg-neutral-750 border border-neutral-700/50 h-full flex flex-col overflow-hidden">
      {/* Compact Header */}
      <div className="flex-shrink-0 mb-2 pb-1.5 flex items-center justify-between border-b border-neutral-700/50">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 rounded-full bg-brand-400" />
          <span className="text-[10px] font-semibold uppercase tracking-wide text-neutral-200">System Design</span>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto overflow-x-hidden min-h-0">
        {/* Focused Answer Mode - For SLI/SLO/concept questions */}
        {systemDesign.focusedAnswer && systemDesign.categories && (
          <div className="space-y-2">
            {/* Overview for focused answer */}
            {systemDesign.overview && (
              <div className="rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <p className="text-xs text-neutral-300 leading-snug">{systemDesign.overview}</p>
              </div>
            )}

            {/* Categories as Compact Tables */}
            <div className="grid grid-cols-1 xl:grid-cols-2 gap-2">
              {systemDesign.categories.map((category, catIdx) => (
                <div key={catIdx} className="rounded overflow-hidden border border-neutral-600/50">
                  <div className="bg-brand-400/10 px-2 py-1 border-b border-neutral-600/50">
                    <h4 className="text-[10px] font-semibold text-brand-400">{category.name}</h4>
                  </div>
                  <div className="bg-neutral-800/50 overflow-x-auto">
                    <table className="w-full text-[10px]">
                      <thead>
                        <tr className="border-b border-neutral-700/50">
                          <th className="text-left px-2 py-1 text-neutral-400 font-semibold whitespace-nowrap">Metric</th>
                          <th className="text-left px-2 py-1 text-neutral-400 font-semibold whitespace-nowrap">Target</th>
                          <th className="text-left px-2 py-1 text-neutral-400 font-semibold whitespace-nowrap">Measurement</th>
                          <th className="text-left px-2 py-1 text-neutral-400 font-semibold whitespace-nowrap">Alert</th>
                        </tr>
                      </thead>
                      <tbody>
                        {category.items?.map((item, itemIdx) => (
                          <tr key={itemIdx} className="border-b border-neutral-700/30 last:border-b-0">
                            <td className="px-2 py-1 text-neutral-200 font-medium">{item.metric || item.name || '-'}</td>
                            <td className="px-2 py-1 text-brand-400 font-mono text-[9px]">{item.target || item.value || '-'}</td>
                            <td className="px-2 py-1 text-neutral-300">{item.measurement || item.description || '-'}</td>
                            <td className="px-2 py-1 text-warning-400 text-[9px]">{item.alertThreshold || item.alert || '-'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Full System Design Mode - Optimized Grid Layout */}
        {!systemDesign.focusedAnswer && (
          <div className="grid grid-cols-12 gap-2 auto-rows-min">

            {/* Row 1: Explanation (spans 8) + Scalability (spans 4) */}
            {systemDesign.overview && (
              <div className={`rounded p-2 bg-neutral-700/30 border border-neutral-600/50 ${hasScalability ? 'col-span-8' : 'col-span-12'}`}>
                <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 text-neutral-500">Explanation</h4>
                <p className="text-[11px] text-neutral-300 leading-snug">{systemDesign.overview}</p>
              </div>
            )}
            {hasScalability && (
              <div className="col-span-4 rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 text-neutral-500">Scalability</h4>
                <div className="flex flex-wrap gap-1">
                  {systemDesign.scalability.map((item, i) => (
                    <span key={i} className="inline-flex items-center gap-1 px-1.5 py-0.5 bg-brand-400/10 text-brand-400 text-[9px] rounded border border-brand-400/30" title={item}>
                      <svg className="w-2.5 h-2.5 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                      </svg>
                      {item.length > 20 ? item.substring(0, 18) + '...' : item}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {/* Row 2: Requirements + Tradeoffs + Edge Cases (4 columns) */}
            {(hasRequirements || hasTradeoffs || hasEdgeCases) && (
              <>
                {systemDesign.requirements?.functional?.length > 0 && (
                  <div className="col-span-3 rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                    <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 text-neutral-500">Functional</h4>
                    <ul className="space-y-0.5">
                      {systemDesign.requirements.functional.map((req, i) => (
                        <li key={i} className="text-[10px] text-neutral-300 flex items-start gap-1.5">
                          <span className="text-brand-400 mt-0.5 flex-shrink-0 text-[8px]">●</span>
                          {req}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {systemDesign.requirements?.nonFunctional?.length > 0 && (
                  <div className="col-span-3 rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                    <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 text-neutral-500">Non-Functional</h4>
                    <ul className="space-y-0.5">
                      {systemDesign.requirements.nonFunctional.map((req, i) => (
                        <li key={i} className="text-[10px] text-neutral-300 flex items-start gap-1.5">
                          <span className="text-brand-400 mt-0.5 flex-shrink-0 text-[8px]">●</span>
                          {req}
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {hasTradeoffs && (
                  <div className="col-span-3 rounded p-2 bg-warning-500/10 border border-warning-500/30">
                    <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 flex items-center gap-1 text-warning-400">
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                      </svg>
                      Tradeoffs
                    </h4>
                    <ul className="space-y-0.5">
                      {systemDesign.tradeoffs.slice(0, 4).map((tradeoff, i) => (
                        <li key={i} className="text-[10px] text-warning-200 flex items-start gap-1.5">
                          <span className="text-warning-400 mt-0.5 flex-shrink-0">⚖</span>
                          <span>{typeof tradeoff === 'string' ? tradeoff.replace(/^Tradeoff \d+:\s*/i, '') : tradeoff}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {hasEdgeCases && (
                  <div className="col-span-3 rounded p-2 bg-error-500/10 border border-error-500/30">
                    <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 flex items-center gap-1 text-error-400">
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                      </svg>
                      Edge Cases
                    </h4>
                    <ul className="space-y-0.5">
                      {systemDesign.edgeCases.slice(0, 4).map((edge, i) => (
                        <li key={i} className="text-[10px] text-error-200 flex items-start gap-1.5">
                          <span className="text-error-400 mt-0.5 flex-shrink-0">⚠</span>
                          <span>{typeof edge === 'string' ? edge.replace(/^Edge case \d+:\s*/i, '') : edge}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </>
            )}

            {/* Row 3: Architecture Components */}
            {hasArchitecture && (
              <div className="col-span-12 rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1 text-neutral-500">Architecture Components</h4>
                <div className="flex flex-wrap gap-1 mb-1.5">
                  {systemDesign.architecture.components?.map((component, i) => (
                    <span key={i} className="px-1.5 py-0.5 bg-neutral-600/50 text-neutral-300 text-[9px] rounded border border-neutral-500/50">
                      {component}
                    </span>
                  ))}
                </div>
                {systemDesign.architecture.description && (
                  <p className="text-[10px] text-neutral-400 leading-snug">{systemDesign.architecture.description}</p>
                )}
              </div>
            )}


            {/* Row 4: Diagrams Side by Side (ASCII + Cloud) */}
            <div className="col-span-12 grid grid-cols-2 gap-2">
              {/* ASCII Diagram */}
              <div className="rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <div className="flex items-center justify-between mb-1.5">
                  <h4 className="text-[9px] font-semibold uppercase tracking-wide text-neutral-500">ASCII Architecture</h4>
                  <button
                    onClick={() => setDiagramDetailLevel(diagramDetailLevel === 'detailed' ? 'overview' : 'detailed')}
                    className={`px-1.5 py-0.5 text-[8px] font-medium rounded border transition-all ${
                      diagramDetailLevel === 'detailed' ? 'bg-info-500/10 text-info-400 border-info-500/30' : 'bg-brand-400/10 text-brand-400 border-brand-400/30'
                    }`}
                  >
                    {diagramDetailLevel === 'detailed' ? 'Detailed' : 'Overview'}
                  </button>
                </div>
                <ASCIIDiagram systemDesign={systemDesign} detailed={diagramDetailLevel === 'detailed'} />
              </div>

              {/* Cloud Diagram */}
              <div className="rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <div className="flex items-center justify-between mb-1.5">
                  <h4 className="text-[9px] font-semibold uppercase tracking-wide text-neutral-500">
                    Cloud {diagramData?.cloudProvider && `(${diagramData.cloudProvider.toUpperCase()})`}
                  </h4>
                  <div className="flex items-center gap-1">
                    {diagramData && (
                      <button
                        onClick={() => setDiagramModal(true)}
                        className="flex items-center gap-0.5 px-1.5 py-0.5 text-[8px] font-medium rounded border bg-brand-400 text-white border-brand-400 hover:bg-brand-500"
                      >
                        <svg className="w-2.5 h-2.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
                        </svg>
                        Expand
                      </button>
                    )}
                    {!diagramData && !generatingDiagram && (
                      <button
                        onClick={() => handleGenerateDiagram('overview')}
                        className="px-1.5 py-0.5 text-[8px] font-medium rounded border bg-brand-400 text-white border-brand-400 hover:bg-brand-500"
                      >
                        Generate
                      </button>
                    )}
                    {diagramData && !detailedDiagram && diagramDetailLevel !== 'detailed' && (
                      <button
                        onClick={() => handleGenerateDiagram('detailed')}
                        disabled={generatingDiagram}
                        className="px-1.5 py-0.5 text-[8px] font-medium rounded border bg-info-500 text-white border-info-500 hover:bg-info-600"
                      >
                        Deep Dive
                      </button>
                    )}
                  </div>
                </div>
                <CloudArchitectureDiagram
                  imageUrl={diagramData?.imageUrl}
                  loading={generatingDiagram}
                  error={diagramError}
                  cloudProvider={diagramData?.cloudProvider || cloudProvider}
                />
              </div>
            </div>

            {/* Row 6: Tech Justifications (compact grid) */}
            {hasTechJustifications && (
              <div className="col-span-12 rounded p-2 bg-neutral-700/30 border border-neutral-600/50">
                <h4 className="text-[9px] font-semibold uppercase tracking-wide mb-1.5 flex items-center gap-1.5 text-neutral-500">
                  Technologies
                  <span className="px-1 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-[8px]">{systemDesign.techJustifications.length}</span>
                </h4>
                <div className="grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-1.5">
                  {systemDesign.techJustifications.map((item, i) => (
                    <div key={i} className="bg-neutral-800 border border-neutral-700/50 rounded p-1.5 hover:border-brand-400/30 transition-colors">
                      <div className="flex flex-wrap items-center gap-1 mb-1">
                        <span className="px-1 py-0.5 bg-brand-500 text-white text-[8px] font-semibold rounded">{item.tech}</span>
                        {item.category && <span className="px-1 py-0.5 bg-neutral-700 text-neutral-400 text-[7px] font-medium rounded">{item.category}</span>}
                      </div>
                      <p className="text-[9px] text-neutral-300 leading-snug line-clamp-2">{item.why}</p>
                      {item.alternatives && <p className="text-[8px] text-brand-400 mt-0.5 truncate"><span className="font-semibold">Alt:</span> {item.alternatives}</p>}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Row 6: Comparison (side by side, compact) */}
            {systemDesign.comparison && (
              <div className="col-span-12 grid grid-cols-2 gap-2">
                {systemDesign.comparison.approach1 && (
                  <div className="rounded p-2 bg-neutral-800 border border-neutral-700/50">
                    <h5 className="text-[10px] font-bold text-neutral-200 mb-1 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-info-400"></span>
                      {systemDesign.comparison.approach1.name || 'Approach 1'}
                    </h5>
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach1.pros?.length > 0 && (
                        <div>
                          <span className="text-[8px] font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-[9px] text-neutral-200 flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-[8px]">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach1.cons?.length > 0 && (
                        <div>
                          <span className="text-[8px] font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach1.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-[9px] text-neutral-200 flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-[8px]">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                )}
                {systemDesign.comparison.approach2 && (
                  <div className="rounded p-2 bg-neutral-800 border border-neutral-700/50">
                    <h5 className="text-[10px] font-bold text-neutral-200 mb-1 flex items-center gap-1.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-accent-purple"></span>
                      {systemDesign.comparison.approach2.name || 'Approach 2'}
                    </h5>
                    <div className="grid grid-cols-2 gap-2">
                      {systemDesign.comparison.approach2.pros?.length > 0 && (
                        <div>
                          <span className="text-[8px] font-semibold text-brand-400 uppercase">Pros</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.pros.slice(0, 3).map((pro, i) => (
                              <li key={i} className="text-[9px] text-neutral-200 flex items-start gap-1">
                                <span className="text-brand-400 mt-0.5 text-[8px]">+</span>
                                <span className="line-clamp-1">{pro}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                      {systemDesign.comparison.approach2.cons?.length > 0 && (
                        <div>
                          <span className="text-[8px] font-semibold text-error-400 uppercase">Cons</span>
                          <ul className="mt-0.5 space-y-0.5">
                            {systemDesign.comparison.approach2.cons.slice(0, 3).map((con, i) => (
                              <li key={i} className="text-[9px] text-neutral-200 flex items-start gap-1">
                                <span className="text-error-400 mt-0.5 text-[8px]">-</span>
                                <span className="line-clamp-1">{con}</span>
                              </li>
                            ))}
                          </ul>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Row 7: Interviewer Q&A Section */}
            {onFollowUpQuestion && (
              <div className="col-span-12 rounded p-2 bg-info-400/5 border border-info-400/20">
                <div className="flex items-center gap-2 mb-2">
                  <div className="w-5 h-5 rounded flex items-center justify-center bg-info-400/20">
                    <svg className="w-3 h-3 text-info-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11a7 7 0 01-7 7m0 0a7 7 0 01-7-7m7 7v4m0 0H8m4 0h4m-4-8a3 3 0 01-3-3V5a3 3 0 116 0v6a3 3 0 01-3 3z" />
                    </svg>
                  </div>
                  <span className="text-[9px] font-semibold uppercase tracking-wide text-info-400">
                    Interviewer Q&A
                  </span>
                  {qaHistory.length > 0 && (
                    <span className="px-1 py-0.5 bg-info-400/10 text-info-400 border border-info-400/30 rounded text-[8px]">
                      {qaHistory.length}
                    </span>
                  )}
                </div>

                {/* Q&A History - compact view */}
                {qaHistory.length > 0 ? (
                  <div className="space-y-1.5 max-h-[150px] overflow-y-auto">
                    {[...qaHistory].reverse().map((qa, i) => (
                      <div key={i} className="p-1.5 rounded bg-neutral-800/50 border border-neutral-700/30">
                        <div className="flex items-start gap-1.5 mb-1">
                          <span className="w-4 h-4 rounded flex-shrink-0 flex items-center justify-center text-[8px] font-bold bg-info-900/30 text-info-400">Q</span>
                          <p className="text-[10px] text-neutral-200 font-medium line-clamp-2">{qa.question}</p>
                        </div>
                        <div className="flex items-start gap-1.5">
                          <span className="w-4 h-4 rounded flex-shrink-0 flex items-center justify-center text-[8px] font-bold bg-brand-900/30 text-brand-400">A</span>
                          {qa.pending ? (
                            <div className="flex items-center gap-1.5">
                              <div className="w-2.5 h-2.5 border-2 rounded-full animate-spin border-brand-400 border-t-transparent" />
                              <p className="text-[9px] text-neutral-500 italic">Generating...</p>
                            </div>
                          ) : (
                            <p className="text-[10px] text-neutral-300 line-clamp-3">{qa.answer}</p>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                ) : (
                  <p className="text-[9px] text-neutral-500 text-center py-2">
                    Questions will appear here when auto-listen captures interviewer questions
                  </p>
                )}
              </div>
            )}
          </div>
        )}

        {/* Cloud Architecture Diagram Modal */}
        <DiagramModal
          isOpen={diagramModal}
          onClose={() => setDiagramModal(false)}
          title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}
        >
          {diagramData && (
            <div className="max-w-full max-h-full">
              <CloudArchitectureDiagram
                imageUrl={diagramData.imageUrl}
                expanded={true}
                cloudProvider={diagramData.cloudProvider}
              />
            </div>
          )}
        </DiagramModal>

        {/* Pro Diagram Modal (Eraser.io) */}
        <DiagramModal
          isOpen={proDiagramModal}
          onClose={() => setProDiagramModal(false)}
          title="Pro Diagram"
        >
          {eraserDiagram && (
            <div className="max-w-full max-h-full">
              <img
                src={eraserDiagram.imageUrl}
                alt="Architecture Diagram"
                className="max-w-full max-h-[80vh] object-contain"
              />
              {eraserDiagram.editUrl && (
                <div className="mt-4 text-center">
                  <a
                    href={eraserDiagram.editUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-neutral-700 text-neutral-200 border border-neutral-600/50 hover:bg-neutral-600 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    Edit on Eraser.io
                  </a>
                </div>
              )}
            </div>
          )}
        </DiagramModal>
      </div>
    </div>
  );
}
