import { useEffect, useState } from 'react';
import { getApiUrl } from '../hooks/useElectron';
import useElectron from '../hooks/useElectron';
import { getAuthHeaders } from '../utils/authHeaders.js';

const API_URL = getApiUrl();

/**
 * Cloud Architecture Diagram Component
 * Displays PNG diagrams generated by the Python diagrams library
 */
function CloudArchitectureDiagram({
  imageUrl,
  expanded = false,
  loading = false,
  error = null,
  cloudProvider = 'auto'
}) {
  const [imageError, setImageError] = useState(false);

  useEffect(() => {
    if (imageUrl) {
      setImageError(false);
    }
  }, [imageUrl]);

  if (loading) {
    return (
      <div className={`p-6 rounded-lg bg-neutral-800 border border-neutral-700/50 text-center ${expanded ? 'min-h-[400px]' : ''}`}>
        <div className="flex flex-col items-center justify-center gap-3">
          <svg className="w-8 h-8 animate-spin text-brand-400" fill="none" viewBox="0 0 24 24">
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
          </svg>
          <div>
            <p className="text-sm text-neutral-300 font-medium">Generating architecture diagram...</p>
            <p className="text-xs text-neutral-500 mt-1">Using {cloudProvider.toUpperCase()} cloud icons</p>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="p-4 rounded-lg bg-error-500/10 border border-error-500/30">
        <p className="text-sm text-error-400">{error}</p>
      </div>
    );
  }

  if (!imageUrl || imageError) {
    return (
      <div className="text-center py-6 text-neutral-500">
        <svg className="w-12 h-12 mx-auto mb-3 text-neutral-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 15a4 4 0 004 4h9a5 5 0 10-.1-9.999 5.002 5.002 0 10-9.78 2.096A4.001 4.001 0 003 15z" />
        </svg>
        <p className="text-xs">Click Generate for cloud architecture diagram</p>
        <p className="text-[10px] text-neutral-600 mt-1">Real AWS/GCP/Azure icons</p>
        {imageError && <p className="text-[10px] text-error-400 mt-1">Image failed to load</p>}
      </div>
    );
  }

  return (
    <div className={`rounded-lg overflow-hidden border border-neutral-700/50 bg-neutral-800 flex justify-center ${expanded ? 'p-4' : 'p-3'}`}>
      <img
        src={imageUrl}
        alt="Cloud Architecture Diagram"
        className={`h-auto object-contain ${expanded ? 'max-h-[80vh] max-w-full' : 'max-w-[60%]'}`}
        onError={(e) => {
          console.error('[CloudDiagram] Image load error:', imageUrl, e);
          setImageError(true);
        }}
        onLoad={() => console.log('[CloudDiagram] Image loaded successfully:', imageUrl)}
      />
    </div>
  );
}

// Modal component for full-screen diagram view
function DiagramModal({ isOpen, onClose, title, children }) {
  if (!isOpen) return null;

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <div
        className="relative bg-neutral-850 rounded-2xl shadow-2xl w-[95vw] h-[90vh] flex flex-col border border-neutral-700/50"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-700/50 bg-neutral-800/50">
          <h3 className="text-sm font-semibold text-neutral-200 uppercase tracking-wide">
            {title}
          </h3>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-neutral-700/50 transition-colors"
          >
            <svg className="w-5 h-5 text-neutral-400 hover:text-neutral-200" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        {/* Content */}
        <div className="flex-1 overflow-auto p-4 flex items-center justify-center bg-neutral-850">
          {children}
        </div>
      </div>
    </div>
  );
}

// Collapsible section component
function CollapsibleSection({ title, icon, color, children, defaultOpen = true, badge }) {
  const [isOpen, setIsOpen] = useState(defaultOpen);

  return (
    <div className="rounded-lg bg-neutral-750 border border-neutral-700/50 overflow-hidden">
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full px-3 py-2 flex items-center justify-between hover:bg-neutral-700/30 transition-colors"
      >
        <span className="text-xs font-semibold uppercase tracking-wide flex items-center gap-2 text-neutral-400">
          {title}
          {badge && <span className="px-1.5 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-[9px] font-medium">{badge}</span>}
        </span>
        <svg
          className={`w-3.5 h-3.5 text-neutral-500 transition-transform ${isOpen ? 'rotate-180' : ''}`}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </button>
      {isOpen && <div className="px-3 pb-3 pt-1">{children}</div>}
    </div>
  );
}

/**
 * ASCII Architecture Diagram Component
 */
function ASCIIDiagram({ systemDesign, detailed = false }) {
  if (!systemDesign?.included) return null;

  const str = (val) => {
    if (typeof val === 'string') return val;
    if (typeof val === 'object' && val !== null) {
      return val.step || val.description || val.name || val.tech || JSON.stringify(val);
    }
    return String(val || '');
  };

  const techStack = (systemDesign.techJustifications?.map(t => str(t.tech || t)) || []).filter(Boolean);
  const components = (systemDesign.architecture?.components || []).map(str).filter(Boolean);
  const dataFlow = (systemDesign.dataFlow || []).map(str).filter(Boolean);

  const uniqueItems = [...new Set([...components, ...techStack])];

  const categorize = (items) => {
    const tiers = {
      client: [],
      edge: [],
      gateway: [],
      compute: [],
      cache: [],
      database: [],
      storage: [],
      queue: [],
      monitoring: []
    };

    const patterns = {
      client: /client|browser|mobile|app|user|frontend|web\s?app/i,
      edge: /cdn|cloudfront|cloudflare|edge|akamai/i,
      gateway: /load.?balancer|alb|nlb|elb|api.?gateway|nginx|haproxy|gateway|ingress/i,
      compute: /ec2|ecs|eks|gke|aks|lambda|function|container|server|service|k8s|kubernetes|fargate|worker|encoding|base62/i,
      cache: /redis|cache|memcache|elasticache/i,
      database: /database|db|rds|aurora|dynamo|postgres|mysql|mongo|sql|cockroach/i,
      storage: /s3|storage|gcs|blob|file|bucket|object/i,
      queue: /queue|sqs|sns|kafka|kinesis|pubsub|rabbit|event|stream|message/i,
      monitoring: /monitor|cloudwatch|prometheus|grafana|log|trace|alert|metric|datadog/i
    };

    items.forEach(item => {
      const itemStr = str(item);
      if (!itemStr) return;
      let matched = false;
      for (const [tier, pattern] of Object.entries(patterns)) {
        if (pattern.test(itemStr)) {
          if (!tiers[tier].includes(itemStr)) {
            tiers[tier].push(itemStr);
          }
          matched = true;
          break;
        }
      }
      if (!matched && !tiers.compute.includes(itemStr)) {
        tiers.compute.push(itemStr);
      }
    });

    return tiers;
  };

  const tiers = categorize(uniqueItems);

  const makeBox = (text, width = null) => {
    const t = str(text);
    const w = width || t.length + 2;
    const padded = t.substring(0, w - 2).padStart(Math.floor((w - 2 + t.length) / 2)).padEnd(w - 2);
    return {
      top: '┌' + '─'.repeat(Math.max(0, w - 2)) + '┐',
      mid: '│' + padded + '│',
      bot: '└' + '─'.repeat(Math.max(0, w - 2)) + '┘',
      width: w
    };
  };

  const buildASCII = () => {
    const lines = [];
    const title = detailed ? '═══ DETAILED SYSTEM ARCHITECTURE ═══' : '═══ SYSTEM ARCHITECTURE OVERVIEW ═══';
    lines.push('');
    lines.push('  ' + title);
    lines.push('');

    const clientBox = makeBox('👤 Client', 14);
    lines.push('  ' + clientBox.top);
    lines.push('  ' + clientBox.mid);
    lines.push('  ' + clientBox.bot);
    lines.push('       │');
    lines.push('       ▼');

    if (tiers.edge.length > 0) {
      const edgeBox = makeBox(tiers.edge[0], 18);
      lines.push('  ' + edgeBox.top);
      lines.push('  ' + edgeBox.mid);
      lines.push('  ' + edgeBox.bot);
      lines.push('       │');
      lines.push('       ▼');
    }

    if (tiers.gateway.length > 0) {
      const lbBox = makeBox(tiers.gateway[0], 20);
      lines.push('  ' + lbBox.top);
      lines.push('  ' + lbBox.mid);
      lines.push('  ' + lbBox.bot);
      lines.push('       │');
      lines.push('  ┌────┴────┐');
      lines.push('  │         │');
      lines.push('  ▼         ▼');
    } else {
      lines.push('       │');
      lines.push('       ▼');
    }

    const computeItems = tiers.compute.slice(0, detailed ? 3 : 2).map(str);
    if (computeItems.length >= 2) {
      const c0 = computeItems[0];
      const c1 = computeItems[1];
      lines.push('┌' + '─'.repeat(14) + '┐   ┌' + '─'.repeat(14) + '┐');
      lines.push('│' + c0.substring(0, 14).padStart(Math.floor((14 + Math.min(c0.length, 14)) / 2)).padEnd(14) + '│   │' + c1.substring(0, 14).padStart(Math.floor((14 + Math.min(c1.length, 14)) / 2)).padEnd(14) + '│');
      lines.push('└' + '─'.repeat(14) + '┘   └' + '─'.repeat(14) + '┘');
      lines.push('       │              │');
      lines.push('       └──────┬───────┘');
      lines.push('              │');
    } else if (computeItems.length === 1) {
      const svcBox = makeBox(computeItems[0], 20);
      lines.push('  ' + svcBox.top);
      lines.push('  ' + svcBox.mid);
      lines.push('  ' + svcBox.bot);
      lines.push('         │');
    }

    const hasCache = tiers.cache.length > 0;
    const hasDb = tiers.database.length > 0;
    const hasStorage = tiers.storage.length > 0;
    const hasQueue = tiers.queue.length > 0;

    if (hasCache || hasDb || hasStorage) {
      if (hasCache && hasDb) {
        lines.push('    ┌────────┴────────┐');
        lines.push('    │                 │');
        lines.push('    ▼                 ▼');
        const cacheLabel = str(tiers.cache[0]).substring(0, 12);
        const dbLabel = str(tiers.database[0]).substring(0, 14);
        lines.push('┌' + '─'.repeat(14) + '┐   ┌' + '─'.repeat(16) + '┐');
        lines.push('│' + ('🔴 ' + cacheLabel).substring(0, 14).padStart(Math.floor((14 + cacheLabel.length + 3) / 2)).padEnd(14) + '│   │' + ('💾 ' + dbLabel).substring(0, 16).padStart(Math.floor((16 + dbLabel.length + 3) / 2)).padEnd(16) + '│');
        lines.push('└' + '─'.repeat(14) + '┘   └' + '─'.repeat(16) + '┘');
      } else if (hasDb) {
        lines.push('              │');
        lines.push('              ▼');
        const dbBox = makeBox('💾 ' + str(tiers.database[0]), 22);
        lines.push('     ' + dbBox.top);
        lines.push('     ' + dbBox.mid);
        lines.push('     ' + dbBox.bot);
      } else if (hasCache) {
        lines.push('              │');
        lines.push('              ▼');
        const cacheBox = makeBox('🔴 ' + str(tiers.cache[0]), 20);
        lines.push('     ' + cacheBox.top);
        lines.push('     ' + cacheBox.mid);
        lines.push('     ' + cacheBox.bot);
      }
    }

    if (hasStorage && detailed) {
      lines.push('');
      lines.push('         ┌───────────────────┐');
      lines.push('         │ 📦 ' + str(tiers.storage[0]).substring(0, 14).padEnd(14) + '│');
      lines.push('         └───────────────────┘');
    }

    if (hasQueue && detailed) {
      lines.push('');
      lines.push('  ╔══════════════════════════╗');
      lines.push('  ║ ⚡ ASYNC: ' + tiers.queue.map(str).slice(0, 2).join(', ').substring(0, 15).padEnd(15) + '║');
      lines.push('  ╚══════════════════════════╝');
    }

    if (dataFlow.length > 0 && detailed) {
      lines.push('');
      lines.push('  ┄┄┄ DATA FLOW ┄┄┄');
      dataFlow.slice(0, 3).forEach((flow, i) => {
        lines.push('  ' + (i + 1) + '. ' + str(flow).substring(0, 50));
      });
    }

    lines.push('');
    lines.push('  ════════════════════════════════════════');
    lines.push('  TECH: ' + techStack.map(str).slice(0, 6).join(' • ').substring(0, 45));
    lines.push('');

    return lines.join('\n');
  };

  const asciiDiagram = buildASCII();

  return (
    <div className="font-mono text-xs leading-snug bg-neutral-900 text-brand-400 p-4 rounded-lg overflow-x-auto whitespace-pre border border-neutral-700/50">
      {asciiDiagram}
    </div>
  );
}

export default function SystemDesignPanel({ systemDesign, eraserDiagram, autoGenerateEraser = false, onGenerateEraserDiagram, question, cloudProvider = 'auto' }) {
  const { isElectron } = useElectron();
  const [generatingEraser, setGeneratingEraser] = useState(false);
  const [diagramModal, setDiagramModal] = useState(false);
  const [proDiagramModal, setProDiagramModal] = useState(false);
  const [imageError, setImageError] = useState(false);

  const [generatingDiagram, setGeneratingDiagram] = useState(false);
  const [overviewDiagram, setOverviewDiagram] = useState(null);
  const [detailedDiagram, setDetailedDiagram] = useState(null);
  const [diagramError, setDiagramError] = useState(null);
  const [diagramDetailLevel, setDiagramDetailLevel] = useState('overview');
  const [showASCII, setShowASCII] = useState(true);

  const diagramData = diagramDetailLevel === 'detailed' ? detailedDiagram : overviewDiagram;
  const hasComparison = systemDesign?.comparison || systemDesign?.comparisonDiagram;

  useEffect(() => {
    if (eraserDiagram?.imageUrl) {
      setImageError(false);
    }
  }, [eraserDiagram?.imageUrl]);

  useEffect(() => {
    // Don't auto-generate diagrams for focused questions (SLIs, SLOs, metrics)
    if (systemDesign?.included && question && !overviewDiagram && !generatingDiagram && !diagramError && !systemDesign?.focusedAnswer) {
      const timer = setTimeout(() => {
        handleGenerateDiagram('overview');
      }, 500);
      return () => clearTimeout(timer);
    }
  }, [systemDesign?.included, question, systemDesign?.focusedAnswer]);

  const handleGenerateEraser = async () => {
    if (!onGenerateEraserDiagram) return;
    setGeneratingEraser(true);
    try {
      await onGenerateEraserDiagram();
    } finally {
      setGeneratingEraser(false);
    }
  };

  const handleGenerateDiagram = async (detailLevel = 'overview') => {
    if (!question) return;

    const cachedDiagram = detailLevel === 'detailed' ? detailedDiagram : overviewDiagram;
    if (cachedDiagram) {
      setDiagramDetailLevel(detailLevel);
      return;
    }

    setGeneratingDiagram(true);
    setDiagramError(null);
    setDiagramDetailLevel(detailLevel);

    try {
      const response = await fetch(`${API_URL}/api/diagram/generate`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          ...getAuthHeaders(),
        },
        body: JSON.stringify({
          question,
          cloudProvider: cloudProvider || 'auto',
          difficulty: 'medium',
          category: 'System Design',
          format: 'png',
          detailLevel: detailLevel
        }),
      });

      if (!response.ok) {
        let errorMessage = `Failed to generate diagram (${response.status})`;
        try {
          const errorData = await response.json();
          errorMessage = errorData.error || errorMessage;
        } catch {
          errorMessage = `Server error: ${response.status} ${response.statusText}`;
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();

      if (result.success && result.image_url) {
        const newDiagramData = {
          imageUrl: `${API_URL}${result.image_url}`,
          cloudProvider: result.cloud_provider,
          pythonCode: result.python_code,
          detailLevel: detailLevel
        };

        if (detailLevel === 'detailed') {
          setDetailedDiagram(newDiagramData);
        } else {
          setOverviewDiagram(newDiagramData);
        }
      } else {
        throw new Error(result.error || 'Diagram generation failed');
      }
    } catch (error) {
      console.error('[Diagram] Generation error:', error);
      setDiagramError(error.message);
    } finally {
      setGeneratingDiagram(false);
    }
  };

  if (!systemDesign || !systemDesign.included) {
    return null;
  }

  return (
    <div className="p-3 rounded-xl animate-fade-in bg-neutral-750 border border-neutral-700/50">
      {/* Header */}
      <div className="mb-3 pb-2 flex items-center justify-between border-b border-neutral-700/50">
        <div className="flex items-center gap-2">
          <div className="w-1.5 h-1.5 rounded-full bg-brand-400" />
          <span className="text-xs font-semibold uppercase tracking-wide text-neutral-200">System Design</span>
        </div>
      </div>

      <div className="space-y-3">
        {/* Focused Answer Mode - For SLI/SLO/concept questions */}
        {systemDesign.focusedAnswer && systemDesign.categories && (
          <>
            {/* Overview for focused answer */}
            {systemDesign.overview && (
              <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
                <p className="text-sm text-neutral-300 leading-relaxed">{systemDesign.overview}</p>
              </div>
            )}

            {/* Categories as Cards/Tables */}
            <div className="space-y-4">
              {systemDesign.categories.map((category, catIdx) => (
                <div key={catIdx} className="rounded-lg overflow-hidden border border-neutral-600/50">
                  <div className="bg-brand-400/10 px-4 py-2 border-b border-neutral-600/50">
                    <h4 className="text-sm font-semibold text-brand-400">{category.name}</h4>
                  </div>
                  <div className="bg-neutral-800/50">
                    <table className="w-full text-xs">
                      <thead>
                        <tr className="border-b border-neutral-700/50">
                          <th className="text-left px-3 py-2 text-neutral-400 font-semibold">Metric</th>
                          <th className="text-left px-3 py-2 text-neutral-400 font-semibold">Target</th>
                          <th className="text-left px-3 py-2 text-neutral-400 font-semibold">Measurement</th>
                          <th className="text-left px-3 py-2 text-neutral-400 font-semibold">Alert Threshold</th>
                        </tr>
                      </thead>
                      <tbody>
                        {category.items?.map((item, itemIdx) => (
                          <tr key={itemIdx} className="border-b border-neutral-700/30 last:border-b-0">
                            <td className="px-3 py-2 text-neutral-200 font-medium">{item.metric || item.name || '-'}</td>
                            <td className="px-3 py-2 text-brand-400 font-mono">{item.target || item.value || '-'}</td>
                            <td className="px-3 py-2 text-neutral-300">{item.measurement || item.description || '-'}</td>
                            <td className="px-3 py-2 text-warning-400">{item.alertThreshold || item.alert || '-'}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}

        {/* Full System Design Mode - Only render if NOT focused answer */}
        {!systemDesign.focusedAnswer && (
          <>
        {/* Overview */}
        {systemDesign.overview && (
          <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
            <h4 className="text-xs font-semibold uppercase tracking-wide mb-1.5 text-neutral-400">
              Overview
            </h4>
            <p className="text-sm text-neutral-300 leading-relaxed">{systemDesign.overview}</p>
          </div>
        )}

        {/* Requirements */}
        {systemDesign.requirements && (
          <div className="grid grid-cols-2 gap-3">
            {systemDesign.requirements.functional && systemDesign.requirements.functional.length > 0 && (
              <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 text-neutral-400">
                  Functional
                </h4>
                <ul className="space-y-1">
                  {systemDesign.requirements.functional.map((req, i) => (
                    <li key={i} className="text-xs text-neutral-300 flex items-start gap-2">
                      <span className="text-brand-400 mt-0.5 flex-shrink-0">•</span>
                      {req}
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {systemDesign.requirements.nonFunctional && systemDesign.requirements.nonFunctional.length > 0 && (
              <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 text-neutral-400">
                  Non-Functional
                </h4>
                <ul className="space-y-1">
                  {systemDesign.requirements.nonFunctional.map((req, i) => (
                    <li key={i} className="text-xs text-neutral-300 flex items-start gap-2">
                      <span className="text-brand-400 mt-0.5 flex-shrink-0">•</span>
                      {req}
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Architecture Components + Scalability */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
          {systemDesign.architecture && (
            <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
              <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 text-neutral-400">
                Components
              </h4>
              {systemDesign.architecture.components && systemDesign.architecture.components.length > 0 && (
                <div className="flex flex-wrap gap-1.5 mb-2">
                  {systemDesign.architecture.components.map((component, i) => (
                    <span
                      key={i}
                      className="px-2 py-0.5 bg-neutral-600/50 text-neutral-300 text-[10px] rounded border border-neutral-500/50"
                    >
                      {component}
                    </span>
                  ))}
                </div>
              )}
              {systemDesign.architecture.description && (
                <p className="text-xs text-neutral-200 leading-relaxed">{systemDesign.architecture.description}</p>
              )}
            </div>
          )}

          {systemDesign.scalability && systemDesign.scalability.length > 0 && (
            <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
              <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 text-neutral-400">
                Scalability
              </h4>
              <div className="flex flex-wrap gap-1.5">
                {systemDesign.scalability.map((item, i) => (
                  <span
                    key={i}
                    className="inline-flex items-center gap-1.5 px-2 py-0.5 bg-brand-400/10 text-brand-400 text-[10px] rounded border border-brand-400/30"
                    title={item}
                  >
                    <svg className="w-3 h-3 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                    </svg>
                    {item}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Edge Cases & Tradeoffs */}
        {(systemDesign.edgeCases?.length > 0 || systemDesign.tradeoffs?.length > 0) && (
          <div className="grid grid-cols-2 gap-3">
            {systemDesign.tradeoffs && systemDesign.tradeoffs.length > 0 && (
              <div className="rounded-lg p-3 bg-warning-500/10 border border-warning-500/30">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 flex items-center gap-1.5 text-warning-400">
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l-3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3" />
                  </svg>
                  Tradeoffs
                </h4>
                <ul className="space-y-1.5">
                  {systemDesign.tradeoffs.map((tradeoff, i) => (
                    <li key={i} className="text-xs text-warning-200 flex items-start gap-2">
                      <span className="text-warning-400 mt-0.5 flex-shrink-0">⚖</span>
                      <span>{typeof tradeoff === 'string' ? tradeoff.replace(/^Tradeoff \d+:\s*/i, '') : tradeoff}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
            {systemDesign.edgeCases && systemDesign.edgeCases.length > 0 && (
              <div className="rounded-lg p-3 bg-error-500/10 border border-error-500/30">
                <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 flex items-center gap-1.5 text-error-400">
                  <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                  Edge Cases
                </h4>
                <ul className="space-y-1.5">
                  {systemDesign.edgeCases.map((edge, i) => (
                    <li key={i} className="text-xs text-error-200 flex items-start gap-2">
                      <span className="text-error-400 mt-0.5 flex-shrink-0">⚠</span>
                      <span>{typeof edge === 'string' ? edge.replace(/^Edge case \d+:\s*/i, '') : edge}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        )}

        {/* Diagrams - Only show for full system design, NOT for focused questions */}
        {!systemDesign.focusedAnswer && (
        <div className="space-y-3">
          {/* ASCII Architecture Diagram */}
          <div className="rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50">
            <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 flex items-center justify-between text-neutral-400">
              <span className="flex items-center gap-1.5">
                Text Architecture
                <span className="px-1.5 py-0.5 bg-neutral-600/50 text-neutral-500 border border-neutral-500/50 rounded text-[9px] font-medium">
                  ASCII
                </span>
              </span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => setDiagramDetailLevel(diagramDetailLevel === 'detailed' ? 'overview' : 'detailed')}
                  className={`px-2 py-1 text-[10px] font-medium rounded border transition-all ${
                    diagramDetailLevel === 'detailed'
                      ? 'bg-info-500/10 text-info-400 border-info-500/30'
                      : 'bg-brand-400/10 text-brand-400 border-brand-400/30'
                  }`}
                >
                  {diagramDetailLevel === 'detailed' ? 'Detailed' : 'Overview'}
                </button>
              </div>
            </h4>
            <ASCIIDiagram systemDesign={systemDesign} detailed={diagramDetailLevel === 'detailed'} />
          </div>

          {/* Cloud Architecture Diagram */}
          <div
            className={`rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50 ${diagramData ? 'cursor-pointer hover:border-brand-400/30 group' : ''} transition-all`}
            onClick={() => diagramData && setDiagramModal(true)}
          >
            <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 flex items-center justify-between text-neutral-400">
              <span className="flex items-center gap-1.5">
                Visual Diagram
                {diagramData?.cloudProvider && (
                  <span className="px-1.5 py-0.5 bg-brand-400/10 text-brand-400 border border-brand-400/30 rounded text-[9px] font-medium uppercase">
                    {diagramData.cloudProvider}
                  </span>
                )}
              </span>
              <div className="flex items-center gap-2">
                {diagramData && (
                  <>
                    <span className="text-[9px] text-neutral-500 px-1.5 py-0.5 bg-neutral-600/50 rounded">
                      {diagramDetailLevel === 'detailed' ? 'Detailed' : 'Overview'}
                    </span>
                    <button
                      onClick={(e) => { e.stopPropagation(); setDiagramModal(true); }}
                      className="flex items-center gap-1 px-2 py-1 text-[10px] font-medium rounded border transition-all bg-brand-400 text-white border-brand-400 hover:bg-brand-500"
                    >
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
                      </svg>
                      Expand
                    </button>
                    {diagramDetailLevel !== 'detailed' && (
                      <button
                        onClick={(e) => { e.stopPropagation(); handleGenerateDiagram('detailed'); }}
                        disabled={generatingDiagram}
                        className={`flex items-center gap-1 px-2 py-1 text-[10px] font-medium rounded border transition-all ${
                          detailedDiagram
                            ? 'bg-info-500/10 text-info-400 border-info-500/30 hover:bg-info-500/20'
                            : 'bg-info-500 text-white border-info-500 hover:bg-info-600'
                        }`}
                      >
                        {detailedDiagram ? 'Deep Dive ✓' : 'Deep Dive'}
                      </button>
                    )}
                    {diagramDetailLevel === 'detailed' && (
                      <button
                        onClick={(e) => { e.stopPropagation(); handleGenerateDiagram('overview'); }}
                        disabled={generatingDiagram}
                        className="flex items-center gap-1 px-2 py-1 text-[10px] font-medium rounded border transition-all bg-neutral-600/50 text-neutral-300 border-neutral-500/50 hover:bg-neutral-600"
                      >
                        Overview ✓
                      </button>
                    )}
                  </>
                )}
                {!diagramData && !generatingDiagram && (
                  <>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleGenerateDiagram('overview'); }}
                      className="flex items-center gap-1 px-2 py-1 text-[10px] font-medium rounded border transition-all bg-brand-400 text-white border-brand-400 hover:bg-brand-500"
                    >
                      Overview
                    </button>
                    <button
                      onClick={(e) => { e.stopPropagation(); handleGenerateDiagram('detailed'); }}
                      className="flex items-center gap-1 px-2 py-1 text-[10px] font-medium rounded border transition-all bg-info-500 text-white border-info-500 hover:bg-info-600"
                    >
                      Deep Dive
                    </button>
                  </>
                )}
              </div>
            </h4>
            <div className="w-full">
              <CloudArchitectureDiagram
                imageUrl={diagramData?.imageUrl}
                loading={generatingDiagram}
                error={diagramError}
                cloudProvider={diagramData?.cloudProvider || cloudProvider}
              />
            </div>
          </div>

          {/* Professional Diagram (Eraser.io) */}
          {(autoGenerateEraser || eraserDiagram) && (
          <div
            className={`rounded-lg p-3 bg-neutral-700/30 border border-neutral-600/50 ${eraserDiagram ? 'cursor-pointer hover:border-brand-400/30 group' : ''} transition-all`}
            onClick={() => eraserDiagram && setProDiagramModal(true)}
          >
            <h4 className="text-xs font-semibold uppercase tracking-wide mb-2 flex items-center justify-between text-neutral-400">
              <span>Pro Diagram</span>
              <div className="flex items-center gap-2">
                {eraserDiagram && (
                  <button
                    onClick={(e) => { e.stopPropagation(); setProDiagramModal(true); }}
                    className="flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium rounded border transition-all bg-brand-400 text-white border-brand-400 hover:bg-brand-500"
                  >
                    <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 8V4m0 0h4M4 4l5 5m11-1V4m0 0h-4m4 0l-5 5M4 16v4m0 0h4m-4 0l5-5m11 5l-5-5m5 5v-4m0 4h-4" />
                    </svg>
                    Expand
                  </button>
                )}
                {onGenerateEraserDiagram && !eraserDiagram && (
                  <button
                    onClick={(e) => { e.stopPropagation(); handleGenerateEraser(); }}
                    disabled={generatingEraser}
                    className={`flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium rounded border transition-all ${
                      generatingEraser
                        ? 'bg-neutral-600/50 text-neutral-400 border-neutral-500/50'
                        : 'bg-brand-400 text-white border-brand-400 hover:bg-brand-500'
                    }`}
                  >
                    {generatingEraser ? (
                      <>
                        <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                        </svg>
                        Generating...
                      </>
                    ) : (
                      <>
                        <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
                        </svg>
                        Generate
                      </>
                    )}
                  </button>
                )}
              </div>
            </h4>

            {eraserDiagram ? (
              <div className="w-full">
                {imageError ? (
                  <div className="rounded-lg border border-neutral-600/50 bg-neutral-800 p-4">
                    <p className="text-xs text-neutral-400 mb-2">Failed to load diagram image</p>
                    <p className="text-[10px] text-neutral-500 mb-2 break-all">URL: {eraserDiagram.imageUrl?.substring(0, 100)}...</p>
                    {eraserDiagram.editUrl && (
                      <a
                        href={eraserDiagram.editUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        onClick={(e) => e.stopPropagation()}
                        className="inline-flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium rounded bg-neutral-700 text-neutral-300 border border-neutral-600/50 hover:bg-neutral-600"
                      >
                        View on Eraser.io
                      </a>
                    )}
                  </div>
                ) : (
                  <div className="rounded-lg overflow-hidden border border-neutral-600/50 bg-neutral-800">
                    <img
                      src={eraserDiagram.imageUrl}
                      alt="Architecture Diagram"
                      className="w-full h-auto"
                      onError={(e) => {
                        console.error('Eraser image failed to load:', eraserDiagram.imageUrl);
                        setImageError(true);
                      }}
                    />
                  </div>
                )}
                {!imageError && eraserDiagram.editUrl && (
                  <a
                    href={eraserDiagram.editUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="mt-2 inline-flex items-center gap-1.5 px-2.5 py-1 text-[10px] font-medium rounded bg-neutral-700 text-neutral-300 border border-neutral-600/50 hover:bg-neutral-600"
                  >
                    <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    Edit on Eraser.io
                  </a>
                )}
              </div>
            ) : (
              <div className="text-center py-6 text-neutral-500">
                <svg className="w-8 h-8 mx-auto mb-2 text-neutral-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2" />
                </svg>
                <p className="text-[10px]">Click Generate for professional diagram</p>
              </div>
            )}
          </div>
          )}
        </div>
        )}

        {/* Tech Justifications */}
        {systemDesign.techJustifications && systemDesign.techJustifications.length > 0 && (
          <CollapsibleSection
            title="Why These Technologies?"
            defaultOpen={true}
            badge={`${systemDesign.techJustifications.length}`}
          >
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
              {systemDesign.techJustifications.map((item, i) => (
                <div key={i} className="bg-neutral-800 border border-neutral-700/50 rounded-lg p-3 hover:border-brand-400/30 transition-colors">
                  <div className="flex flex-wrap items-center gap-1.5 mb-2">
                    <span className="px-1.5 py-0.5 bg-brand-500 text-white text-[10px] font-semibold rounded">
                      {item.tech}
                    </span>
                    {item.category && (
                      <span className="px-1.5 py-0.5 bg-neutral-700 text-neutral-400 text-[9px] font-medium rounded">
                        {item.category}
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-neutral-300 leading-relaxed mb-2">
                    {item.why}
                  </p>
                  <div className="space-y-1 text-[10px]">
                    {item.without && (
                      <p className="text-neutral-300">
                        <span className="font-semibold text-neutral-200">Risk:</span> {item.without}
                      </p>
                    )}
                    {item.alternatives && (
                      <p className="text-brand-400">
                        <span className="font-semibold">Alt:</span> {item.alternatives}
                      </p>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CollapsibleSection>
        )}

        {/* Comparison Section */}
        {systemDesign.comparison && (
          <CollapsibleSection
            title="Comparison"
            defaultOpen={true}
          >
            <div className="grid grid-cols-2 gap-3">
              {systemDesign.comparison.approach1 && (
                <div className="rounded-lg p-3 bg-neutral-800 border border-neutral-700/50">
                  <h5 className="text-xs font-bold text-neutral-200 mb-2 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-info-400"></span>
                    {systemDesign.comparison.approach1.name || 'Approach 1'}
                  </h5>
                  {systemDesign.comparison.approach1.pros && (
                    <div className="mb-2">
                      <span className="text-[9px] font-semibold text-brand-400 uppercase">Pros</span>
                      <ul className="mt-1 space-y-0.5">
                        {systemDesign.comparison.approach1.pros.map((pro, i) => (
                          <li key={i} className="text-[10px] text-neutral-200 flex items-start gap-1.5">
                            <span className="text-brand-400 mt-0.5">+</span>
                            {pro}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {systemDesign.comparison.approach1.cons && (
                    <div>
                      <span className="text-[9px] font-semibold text-error-400 uppercase">Cons</span>
                      <ul className="mt-1 space-y-0.5">
                        {systemDesign.comparison.approach1.cons.map((con, i) => (
                          <li key={i} className="text-[10px] text-neutral-200 flex items-start gap-1.5">
                            <span className="text-error-400 mt-0.5">-</span>
                            {con}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
              {systemDesign.comparison.approach2 && (
                <div className="rounded-lg p-3 bg-neutral-800 border border-neutral-700/50">
                  <h5 className="text-xs font-bold text-neutral-200 mb-2 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-accent-purple"></span>
                    {systemDesign.comparison.approach2.name || 'Approach 2'}
                  </h5>
                  {systemDesign.comparison.approach2.pros && (
                    <div className="mb-2">
                      <span className="text-[9px] font-semibold text-brand-400 uppercase">Pros</span>
                      <ul className="mt-1 space-y-0.5">
                        {systemDesign.comparison.approach2.pros.map((pro, i) => (
                          <li key={i} className="text-[10px] text-neutral-200 flex items-start gap-1.5">
                            <span className="text-brand-400 mt-0.5">+</span>
                            {pro}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                  {systemDesign.comparison.approach2.cons && (
                    <div>
                      <span className="text-[9px] font-semibold text-error-400 uppercase">Cons</span>
                      <ul className="mt-1 space-y-0.5">
                        {systemDesign.comparison.approach2.cons.map((con, i) => (
                          <li key={i} className="text-[10px] text-neutral-200 flex items-start gap-1.5">
                            <span className="text-error-400 mt-0.5">-</span>
                            {con}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </div>
          </CollapsibleSection>
        )}
          </>
        )}

        {/* Cloud Architecture Diagram Modal */}
        <DiagramModal
          isOpen={diagramModal}
          onClose={() => setDiagramModal(false)}
          title={`Architecture Diagram${diagramData?.cloudProvider ? ` (${diagramData.cloudProvider.toUpperCase()})` : ''}`}
        >
          {diagramData && (
            <div className="max-w-full max-h-full">
              <CloudArchitectureDiagram
                imageUrl={diagramData.imageUrl}
                expanded={true}
                cloudProvider={diagramData.cloudProvider}
              />
            </div>
          )}
        </DiagramModal>

        {/* Pro Diagram Modal (Eraser.io) */}
        <DiagramModal
          isOpen={proDiagramModal}
          onClose={() => setProDiagramModal(false)}
          title="Pro Diagram"
        >
          {eraserDiagram && (
            <div className="max-w-full max-h-full">
              <img
                src={eraserDiagram.imageUrl}
                alt="Architecture Diagram"
                className="max-w-full max-h-[80vh] object-contain"
              />
              {eraserDiagram.editUrl && (
                <div className="mt-4 text-center">
                  <a
                    href={eraserDiagram.editUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium rounded-lg bg-neutral-700 text-neutral-200 border border-neutral-600/50 hover:bg-neutral-600 transition-colors"
                  >
                    <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                    </svg>
                    Edit on Eraser.io
                  </a>
                </div>
              )}
            </div>
          )}
        </DiagramModal>
      </div>
    </div>
  );
}
