-- Add onboarding fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS job_roles JSONB DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS resume_text TEXT DEFAULT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS technical_context TEXT DEFAULT NULL;
